<?php

namespace Knp\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    public function getMediaForAdmin($maxPerPage = 10, $currentPage = 1)
    {
        $qb = $this->createQueryBuilder('m')
            ->where('m.isAdmin = 1')
            ->orderBy('m.createdAt', 'DESC');


        $adapter = new DoctrineORMAdapter($qb);
        $pager = new Pagerfanta($adapter);
        $pager->setMaxPerPage($maxPerPage)->setCurrentPage($currentPage);

        return $pager;
    }
}
