_admin_giveaway:
    resource: "routing/admin.yml"
    prefix:   /admin/giveaways

_admin_giveaway_metrics:
    resource: "routing/metrics.yml"
    prefix:   /admin/metrics/giveaways

_giveaway_flash_message:
    pattern: /esi/USER_SPECIFIC/giveawayFlashMessage/{giveawayId}
    defaults: { _controller: GiveawayBundle:Giveaway:_giveawayFlashMessage }

_giveaway_show_actions:
    pattern: /esi/USER_SPECIFIC/giveawayShowMainActions/{giveawayId}
    defaults: { _controller: GiveawayBundle:Giveaway:_giveawayShowActions }

giveaway_index: 
    pattern: /giveaways
    defaults: { _controller: GiveawayBundle:Giveaway:index }

giveaway_show:
    pattern: /giveaways/{slug}/{keyId}
    defaults: { _controller: GiveawayBundle:Giveaway:show, keyId: null }
    requirements:
        keyId: \d+

giveaway_get_key:
    pattern: /giveaways/{giveawayId}/{slug}/key/{joinGroup}
    defaults: { _controller: GiveawayBundle:Giveaway:key, joinGroup: true }

giveaway_submit_machine_code:
    pattern: /giveaways/{slug}/machineCode
    defaults: { _controller: GiveawayBundle:Giveaway:machineCode }

GiveawayBundle_admin_deal:
    resource: "@GiveawayBundle/Resources/config/routing/admin_deal.yml"
    prefix:   /admin/deal

GiveawayBundle_deal:
    resource: "@GiveawayBundle/Resources/config/routing/deal.yml"
    prefix:   /deal

