services:
    pd_giveaway.giveaway_manager:
        class: Platformd\GiveawayBundle\Model\GiveawayManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@mailer"
            - "@translator"
            - "@router"
            - "%sender_email_address%"
            - "%sender_email_name%"