services:
    pd_giveaway.giveaway_manager:
        class: Platformd\GiveawayBundle\Model\GiveawayManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@translator"
            - "@router"
            - "@platformd.model.email_manager"
            - "%sender_email_address%"
            - "%sender_email_name%"
            - @event_filesystem

    platformd.model.deal_manager:
        class: Platformd\GiveawayBundle\Model\DealManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@knp_media.util.media_util"

