Platformd_UserBundle_admin_index:
    pattern: /
    defaults: { _controller: UserBundle:Admin:index }

Platformd_UserBundle_admin_edit:
    pattern: /{id}/edit
    defaults: { _controller: UserBundle:Admin:edit }

Platformd_UserBundle_admin_delete:
    pattern: /{id}/delete
    defaults: { _controller: UserBundle:Admin:delete }
    requirements:
        _method: POST|DELETE
