Platformd_UserBundle_admin_index:
    pattern: /
    defaults: { _controller: UserBundle:Admin:index }

Platformd_UserBundle_admin_filter:
    pattern: /filter
    requirements:
        _method: POST
    defaults: { _controller: UserBundle:Admin:filter }

admin_unapproved_avatars:
    pattern: /avatars
    defaults: { _controller: UserBundle:Admin:unapprovedAvatars }

Platformd_UserBundle_admin_suspend:
    pattern: /suspend/{id}
    defaults: { _controller: UserBundle:Suspend:suspend }
    requirements: { _method: POST }

Platformd_UserBundle_admin_ban:
    pattern: /ban/{id}
    defaults: { _controller: UserBundle:Suspend:ban }

Platformd_UserBundle_admin_unban:
    pattern: /unban/{id}
    defaults: { _controller: UserBundle:Suspend:unban }

Platformd_UserBundle_admin_show:
    pattern: /{id}
    requirements:
        _method: GET
    defaults: { _controller: UserBundle:Admin:show }

Platformd_UserBundle_admin_edit:
    pattern: /{id}/edit
    requirements:
        _method: GET
    defaults: { _controller: UserBundle:Admin:edit }

Platformd_UserBundle_admin_update:
    pattern: /{id}/edit
    requirements:
        _method: PUT
    defaults: { _controller: UserBundle:Admin:update }

Platformd_UserBundle_admin_delete:
    pattern: /{id}/delete
    defaults: { _controller: UserBundle:Admin:delete }
    requirements:
        _method: POST|DELETE|GET

Platformd_UserBundle_admin_logins:
    pattern: /{id}/logins
    defaults: { _controller: UserBundle:Admin:logins }

Platformd_UserBundle_admin_reset_password:
    pattern: /{id}/password/reset
    defaults: { _controller: UserBundle:Admin:resetPassword }
    requirements:
        _method: GET

Platformd_UserBundle_admin_avatar_list_remaining:
    pattern: /avatars/remaining
    defaults: { _controller: UserBundle:Admin\Avatar:listRemaining }
    requirements:
        _method: GET

Platformd_UserBundle_admin_avatar_disapprove_batch:
    pattern: /avatars/approve/batch
    defaults: { _controller: UserBundle:Admin\Avatar:batchSetApprove }
    requirements:
        _method: POST
