user_avatar_edit:
    pattern: /account/settings
    defaults: { _controller: UserBundle:Avatar:edit }
    requirements: { _method: GET }

user_avatar_update:
    pattern: /account/settings
    defaults: { _controller: UserBundle:Avatar:update }
    requirements: { _method: PUT }

user_avatar_toggle_selection:
    pattern: /account/settings/avatar/{id}/select
    defaults: { _controller: UserBundle:Avatar:toggleSelection }
    requirements: { _method: GET, id: "\d+" }
