_security_check:
    pattern: /login-check
    defaults: { _controller: UserBundle:Security:facebookSecurityCheck }

_security_logout:
    pattern: /logout
    defaults: { _controller: UserBundle:Security:facebookLogout }

facebook_deauthorize:
    pattern: /deauthorize
    defaults: { _controller: UserBundle:Security:facebookDeauthorize }
    requirements:
        _method: POST
