
# Page Routes

page_new:
    path:    /pages/new
    defaults:   { _controller: IdeaBundle:Admin:htmlPageForm }

page_view:
    path:    /pages/{id}
    defaults:   { _controller: IdeaBundle:Idea:htmlPageView }

page_edit:
    path:    /pages/{id}/edit
    defaults:   { _controller: IdeaBundle:Admin:htmlPageForm }

page_delete:
    path:    /pages/{id}/delete
    defaults:   { _controller: IdeaBundle:Admin:htmlPageDelete }

# Sponsor Routes

sponsors:
    path:    /sponsors
    defaults:   { _controller: IdeaBundle:Idea:sponsors }

sponsor_view:
    path:    /sponsors/{id}
    defaults:   { _controller: IdeaBundle:Idea:sponsorView }

sponsor_form:
    path:    /sponsors/{id}/edit
    defaults:   { _controller: IdeaBundle:Idea:sponsorForm }

sponsor_add_form:
    path:    /sponsors/{id}/addSponsor
    defaults:   { _controller: IdeaBundle:Idea:sponsorAddForm }

sponsor_remove:
    path:    /sponsors/{id}/remove
    defaults:   { _controller: IdeaBundle:Idea:sponsorRemove }

sponsor_delete:
    path:    /sponsors/{id}/delete
    defaults:   { _controller: IdeaBundle:Idea:sponsorDelete }

recommend_sponsor_list:
    path:    /recommendSponsor
    defaults:   { _controller: IdeaBundle:Idea:recommendSponsorList }

recommend_sponsor:
    path:    /recommendSponsor/{department_id}
    defaults:   { _controller: IdeaBundle:Idea:recommendSponsor }

update_sponsorship_status:
    path:    /updateSponsorshipStatus/{sponsorship_id}
    defaults:   { _controller: IdeaBundle:Idea:updateSponsorshipStatus }

# EntrySet Routes

entry_set_view:
    path:    /list/{entrySetId}
    defaults:   { _controller: IdeaBundle:Idea:entrySetView }

entry_set_new:
    path:    /list/{entrySetId}/form
    defaults:   { _controller: IdeaBundle:Admin:entrySet }

entry_set_edit:
    path:    /list/{entrySetId}/edit
    defaults:   { _controller: IdeaBundle:Admin:entrySet }

entry_set_delete:
    path:    /list/{entrySetId}/delete
    defaults:   { _controller: IdeaBundle:Admin:entrySetDelete }

# Session Routes

event_session_schedule:
    path:    /{groupSlug}/event/{eventId}/sessions
    defaults:   { _controller: IdeaBundle:Idea:eventSessions }

event_session_create:
    path:    /{groupSlug}/event/{eventId}/createSession
    defaults:   { _controller: IdeaBundle:Admin:eventSession }

event_session_edit:
    path:    /{groupSlug}/event/{eventId}/session/{sessionId}/edit
    defaults:   { _controller: IdeaBundle:Admin:eventSession }

event_session_delete:
    path:    /{groupSlug}/event/{eventId}/session/{sessionId}/delete
    defaults:   { _controller: IdeaBundle:Admin:eventSessionDelete }

event_session_add_speaker:
    path:    /{groupSlug}/event/{eventId}/session/{sessionId}/addSpeaker
    defaults:   { _controller: IdeaBundle:Admin:addEventSessionSpeaker }

event_session_remove_speaker:
    path:    /{groupSlug}/event/{eventId}/session/{sessionId}/removeSpeaker/{userId}
    defaults:   { _controller: IdeaBundle:Admin:removeEventSessionSpeaker }

event_session:
    path:    /{groupSlug}/event/{eventId}/session/{sessionId}
    defaults:   { _controller: IdeaBundle:Idea:eventSession }


# Watching Routes

watch_event:
    path:    /watch/{eventId}
    defaults:   { _controller: IdeaBundle:Idea:watch }

unwatch_event:
    path:    /unwatch/{eventId}
    defaults:   { _controller: IdeaBundle:Idea:unwatch }

watch_group:
    path:    /watchGroup/{groupId}
    defaults:   { _controller: IdeaBundle:Idea:watchGroup }

unwatch_group:
    path:    /unwatchGroup/{groupId}
    defaults:   { _controller: IdeaBundle:Idea:unwatchGroup }

invite_user:
    path:    /inviteUser
    defaults:   { _controller: IdeaBundle:Idea:inviteUser }

dismiss_recommendation:
    path:    /dismissRec/{recType}/{recId}
    defaults:   { _controller: IdeaBundle:Idea:dismissRecommendation }

# Admin Routes

idea_admin_feedback:
    path:    /feedback
    defaults:   { _controller: IdeaBundle:Admin:feedback }

idea_admin_event:
    path:    /{groupSlug}/event/{eventId}/admin/configure
    defaults:   { _controller: IdeaBundle:Admin:event, eventId:newEvent}

idea_admin_global_event:
    path:    /publicEvent/{global_eventId}
    defaults:   { _controller: IdeaBundle:Admin:globalEvent, global_eventId:new}

idea_admin:
    path:    /{groupSlug}/event/{eventId}/admin
    defaults:   { _controller: IdeaBundle:Admin:admin }

idea_admin_criteria_all:
    path:    /{groupSlug}/event/{eventId}/admin/criteriaList
    defaults:   { _controller: IdeaBundle:Admin:criteriaList }

idea_admin_criteria_get:
    path:    /{groupSlug}/event/{eventId}/admin/criteria/{id}
    defaults:   { _controller: IdeaBundle:Admin:criteria }
    requirements:
      _method: GET

idea_admin_assign:
    path:    /list/{entrySetId}/entry/{entryId}/assign
    defaults:   { _controller: IdeaBundle:Admin:assignJudges }
    requirements:
     _method: POST

idea_admin_criteria:
    path:    /{groupSlug}/event/{eventId}/admin/criteria
    defaults:   { _controller: IdeaBundle:Admin:criteria }

idea_admin_member_approvals:
    path:    /{groupSlug}/event/{eventId}/admin/approvals
    defaults:   { _controller: IdeaBundle:Admin:approvals }

idea_admin_process_approval:
    path:    /{groupSlug}/event/{eventId}/admin/approvals/{userId}/{action}
    defaults:   { _controller: IdeaBundle:Admin:processApproval }

idea_summary:
    path:    /{groupSlug}/event/{eventId}/admin/summary
    defaults:   { _controller: IdeaBundle:Admin:summary }
    requirements:
      _method:  GET

idea_advance:
    path:    /{groupSlug}/event/{eventId}/admin/advance
    defaults:   { _controller: IdeaBundle:Admin:advance }
    requirements:
      _method:  POST

idea_admin_images:
    path:    /{groupSlug}/event/{eventId}/admin/images
    defaults:   { _controller: IdeaBundle:Admin:images }
    requirements:
      _method: GET|POST

idea_admin_remove_image:
    path:    /{groupSlug}/event/{eventId}/admin/images/remove/{imageId}
    defaults:   { _controller: IdeaBundle:Admin:removeImage }
    requirements:
      _method: GET

idea_admin_export_ideas:
    path:    /{groupSlug}/event/{eventId}/admin/exportIdeas
    defaults:   { _controller: IdeaBundle:Admin:exportIdeas }
    requirements:
      _method: GET

idea_admin_export_users:
    path:    /{groupSlug}/event/{eventId}/admin/exportUsers
    defaults:   { _controller: IdeaBundle:Admin:exportUsers }
    requirements:
      _method: GET

idea_admin_export_votes:
    path:    /{groupSlug}/event/{eventId}/admin/exportVotes
    defaults:   { _controller: IdeaBundle:Admin:exportVotes }
    requirements:
      _method: GET

idea_admin_import_eventbrite_event:
    path:    /{groupSlug}/eb_event_import/{ebEventId}
    defaults:   { _controller: IdeaBundle:Admin:importEventbriteEvent }

idea_admin_import_meetup_event:
    path:    /{groupSlug}/mu_event_import/{muEventId}
    defaults:   { _controller: IdeaBundle:Admin:importMeetupEvent }


# Admin Scripts

update_session_speakers:
    path:    /admin/updateSessionSpeakers
    defaults:   { _controller: IdeaBundle:Admin:updateSessionSpeakers }

all_event_acl_fix:
    path:    /admin/fixEventACLs
    defaults:   { _controller: IdeaBundle:Admin:fixEventACLs }

add_entry_set_creators:
    path:    /admin/addEntrySetCreators
    defaults:   { _controller: IdeaBundle:Admin:addEntrySetCreators }

add_entry_set_registrations:
    path:    /admin/addEntrySetRegistrations
    defaults:   { _controller: IdeaBundle:Admin:addEntrySetRegistrationsToAllEvents }

create_depts_for_sponsors:
    path:    /admin/createDeptsForSponsors
    defaults:   { _controller: IdeaBundle:Admin:createDepartmentsForAllExistingSponsors }

associate_group_to_site:
    path:    /admin/associate_group_to_site/{groupSlug}
    defaults:   { _controller: IdeaBundle:Admin:associateGroupToSite }

import_svic:
    path:    /admin/import_svic
    defaults:   { _controller: IdeaBundle:Admin:importSvic }

# Entry Routes


idea_create:
    path:    /list/{entrySetId}/create
    defaults:   { _controller: IdeaBundle:Idea:create }
    requirements:
      _method: POST

idea_create_form:
    path:    /list/{entrySetId}/create
    defaults:   { _controller: IdeaBundle:Idea:createForm}
    requirements:
      _method: GET

idea_show:
    path:    /list/{entrySetId}/entry/{entryId}
    defaults:   { _controller: IdeaBundle:Idea:show }
    requirements:
      _method: GET

idea_edit:
    path:    /list/{entrySetId}/entry/{entryId}/edit
    defaults:   { _controller: IdeaBundle:Idea:edit }
    requirements:
      _method: POST

idea_edit_form:
    path:    /list/{entrySetId}/entry/{entryId}/edit
    defaults:   { _controller: IdeaBundle:Idea:editForm }
    requirements:
      _method: GET

idea_upload:
    path:    /list/{entrySetId}/entry/{entryId}/upload
    defaults:   { _controller: IdeaBundle:Idea:upload }
    requirements:
     _method:   POST

idea_upload_form:
    path:    /list/{entrySetId}/entry/{entryId}/upload
    defaults:   { _controller: IdeaBundle:Idea:upload }
    requirements:
      _method: GET

idea_image_delete:
    path:    /list/{entrySetId}/entry/{entryId}/deleteImage
    defaults:   { _controller: IdeaBundle:Idea:deleteImage }

idea_add_link:
    path:    /list/{entrySetId}/entry/{entryId}/addLink
    defaults:   { _controller: IdeaBundle:Idea:addLink }
    requirements:
     _method: POST

idea_add_link_form:
    path:    /list/{entrySetId}/entry/{entryId}/addLink
    defaults:   { _controller: IdeaBundle:Idea:addLink }
    requirements:
     _method: GET

idea_link_delete:
    path:    /list/{entrySetId}/entry/{entryId}/deleteLink
    defaults:   { _controller: IdeaBundle:Idea:deleteLink }

idea_follow:
    path:    /list/{entrySetId}/entry/{entryId}/follow
    defaults:   { _controller: IdeaBundle:Idea:follow }
    requirements:
     _method:   POST

idea_vote:
    path:    /list/{entrySetId}/entry/{entryId}/vote
    defaults:   { _controller: IdeaBundle:Idea:vote }
    requirements:
     _method:   POST

idea_comment:
    path:    /list/{entrySetId}/entry/{entryId}/comment
    defaults:   { _controller: IdeaBundle:Idea:comment }
    requirements:
     _method:   POST

idea_complete:
    path:    /list/{entrySetId}/entry/{entryId}/complete
    defaults:   { _controller: IdeaBundle:Idea:toggleCompleted }

idea_comment_delete:
    path:    /list/{entrySetId}/entry/{entryId}/commentDelete
    defaults:   { _controller: IdeaBundle:Idea:commentDelete }

idea_delete:
    path:    /list/{entrySetId}/entry/{entryId}/delete
    defaults:   { _controller: IdeaBundle:Idea:delete }

idea_add_speaker:
    path:    /list/{entrySetId}/entry/{entryId}/addSpeaker
    defaults:   { _controller: IdeaBundle:Idea:addIdeaSpeaker }

idea_remove_speaker:
    path:    /list/{entrySetId}/entry/{entryId}/removeSpeaker/{userId}
    defaults:   { _controller: IdeaBundle:Idea:removeIdeaSpeaker }

# Account Routes

profile:
    path:    /profile/{userId}
    defaults:   { _controller: IdeaBundle:Idea:profile, userId:null }

profile_edit:
    path:    /profile/{userId}/edit
    defaults:   { _controller: IdeaBundle:Idea:profileEdit }

contact_user:
    path:    /profile/{userId}/contact
    defaults:   { _controller: IdeaBundle:Idea:contactUser }

login:
    path:   /login
    defaults:  { _controller: FOSUserBundle:Registration:register }

logout:
    path:   /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

change_password:
    path:  /password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    requirements:
      _method: GET|POST
      _scheme: https

# Misc Routes

info_page:
    path:    /{groupSlug}/info/{page}
    defaults:   { _controller: IdeaBundle:Idea:infoPage }

event_registration:
    path:    /{groupSlug}/event/{eventId}/registrationForm
    defaults:   { _controller: IdeaBundle:Idea:eventRegistrationForm }

user_event_reg_answers:
    path:    /{groupSlug}/event/{eventId}/user/{userId}
    defaults:   { _controller: IdeaBundle:Idea:userRegistrationAnswers }
    
