
profile:
    pattern:    /profile/{userId}
    defaults:   { _controller: IdeaBundle:Idea:profile, userId:null }

profile_edit:
    pattern:    /profile/{userId}/edit
    defaults:   { _controller: IdeaBundle:Idea:profileEdit }

# EntrySet Routes

entry_set_view:
    pattern:    /list/{entrySetId}
    defaults:   { _controller: IdeaBundle:Idea:entrySetView }

entry_set_new:
    pattern:    /list/{entrySetId}/form
    defaults:   { _controller: IdeaBundle:Admin:entrySet }

entry_set_edit:
    pattern:    /list/{entrySetId}/edit
    defaults:   { _controller: IdeaBundle:Admin:entrySet }

entry_set_delete:
    pattern:    /list/{entrySetId}/delete
    defaults:   { _controller: IdeaBundle:Admin:entrySetDelete }

# ADMIN ROUTES

idea_admin_event:
    pattern:    /{groupSlug}/event/{eventId}/admin/configure
    defaults:   { _controller: IdeaBundle:Admin:event, eventId:newEvent}

idea_admin:
    pattern:    /{groupSlug}/event/{eventId}/admin
    defaults:   { _controller: IdeaBundle:Admin:admin }

idea_admin_criteria_all:
    pattern:    /{groupSlug}/event/{eventId}/admin/criteriaList
    defaults:   { _controller: IdeaBundle:Admin:criteriaList }

idea_admin_criteria_get:
    pattern:    /{groupSlug}/event/{eventId}/admin/criteria/{id}
    defaults:   { _controller: IdeaBundle:Admin:criteria }
    requirements:
      _method: GET

idea_admin_assign:
    pattern:    /list/{entrySetId}/entry/{entryId}/assign
    defaults:   { _controller: IdeaBundle:Admin:assignJudges }
    requirements:
     _method: POST

idea_admin_criteria:
    pattern:    /{groupSlug}/event/{eventId}/admin/criteria
    defaults:   { _controller: IdeaBundle:Admin:criteria }

idea_admin_member_approvals:
    pattern:    /{groupSlug}/event/{eventId}/admin/approvals
    defaults:   { _controller: IdeaBundle:Admin:approvals }

idea_admin_process_approval:
    pattern:    /{groupSlug}/event/{eventId}/admin/approvals/{userId}/{approval}
    defaults:   { _controller: IdeaBundle:Admin:processApproval }

idea_summary:
    pattern:    /{groupSlug}/event/{eventId}/admin/summary
    defaults:   { _controller: IdeaBundle:Admin:summary }
    requirements:
      _method:  GET

idea_advance:
    pattern:    /{groupSlug}/event/{eventId}/admin/advance
    defaults:   { _controller: IdeaBundle:Admin:advance }
    requirements:
      _method:  POST

idea_admin_images:
    pattern:    /{groupSlug}/event/{eventId}/admin/images
    defaults:   { _controller: IdeaBundle:Admin:images }
    requirements:
      _method: GET|POST

idea_admin_remove_image:
    pattern:    /{groupSlug}/event/{eventId}/admin/images/remove/{imageId}
    defaults:   { _controller: IdeaBundle:Admin:removeImage }
    requirements:
      _method: GET

idea_admin_export_ideas:
    pattern:    /{groupSlug}/event/{eventId}/admin/exportIdeas
    defaults:   { _controller: IdeaBundle:Admin:exportIdeas }
    requirements:
      _method: GET

idea_admin_export_users:
    pattern:    /{groupSlug}/event/{eventId}/admin/exportUsers
    defaults:   { _controller: IdeaBundle:Admin:exportUsers }
    requirements:
      _method: GET

idea_admin_export_votes:
    pattern:    /{groupSlug}/event/{eventId}/admin/exportVotes
    defaults:   { _controller: IdeaBundle:Admin:exportVotes }
    requirements:
      _method: GET

# NON-ADMIN

idea_create:
    pattern:    /list/{entrySetId}/create
    defaults:   { _controller: IdeaBundle:Idea:create }
    requirements:
      _method: POST

idea_create_form:
    pattern:    /list/{entrySetId}/create
    defaults:   { _controller: IdeaBundle:Idea:createForm}
    requirements:
      _method: GET

idea_show:
    pattern:    /list/{entrySetId}/entry/{entryId}
    defaults:   { _controller: IdeaBundle:Idea:show }
    requirements:
      _method: GET


idea_edit:
    pattern:    /list/{entrySetId}/entry/{entryId}/edit
    defaults:   { _controller: IdeaBundle:Idea:edit }
    requirements:
      _method: POST

idea_edit_form:
    pattern:    /list/{entrySetId}/entry/{entryId}/edit
    defaults:   { _controller: IdeaBundle:Idea:editForm }
    requirements:
      _method: GET

idea_upload:
    pattern:    /list/{entrySetId}/entry/{entryId}/upload
    defaults:   { _controller: IdeaBundle:Idea:upload }
    requirements:
     _method:   POST

idea_upload_form:
    pattern:    /list/{entrySetId}/entry/{entryId}/upload
    defaults:   { _controller: IdeaBundle:Idea:upload }
    requirements:
      _method: GET

idea_image_delete:
    pattern:    /list/{entrySetId}/entry/{entryId}/deleteImage
    defaults:   { _controller: IdeaBundle:Idea:deleteImage }
    requirements:
     _method: POST

idea_add_link:
    pattern:    /list/{entrySetId}/entry/{entryId}/addLink
    defaults:   { _controller: IdeaBundle:Idea:addLink }
    requirements:
     _method: POST

idea_add_link_form:
    pattern:    /list/{entrySetId}/entry/{entryId}/addLink
    defaults:   { _controller: IdeaBundle:Idea:addLink }
    requirements:
     _method: GET

idea_link_delete:
    pattern:    /list/{entrySetId}/entry/{entryId}/deleteLink
    defaults:   { _controller: IdeaBundle:Idea:deleteLink }
    requirements:
     _method: POST

idea_follow:
    pattern:    /list/{entrySetId}/entry/{entryId}/follow
    defaults:   { _controller: IdeaBundle:Idea:follow }
    requirements:
     _method:   POST

idea_vote:
    pattern:    /list/{entrySetId}/entry/{entryId}/vote
    defaults:   { _controller: IdeaBundle:Idea:vote }
    requirements:
     _method:   POST

idea_comment:
    pattern:    /list/{entrySetId}/entry/{entryId}/comment
    defaults:   { _controller: IdeaBundle:Idea:comment }
    requirements:
     _method:   POST

idea_comment_delete:
    pattern:    /list/{entrySetId}/entry/{entryId}/commentDelete
    defaults:   { _controller: IdeaBundle:Idea:commentDelete }
    requirements:
     _method:    POST

idea_delete:
    pattern:    /list/{entrySetId}/entry/{entryId}/delete
    defaults:   { _controller: IdeaBundle:Idea:delete }
#    requirements:
#     _method:   POST

login:
    pattern:   /login
    defaults:  { _controller: FOSUserBundle:Security:login }

logout:
    pattern:   /logout
    defaults: { _controller: FOSUserBundle:Security:logout }


change_password:
    pattern: /password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    requirements:
      _method: GET|POST

