<?php

namespace Platformd\GroupBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use DateTime;
use DateTimeZone;

/**
 * GroupNewssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupNewsRepository extends EntityRepository
{
    public function getNewsForGroupMostRecentFirst($group)
    {
        return $this->createQueryBuilder('gn')
            ->where('gn.group = :groupId')
            ->andWhere('gn.deleted = false')
            ->setParameter('groupId', $group->getId())
            ->orderBy('gn.createdAt', 'DESC')
            ->getQuery()
            ->execute();
    }

    public function getNewsCountForGroup($group, $fromDate=null, $thruDate=null)
    {
        $qb = $this->createQueryBuilder('gn');

        $qb->where('gn.group = :groupId');
        $qb->setParameter('groupId', $group->getId());

        if($fromDate != null and $thruDate != null)
        {
            $qb->andWhere('gn.createdAt >= :fromDate')
               ->andWhere('gn.createdAt <= :thruDate')
               ->setParameter('fromDate', $fromDate)
               ->setParameter('thruDate', $thruDate);
        }

        $total = $qb->getQuery()
                    ->getResult();

        return count($total);
    }
}
