<?php

namespace Platformd\GroupBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use DateTime;
use DateTimeZone;

/**
 * GroupVideosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupVideoRepository extends EntityRepository
{
    public function getVideosForGroupMostRecentFirst($group)
    {
        return $this->createQueryBuilder('gv')
            ->where('gv.group = :groupId')
            ->andWhere('gv.deleted = false')
            ->setParameter('groupId', $group->getId())
            ->orderBy('gv.createdAt', 'DESC')
            ->getQuery()
            ->execute();
    }

    public function getVideoCountForGroup($group, $fromDate=null, $thruDate=null)
    {
        $qb = $this->createQueryBuilder('gv');

        $qb->where('gv.group = :groupId');
        $qb->setParameter('groupId', $group->getId());

        if($fromDate != null and $thruDate != null)
        {
            $qb->andWhere('gv.createdAt >= :fromDate')
               ->andWhere('gv.createdAt <= :thruDate')
               ->setParameter('fromDate', $fromDate)
               ->setParameter('thruDate', $thruDate);
        }

        $total = $qb->getQuery()
                    ->getResult();

        return count($total);
    }
}
