accounts_index:
    pattern: /
    defaults: { _controller: SpoutletBundle:Account:account }

# profile page - null username means *this* user
accounts_profile:
    pattern: /profile/{username}
    defaults: { _controller: SpoutletBundle:Account:profile, username: null }

