accounts_index:
    path: /
    defaults: { _controller: SpoutletBundle:Account:account }

accounts_profile_edit:
    path: /profile/edit
    defaults: { _controller: SpoutletBundle:Account:editProfile }

accounts_events:
    path: /profile/events
    defaults: { _controller: SpoutletBundle:Account:events }

accounts_sponsorships:
    path: /profile/sponsorships
    defaults: { _controller: IdeaBundle:Idea:userSponsorships }

accounts_entrySets:
    path:  /profile/lists
    defaults: { _controller: IdeaBundle:Idea:userEntrySets }

accounts_entries:
    path: /profile/entries
    defaults: { _controller: IdeaBundle:Idea:userEntries }

accounts_pages:
    path: /profile/pages
    defaults: { _controller: IdeaBundle:Idea:userPages }

accounts_event_recommendations:
    path: /profile/eventRecommendations
    defaults: { _controller: IdeaBundle:Idea:userEventRecommendations }

accounts_group_recommendations:
    path: /profile/groupRecommendations
    defaults: { _controller: IdeaBundle:Idea:userGroupRecommendations }

accounts_giveaways:
    path: /profile/giveaways
    defaults: { _controller: SpoutletBundle:Account:giveaways }

accounts_deals:
    path: /profile/deals
    defaults: { _controller: SpoutletBundle:Account:deals }

accounts_groups:
    path: /profile/groups
    defaults: { _controller: SpoutletBundle:Account:groups }

videos_edit:
    path: /profile/videos
    defaults: { _controller: SpoutletBundle:Account:videos }

# profile page - null username means *this* user
accounts_profile:
    path: /profile/view/{username}
    defaults: { _controller: SpoutletBundle:Account:profile, username: null }

accounts_photos:
    path: /profile/photos/{filter}
    defaults: { _controller: SpoutletBundle:Account:photos, filter: 'all' }

accounts_videos:
    path: /profile/videos
    defaults: { _controller: SpoutletBundle:Account:videos }

accounts_settings:
    path: /settings
    defaults: { _controller: SpoutletBundle:Account:settings }

accounts_incomplete:
    path: /incomplete
    defaults: { _controller: SpoutletBundle:Account:incomplete }

accounts_change_password:
    path: /change-password
    defaults: { _controller: SpoutletBundle:Account:settings }

subscription_settings:
    path: /subscription-settings
    defaults: { _controller: SpoutletBundle:Account:subscriptionSettings }

accounts_unsubscribe:
    path: /unsubscribe/{email}
    defaults: { _controller: SpoutletBundle:Account:unsubscribe, email: null }

accounts_tradeshow_confirm:
    path: /tradeshow/confirm/{token}
    defaults: { _controller: SpoutletBundle:Account:confirmTradeshowReg, token: null }
