accounts_index:
    pattern: /
    defaults: { _controller: SpoutletBundle:Account:account }

accounts_profile_edit:
    pattern: /profile/edit
    defaults: { _controller: SpoutletBundle:Account:editProfile }

accounts_events:
    pattern: /profile/events
    defaults: { _controller: SpoutletBundle:Account:events }

accounts_entrySets:
    pattern:  /profile/lists
    defaults: { _controller: IdeaBundle:Idea:userEntrySets }

accounts_entries:
    pattern: /profile/entries
    defaults: { _controller: IdeaBundle:Idea:userEntries }

accounts_giveaways:
    pattern: /profile/giveaways
    defaults: { _controller: SpoutletBundle:Account:giveaways }

accounts_deals:
    pattern: /profile/deals
    defaults: { _controller: SpoutletBundle:Account:deals }

accounts_groups:
    pattern: /profile/groups
    defaults: { _controller: SpoutletBundle:Account:groups }

videos_edit:
    pattern: /profile/videos
    defaults: { _controller: SpoutletBundle:Account:videos }

# profile page - null username means *this* user
accounts_profile:
    pattern: /profile/view/{username}
    defaults: { _controller: SpoutletBundle:Account:profile, username: null }

accounts_photos:
    pattern: /profile/photos/{filter}
    defaults: { _controller: SpoutletBundle:Account:photos, filter: 'all' }

accounts_videos:
    pattern: /profile/videos
    defaults: { _controller: SpoutletBundle:Account:videos }

accounts_settings:
    pattern: /settings
    defaults: { _controller: SpoutletBundle:Account:settings }

accounts_incomplete:
    pattern: /incomplete
    defaults: { _controller: SpoutletBundle:Account:incomplete }

accounts_change_password:
    pattern: /change-password
    defaults: { _controller: SpoutletBundle:Account:settings }

subscription_settings:
    pattern: /subscription-settings
    defaults: { _controller: SpoutletBundle:Account:subscriptionSettings }

accounts_unsubscribe:
    pattern: /unsubscribe/{email}
    defaults: { _controller: SpoutletBundle:Account:unsubscribe, email: null }

accounts_tradeshow_confirm:
    pattern: /tradeshow/confirm/{token}
    defaults: { _controller: SpoutletBundle:Account:confirmTradeshowReg, token: null }
