admin_group:
    pattern: /metrics
    defaults: { _controller: "SpoutletBundle:GroupAdmin:index" }

admin_group_find:
    pattern: /metrics/find-groups
    defaults: { _controller: "SpoutletBundle:GroupAdmin:find" }

admin_group_show:
    pattern: /metrics/{id}
    defaults: { _controller: "SpoutletBundle:GroupAdmin:show" }
