admin_index:
    pattern: /admin
    defaults: { _controller: SpoutletBundle:Admin:index }

admin_events_index:
    pattern: /admin/events
    defaults: { _controller: SpoutletBundle:Admin:events }

admin_events_new:
    pattern: /admin/events/new
    defaults: { _controller: SpoutletBundle:Admin:newEvent }

admin_events_edit:
    pattern: /admin/events/edit/{id}
    defaults: { _controller: SpoutletBundle:Admin:editEvent }

admin_event_approve:
    pattern: /admin/events/approve/{id}
    defaults: { _controller: SpoutletBundle:Admin:approveEvent }

admin_event_unpublish:
    pattern: /admin/events/unpublish/{id}
    defaults: { _controller: SpoutletBundle:Admin:unpublishEvent }

admin_user_approve_avatar:
    pattern: /admin/user/{id}/avatar/approve
    defaults: { _controller: UserBundle:Admin:approveAvatar }

# banner admin

admin_homepage_banner_index:
    pattern: /admin/homepage-banners
    defaults: { _controller: SpoutletBundle:HomepageBanner:index }

admin_homepage_banner_new:
    pattern: /admin/homepage-banners/new
    defaults: { _controller: SpoutletBundle:HomepageBanner:new }

admin_homepage_banner_move:
    pattern: /admin/homepage-banners/move/{id}/{direction}
    defaults: { _controller: SpoutletBundle:HomepageBanner:move }

admin_homepage_banner_edit:
    pattern: /admin/homepage-banners/edit/{id}
    defaults: { _controller: SpoutletBundle:HomepageBanner:edit }
    requirements:
        id: \d+

admin_homepage_banner_delete:
    pattern: /admin/homepage-banners/delete/{id}
    defaults: { _controller: SpoutletBundle:HomepageBanner:delete }
    requirements:
        id: \d+

admin_homepage_banner_list:
    pattern: /admin/homepage-banners/{site}
    defaults: { _controller: SpoutletBundle:HomepageBanner:list }

admin_locale_to_sites_migration:
    pattern: /admin/migrate-locales-to-sites
    defaults: { _controller: SpoutletBundle:SiteMigration:migrate }
