admin_contest_new:
    pattern: /new
    defaults: { _controller: "SpoutletBundle:ContestAdmin:new" }

admin_contest_create:
    pattern: /create
    defaults: { _controller: "SpoutletBundle:ContestAdmin:new" }
    requirements: { _method: post }

admin_contest_index:
    pattern: /
    defaults: { _controller: "SpoutletBundle:ContestAdmin:index" }

admin_contest_list:
    pattern: /{site}
    defaults: { _controller: "SpoutletBundle:ContestAdmin:list" }

admin_contest_edit:
    pattern: /{slug}/edit
    defaults: { _controller: "SpoutletBundle:ContestAdmin:edit" }

admin_contest_update:
    pattern:  /{slug}/update
    defaults: { _controller: "SpoutletBundle:ContestAdmin:edit" }
    requirements: { _method: post }
