admin_group_filter:
    pattern: /metrics/find-groups
    defaults: { _controller: "SpoutletBundle:GroupAdmin:filter" }
    requirements: { _method: POST }

admin_group_find:
    pattern: /metrics/find-groups
    defaults: { _controller: "SpoutletBundle:GroupAdmin:find" }
    requirements: { _method: GET }

admin_group_show:
    pattern: /{id}
    defaults: { _controller: "SpoutletBundle:GroupAdmin:show" }

admin_group_summary:
    pattern: /metrics/group-summary
    defaults: { _controller: "SpoutletBundle:GroupAdmin:summary" }

admin_group_export:
    pattern: /{groupId}/metrics/group-export/{type}
    defaults: { _controller: "SpoutletBundle:GroupAdmin:generateExportCsv" }

admin_group_content_report:
    pattern: /metrics/group-content-report/{id}
    defaults: { _controller: "SpoutletBundle:GroupAdmin:contentReport" }
