admin_group_find:
    pattern: /metrics/find-groups
    defaults: { _controller: "SpoutletBundle:GroupAdmin:find" }

admin_group_show:
    pattern: /{id}
    defaults: { _controller: "SpoutletBundle:GroupAdmin:show" }

admin_group_summary:
    pattern: /metrics/group-summary
    defaults: { _controller: "SpoutletBundle:GroupAdmin:summary" }
