admin_content_reports:
    pattern:  /list/
    defaults: { _controller: "SpoutletBundle:ContentReportAdmin:list" }

admin_content_reports_hide_complaint:
    pattern:  /list/hideComplaint/{contentReportId}
    defaults: { _controller: "SpoutletBundle:ContentReportAdmin:hideComplaint"  }

admin_content_reports_remove_content:
    pattern:  /list/removeContent/{contentReportId}
    defaults: { _controller: "SpoutletBundle:ContentReportAdmin:removeContent" }
