admin_game:
    pattern:  /
    defaults: { _controller: "SpoutletBundle:GameAdmin:index" }

admin_game_new:
    pattern:  /new
    defaults: { _controller: "SpoutletBundle:GameAdmin:new" }

admin_game_create:
    pattern:  /create
    defaults: { _controller: "SpoutletBundle:GameAdmin:create" }
    requirements: { _method: post }

admin_game_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SpoutletBundle:GameAdmin:edit" }

admin_game_update:
    pattern:  /{id}/update
    defaults: { _controller: "SpoutletBundle:GameAdmin:update" }
    requirements: { _method: post }

admin_game_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SpoutletBundle:GameAdmin:delete" }
    requirements: { _method: post }
