admin_gallery_new:
    pattern: /new
    defaults: { _controller: "SpoutletBundle:GalleryAdmin:new" }

admin_gallery_index:
    pattern: /
    defaults: { _controller: "SpoutletBundle:GalleryAdmin:index" }

admin_gallery_edit:
    pattern: /{slug}/edit
    defaults: { _controller: "SpoutletBundle:GalleryAdmin:edit" }

admin_gallery_create:
    pattern: /create
    defaults: { _controller: "SpoutletBundle:GalleryAdmin:new" }
    requirements: { _method: post }

admin_gallery_update:
    pattern:  /{slug}/update
    defaults: { _controller: "SpoutletBundle:GalleryAdmin:edit" }
    requirements: { _method: post }
