comments_thread:
    pattern: /thread/{threadId}
    defaults: { _controller: "SpoutletBundle:Comments:thread" }

comments_replies:
    pattern: /replies/{commentId}
    defaults: { _controller: "SpoutletBundle:Comments:replies" }

comments_new:
    pattern: /new
    defaults: { _controller: "SpoutletBundle:Comments:new" }
    requirements:
        _format: json
        _method: POST
