comments_thread:
    pattern: /comments/thread/{threadId}
    defaults: { _controller: "SpoutletBundle:Comments:thread" }

comments_new:
    pattern: /comments/new
    defaults: { _controller: "SpoutletBundle:Comments:new" }
    requirements:
        _format: json
        _method: POST

comments_edit:
    pattern: /comments/edit
    defaults: { _controller: "SpoutletBundle:Comments:edit" }
    requirements:
        _format: json
        _method: POST

comments_delete:
    pattern: /comments/delete
    defaults: { _controller: "SpoutletBundle:Comments:delete" }
    requirements:
        _format: json
        _method: POST

comments_vote:
    pattern: /comments/vote
    defaults: { _controller: "SpoutletBundle:Vote:vote" }
    requirements:
        _format: json
        _method: POST
