comments_thread:
    pattern: /thread/{threadId}
    defaults: { _controller: "SpoutletBundle:Comments:thread" }

comments_update_thread:
    pattern: /update-thread
    defaults: { _controller: "SpoutletBundle:Comments:updateThread" }
    requirements:
        _format: json
        _method: POST

comments_replies:
    pattern: /replies/{commentId}
    defaults: { _controller: "SpoutletBundle:Comments:replies" }

comments_new:
    pattern: /new
    defaults: { _controller: "SpoutletBundle:Comments:new" }
    requirements:
        _format: json
        _method: POST

comments_edit:
    pattern: /edit
    defaults: { _controller: "SpoutletBundle:Comments:edit" }
    requirements:
        _format: json
        _method: POST

comments_delete:
    pattern: /delete
    defaults: { _controller: "SpoutletBundle:Comments:delete" }
    requirements:
        _format: json
        _method: POST

comments_vote:
    pattern: /vote
    defaults: { _controller: "SpoutletBundle:Vote:vote" }
    requirements:
        _format: json
        _method: POST
