contest_index:
    pattern: /
    defaults: { _controller: SpoutletBundle:Contest:index }

contest_show:
    pattern: /{slug}
    defaults: { _controller: SpoutletBundle:Contest:show }

contest_enter:
    pattern: /enter/{slug}
    defaults: { _controller: SpoutletBundle:Contest:enter }

contest_submit:
    pattern: /submit/{slug}
    defaults: { _controller: SpoutletBundle:Contest:submit }

contest_submit_group:
    pattern: /submit-group/{slug}
    defaults: { _controller: SpoutletBundle:Contest:groupSubmit }
    requirements:
        _format: json
        _method: POST

contest_vote:
    pattern: /entries/{slug}
    defaults: { _controller: SpoutletBundle:Contest:vote }

contest_rules_show:
    pattern: /rules/{slug}
    defaults: { _controller: SpoutletBundle:Contest:rules }

contest_winners:
    pattern: /winners/{slug}
    defaults: { _controller: SpoutletBundle:Contest:winners }

contest_filter:
    pattern: /filter/{filter}
    defaults: { _controller: SpoutletBundle:Contest:filteredContests, filter: "image" }
