contest_index:
    pattern: /
    defaults: { _controller: SpoutletBundle:Contest:index }

contest_show:
    pattern: /{slug}
    defaults: { _controller: SpoutletBundle:Contest:show }

contest_enter:
    pattern: /enter/{slug}
    defaults: { _controller: SpoutletBundle:Contest:enter }

contest_submit:
    pattern: /submit/{slug}
    defaults: { _controller: SpoutletBundle:Contest:submit }

contest_vote:
    pattern: /vote/{slug}
    defaults: { _controller: SpoutletBundle:Contest:vote }

contest_rules_show:
    pattern: /rules/{slug}
    defaults: { _controller: SpoutletBundle:Contest:rules }

