contest_index:
    pattern: /{category}
    defaults: { _controller: SpoutletBundle:Contest:index, category: null }

contest_filter:
    pattern: /filter/{filter}
    defaults: { _controller: SpoutletBundle:Contest:filteredContests, filter: "image" }
