events_index:
    pattern: /
    defaults: { _controller: SpoutletBundle:Events:index }

events_current:
    pattern: /current
    defaults: { _controller: SpoutletBundle:Events:current }

events_past:
    pattern: /past
    defaults: { _controller: SpoutletBundle:Events:past }

events_detail:
    pattern: /{id}
    defaults: { _controller: SpoutletBundle:Events:event }