events_index:
    pattern: /
    defaults: { _controller: SpoutletBundle:Events:index }

events_current:
    pattern: /current
    defaults: { _controller: SpoutletBundle:Events:current }

events_past:
    pattern: /past
    defaults: { _controller: SpoutletBundle:Events:past }

events_detail:
    pattern: /{slug}
    defaults: { _controller: SpoutletBundle:Events:event }

events_register:
    pattern: /{slug}/register
    defaults: { _controller: SpoutletBundle:Events:register }

events_unregister:
    pattern: /{slug}/unregister
    defaults: { _controller: SpoutletBundle:Events:unregister }