gallery_index:
    pattern: /
    defaults: { _controller: SpoutletBundle:Gallery:index }

gallery_submit:
    pattern: /submit-photo
    defaults: { _controller: SpoutletBundle:Gallery:submit, site: ~ }
