gallery_index:
    pattern: /
    defaults: { _controller: SpoutletBundle:Gallery:index }

gallery_submit:
    pattern: /submit-photo
    defaults: { _controller: SpoutletBundle:Gallery:submit, site: ~ }

gallery_upload:
    pattern: /upload
    defaults: { _controller: SpoutletBundle:Gallery:upload, site: ~ }

gallery_edit_photos:
    pattern: /photos
    defaults: { _controller: SpoutletBundle:Gallery:editPhotos, site: ~ }

gallery_publish_photo:
    pattern: /publish
    defaults: { _controller: SpoutletBundle:Gallery:publish, site: ~ }
    requirements:
        _format: json
        _method: POST
