gallery_index:
    pattern: /
    defaults: { _controller: SpoutletBundle:Gallery:index }

gallery_index_data:
    pattern: /gallery-data
    defaults: { _controller: SpoutletBundle:Gallery:galleryData, site: ~ }

gallery_submit:
    pattern: /submit-photo
    defaults: { _controller: SpoutletBundle:Gallery:submit, site: ~ }

gallery_upload:
    pattern: /upload
    defaults: { _controller: SpoutletBundle:Gallery:upload, site: ~ }

gallery_edit_photos:
    pattern: /photos
    defaults: { _controller: SpoutletBundle:Gallery:editPhotos, site: ~ }

gallery_publish_photo:
    pattern: /publish
    defaults: { _controller: SpoutletBundle:Gallery:publish, site: ~ }
    requirements:
        _format: json
        _method: POST

gallery_media_show:
    pattern: /photo/{id}
    defaults: { _controller: SpoutletBundle:Gallery:show, site: ~ }

gallery_gallery_show:
    pattern: /{slug}
    defaults: { _controller: SpoutletBundle:Gallery:gallery, site: ~ }

gallery_delete_media:
    pattern: /delete-media/{id}
    defaults: { _controller: SpoutletBundle:Gallery:deleteMedia, site: ~ }

gallery_edit_media:
    pattern: /edit-media/{id}
    defaults: { _controller: SpoutletBundle:Gallery:editMedia, site: ~ }

gallery_feature_media:
    pattern: /feature-media/{id}
    defaults: { _controller: SpoutletBundle:Gallery:feature, site: ~ }

gallery_share_photo:
    pattern: /share/photo
    defaults: { _controller: SpoutletBundle:Gallery:sharePhoto, site: ~ }
