game_page_list:
    pattern:  /
    defaults: { _controller: "SpoutletBundle:GamePage:index" }

game_page_show:
    pattern:  /{category}/{slug}
    defaults: { _controller: "SpoutletBundle:GamePage:show" }