groups:
    pattern:  /
    defaults: { _controller: "SpoutletBundle:Group:index" }

group_new_getting_started:
    pattern:  /new-getting-started/
    defaults: { _controller: "SpoutletBundle:Group:newGettingStarted", site: ~ }

group_new:
    pattern:  /new/
    defaults: { _controller: "SpoutletBundle:Group:new", site: ~ }

group_create:
    pattern:  /create/
    defaults: { _controller: "SpoutletBundle:Group:new", site: ~ }

group_edit:
    pattern:  /{id}/edit/
    defaults: { _controller: "SpoutletBundle:Group:edit", site: ~ }

group_news:
    pattern: /{id}/news/
    defaults: { _controller: "SpoutletBundle:Group:news", site: ~ }

group_add_news:
    pattern:  /{id}/add-news/
    defaults: { _controller: "SpoutletBundle:Group:addNews", site: ~ }

group_delete_news:
    pattern:  /{id}/delete-news/{newsId}
    defaults: { _controller: "SpoutletBundle:Group:deleteNews", site: ~ }

group_edit_news:
    pattern:  /{id}/edit-news/{newsId}
    defaults: { _controller: "SpoutletBundle:Group:editNews", site: ~ }

group_images:
    pattern: /{id}/images/
    defaults: { _controller: "SpoutletBundle:Group:image", site: ~ }

group_add_image:
    pattern:  /{id}/add-image/
    defaults: { _controller: "SpoutletBundle:Group:addImage", site: ~ }

group_delete_image:
    pattern:  /{id}/delete-image/{imageId}
    defaults: { _controller: "SpoutletBundle:Group:deleteImage", site: ~ }

group_edit_image:
    pattern:  /{id}/edit-image/{imageId}
    defaults: { _controller: "SpoutletBundle:Group:editImage", site: ~ }

group_videos:
    pattern: /{id}/videos/
    defaults: { _controller: "SpoutletBundle:Group:videos", site: ~ }

group_add_video:
    pattern:  /{id}/add-video/
    defaults: { _controller: "SpoutletBundle:Group:addVideo", site: ~ }

group_delete_video:
    pattern:  /{id}/delete-video/{videoId}
    defaults: { _controller: "SpoutletBundle:Group:deleteVideo", site: ~ }

group_edit_video:
    pattern:  /{id}/edit-video/{videoId}
    defaults: { _controller: "SpoutletBundle:Group:editVideo", site: ~ }

group_discussions:
    pattern: /{id}/discussions/
    defaults: { _controller: "SpoutletBundle:Group:discussions", site: ~ }

group_enable_discussions:
    pattern: /{id}/discussions-enable/
    defaults: { _controller: "SpoutletBundle:Group:enableDiscussions", site: ~ }

group_disable_discussions:
    pattern: /{id}/discussions-disable/
    defaults: { _controller: "SpoutletBundle:Group:disableDiscussions", site: ~ }

group_add_discussion:
    pattern: /{id}/add-discussion/
    defaults: { _controller: "SpoutletBundle:Group:addDiscussion", site: ~ }

group_delete_discussion:
    pattern: /{id}/delete-discussion/{discussionId}
    defaults: { _controller: "SpoutletBundle:Group:deleteDiscussion", site: ~ }

group_edit_discussion:
    pattern: /{id}/edit-discussion/{discussionId}
    defaults: { _controller: "SpoutletBundle:Group:editDiscussion", site: ~ }

group_view_discussion:
    pattern: /{id}/discussion/{discussionId}
    defaults: { _controller: "SpoutletBundle:Group:viewDiscussion", site: ~ }

group_reply_discussion:
    pattern: /{id}/discussion/{discussionId}/reply
    defaults: { _controller: "SpoutletBundle:Group:replyDiscussion", site: ~ }

group_edit_discussion_post:
    pattern: /discussion-post/{id}/edit
    defaults: { _controller: "SpoutletBundle:Group:editDiscussionPost", site: ~ }

group_delete_discussion_post:
    pattern: /discussion-post/{id}/delete
    defaults: { _controller: "SpoutletBundle:Group:deleteDiscussionPost", site: ~ }

group_about:
    pattern: /{id}/about
    defaults: { _controller: "SpoutletBundle:Group:about", site: ~ }

group_leave:
    pattern:  /{id}/leave/
    defaults: { _controller: "SpoutletBundle:Group:leave", site: ~ }

group_join:
    pattern:  /{id}/join/
    defaults: { _controller: "SpoutletBundle:Group:join", site: ~ }

group_apply:
    pattern:  /{id}/apply/
    defaults: { _controller: "SpoutletBundle:Group:applyToGroup", site: ~ }

group_delete:
    pattern:  /{id}/delete/
    defaults: { _controller: "SpoutletBundle:Group:delete", site: ~ }

group_show:
    pattern:  /{slug}/
    defaults: { _controller: "SpoutletBundle:Group:show", site: ~ }

group_slug_show:
    pattern:  /{slug}/
    defaults: { _controller: "SpoutletBundle:Group:show", site: ~ }

group_update:
    pattern:  /{id}/update/
    defaults: { _controller: "SpoutletBundle:Group:edit", site: ~ }
    requirements: { _method: post }

group_applications:
    pattern:  /{id}/applications/
    defaults: { _controller: "SpoutletBundle:Group:applications", site: ~ }

group_accept_application:
    pattern:  /{id}/applications/{applicationId}/accept
    defaults: { _controller: "SpoutletBundle:Group:acceptApplication", site: ~ }

group_reject_application:
    pattern:  /{id}/applications/{applicationId}/reject
    defaults: { _controller: "SpoutletBundle:Group:rejectApplication", site: ~ }

group_members:
    pattern: /{id}/members
    defaults: { _controller: "SpoutletBundle:Group:members", site: ~ }

group_remove_member:
    pattern: /{id}/remove/{uid}
    defaults: { _controller: "SpoutletBundle:Group:remove", site: ~ }
