# shows a chooser for locales
group:
    pattern:  /
    defaults: { _controller: "SpoutletBundle:Group:index" }

group_new_getting_started:
    pattern:  /new-getting-started/
    defaults: { _controller: "SpoutletBundle:Group:newGettingStarted", site: ~ }

group_new:
    pattern:  /new/
    defaults: { _controller: "SpoutletBundle:Group:new", site: ~ }

group_create:
    pattern:  /create/
    defaults: { _controller: "SpoutletBundle:Group:new", site: ~ }

group_edit:
    pattern:  /{id}/edit/
    defaults: { _controller: "SpoutletBundle:Group:edit", site: ~ }

group_news:
    pattern: /{id}/news/
    defaults: { _controller: "SpoutletBundle:Group:news", site: ~ }

group_view_news:
    pattern:  /{id}/view-news/{newsId}
    defaults: { _controller: "SpoutletBundle:Group:viewNews", site: ~ }

group_add_news:
    pattern:  /{id}/add-news/
    defaults: { _controller: "SpoutletBundle:Group:addNews", site: ~ }

group_delete_news:
    pattern:  /{id}/delete-news/{newsId}
    defaults: { _controller: "SpoutletBundle:Group:deleteNews", site: ~ }

group_edit_news:
    pattern:  /{id}/edit-news/{newsId}
    defaults: { _controller: "SpoutletBundle:Group:editNews", site: ~ }

group_videos:
    pattern: /{id}/videos
    defaults: { _controller: "SpoutletBundle:Group:videos", site: ~ }

group_view_video:
    pattern:  /{id}/view-video/{videoId}
    defaults: { _controller: "SpoutletBundle:Group:viewVideo", site: ~ }

group_add_video:
    pattern:  /{id}/add-video/
    defaults: { _controller: "SpoutletBundle:Group:addVideo", site: ~ }

group_delete_video:
    pattern:  /{id}/delete-video/{videoId}
    defaults: { _controller: "SpoutletBundle:Group:deleteVideo", site: ~ }

group_edit_video:
    pattern:  /{id}/edit-video/{videoId}
    defaults: { _controller: "SpoutletBundle:Group:editVideo", site: ~ }

group_leave:
    pattern:  /{id}/leave/
    defaults: { _controller: "SpoutletBundle:Group:leave", site: ~ }

group_join:
    pattern:  /{id}/join/
    defaults: { _controller: "SpoutletBundle:Group:join", site: ~ }

group_delete:
    pattern:  /{id}/delete/
    defaults: { _controller: "SpoutletBundle:Group:delete", site: ~ }

group_show:
    pattern:  /{id}/show/
    defaults: { _controller: "SpoutletBundle:Group:show", site: ~ }

group_update:
    pattern:  /{id}/update/
    defaults: { _controller: "SpoutletBundle:Group:edit", site: ~ }
    requirements: { _method: post }

