gallery_delete_media:
    pattern: /delete/{id}
    defaults: { _controller: SpoutletBundle:Gallery:deleteMedia, site: ~ }

gallery_delete_media_ajax:
    pattern: /delete-ajax
    defaults: { _controller: SpoutletBundle:Gallery:deleteMediaAjax, site: ~ }
    requirements:
        _format: json
        _method: POST

gallery_edit_media:
    pattern: /edit/{id}
    defaults: { _controller: SpoutletBundle:Gallery:editMedia, site: ~ }

gallery_feature_media:
    pattern: /feature/{id}
    defaults: { _controller: SpoutletBundle:Gallery:feature, site: ~ }

gallery_share_photo:
    pattern: /share/photo
    defaults: { _controller: SpoutletBundle:Gallery:sharePhoto, site: ~ }
