takeover:
    pattern: /{returnUrl}
    defaults: { _controller: SpoutletBundle:SiteTakeover:takeover, returnUrl: null }

takeover_specified:
    pattern: /{id}
    defaults: { _controller: SpoutletBundle:SiteTakeover:takeoverSpecified }
