services:
    platformd.model.game_page_manager:
        class: Platformd\GameBundle\Model\GamePageManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@knp_media.util.media_util"
