services:
    platformd.events_manager:
        class: Platformd\SpoutletBundle\Entity\EventManager
        arguments:
            - @event_filesystem
            - @doctrine.orm.entity_manager
    
    platformd.event_banner_resolver:
        class:  'Platformd\SpoutletBundle\BannerPathResolver'
        arguments:
            - @event_filesystem
        parent: platformd.path_resolver
        tags:
            - { name: 'knp_media_exposer.resolver' }