default_index:
    pattern:  /
    defaults: { _controller: SpoutletBundle:Default:index }

privacy:
    pattern: /legal/privacy
    defaults: { _controller: SpoutletBundle:Default:privacy }

terms_conditions:
    pattern: /legal/terms
    defaults: { _controller: SpoutletBundle:Default:terms_conditions }

about:
    pattern: /about
    defaults: { _controller: SpoutletBundle:Default:about }

contact:
    pattern: /contact
    defaults: { _controller: SpoutletBundle:Default:contact }

microsoft:
    pattern: /microsoft
    defaults: { _controller: SpoutletBundle:Default:microsoft }

_spoutlet_admin:
    resource: routing/admin.yml

_spoutlet_events:
    resource: routing/events.yml
    prefix:   /events

_spoutlet_account:
    resource: routing/account.yml
    prefix:   /account

SpoutletBundle_age:
    resource: "@SpoutletBundle/Resources/config/routing/age.yml"
    prefix:   /age

SpoutletBundle_game_page:
    resource: "@SpoutletBundle/Resources/config/routing/game_page.yml"
    prefix:   /games

SpoutletBundle_admin_game:
    resource: "@SpoutletBundle/Resources/config/routing/admin_game.yml"
    prefix:   /admin/game

SpoutletBundle_admin_game_page:
    resource: "@SpoutletBundle/Resources/config/routing/admin_game_page.yml"
    prefix:   /admin/game-page