_main_user_strip:
    pattern: /esi/USER_SPECIFIC/mainUserStrip
    defaults: { _controller: SpoutletBundle:Default:_mainUserStrip }

_user_arp:
    pattern: /user/arp/{uuid}
    defaults: { _controller: SpoutletBundle:Default:_userArp, uuid: null}

_check_account_complete:
    pattern: /esi/USER_SPECIFIC/checkAccountComplete
    defaults: { _controller: SpoutletBundle:Default:_checkAccountComplete }

_flash_message:
    pattern: /esi/USER_SPECIFIC/flashMessage
    defaults: { _controller: SpoutletBundle:Default:_flashMessage }

_gallery_media_user_votes:
    pattern: /esi/USER_SPECIFIC/galleryMediaUserVotes
    defaults: { _controller: SpoutletBundle:Gallery:_galleryMediaUserVotes }

_gallery_media_show_user_data:
    pattern: /esi/USER_SPECIFIC/galleryMediaShowUserData/{id}
    defaults: { _controller: SpoutletBundle:Gallery:_galleryMediaShowUserData }

_layout_footer:
    pattern: /esi/COUNTRY_SPECIFIC/layoutFooter
    defaults: { _controller: SpoutletBundle:Default:_layoutFooter }

_groups_index:
    pattern: /groups-index
    defaults: { _controller: SpoutletBundle:Default:_groups }

_polls_index:
    pattern: /polls-index
    defaults: { _controller: SpoutletBundle:Default:_polls }

_arp_index:
    pattern: /arp-index
    defaults: { _controller: SpoutletBundle:Default:_arp }

force_logout:
    pattern: /forceLogout/{returnUrl}
    defaults: { _controller: SpoutletBundle:Default:forceLogout, returnUrl: '/' }

session_cookie:
    pattern: /sessionCookie
    defaults: { _controller: SpoutletBundle:Default:sessionCookie }

api_session_cookie:
    pattern: /setApiSessionCookie/{uuid}/{expires}
    defaults: { _controller: SpoutletBundle:Default:setApiSessionCookie, uuid: ~, expires: ~ }

api_session_cookie_refresh:
    pattern: /refreshApiSessionCookie/{uuid}
    defaults: { _controller: SpoutletBundle:Default:refreshApiSessionCookie, uuid: ~ }

default_index:
    pattern:  /
    defaults: { _controller: SpoutletBundle:Default:index }

health_check:
    pattern:  /healthCheck
    defaults: { _controller: SpoutletBundle:Default:healthCheck }

privacy:
    pattern: /legal/privacy
    defaults: { _controller: SpoutletBundle:Default:privacy }

terms_conditions:
    pattern: /legal/terms
    defaults: { _controller: SpoutletBundle:Default:terms_conditions }

about:
    pattern: /about
    defaults: { _controller: SpoutletBundle:Default:about }

contact:
    pattern: /contact
    defaults: { _controller: SpoutletBundle:Default:contact }

microsoft:
    pattern: /microsoft
    defaults: { _controller: SpoutletBundle:Default:microsoft }

banner:
    pattern: /banner
    defaults: { _controller: SpoutletBundle:Default:banner }

hot_stories:
    pattern: /hot-stories
    defaults: { _controller: SpoutletBundle:Default:hotStories }

featured_content:
    pattern: /featured-content
    defaults: { _controller: SpoutletBundle:Default:featuredContent }

video_feed:
    pattern: /video-feed/{height}
    defaults: { _controller: SpoutletBundle:Default:videoFeed, height: 252 }

content_reporting:
    pattern:  /report
    defaults: { _controller: "SpoutletBundle:ContentReporting:reportContent" }
    requirements:
        _format: json
        _method: POST

forums:
    pattern: /forums
    defaults: { _controller: SpoutletBundle:Default:forums }

arp:
    pattern: /arp
    defaults: { _controller: SpoutletBundle:Default:_arp }

_spoutlet_admin:
    resource: routing/admin.yml

_spoutlet_account:
    resource: routing/account.yml
    prefix:   /account

wallpapers:
    pattern: /wallpapers
    defaults: { _controller: SpoutletBundle:Default:wallpapers }

SpoutletBundle_age:
    resource: "@SpoutletBundle/Resources/config/routing/age.yml"
    prefix:   /age

SpoutletBundle_admin_content_reports:
    resource: "@SpoutletBundle/Resources/config/routing/admin_content_reports.yml"
    prefix:   /admin/contentReports

SpoutletBundle_gallery:
    resource: "@SpoutletBundle/Resources/config/routing/gallery.yml"
    prefix:   /galleries

SpoutletBundle_media:
    resource: "@SpoutletBundle/Resources/config/routing/media.yml"
    prefix:   /media

SpoutletBundle_contest:
    resource: "@SpoutletBundle/Resources/config/routing/contest.yml"
    prefix:   /contest

SpoutletBundle_contests:
    resource: "@SpoutletBundle/Resources/config/routing/contests.yml"
    prefix:   /contests

SpoutletBundle_admin_wallpapers:
    resource: "@SpoutletBundle/Resources/config/routing/admin_wallpaper.yml"
    prefix:   /admin/wallpapers

SpoutletBundle_comments:
    resource: "@SpoutletBundle/Resources/config/routing/comments.yml"
    prefix: /comments

SpoutletBundle_admin_gallery:
    resource: "@SpoutletBundle/Resources/config/routing/admin_gallery.yml"
    prefix:   /admin/galleries

SpoutletBundle_admin_contest:
    resource: "@SpoutletBundle/Resources/config/routing/admin_contest.yml"
    prefix:   /admin/contests

SpoutletBundle_admin_featured_media:
    resource: "@SpoutletBundle/Resources/config/routing/admin_featured_media.yml"
    prefix:   /admin/featured-media

SpoutletBundle_admin_background_ads:
    resource: "@SpoutletBundle/Resources/config/routing/admin_background_ads.yml"
    prefix:   /admin/background-ads

SpoutletBundle_admin_rsvp:
    resource: "@SpoutletBundle/Resources/config/routing/admin_rsvp.yml"
    prefix:   /admin/rsvp

SpoutletBundle_rsvp:
    resource: "@SpoutletBundle/Resources/config/routing/rsvp.yml"
    prefix:   /rsvp

SpoutletBundle_takeover:
    resource: "@SpoutletBundle/Resources/config/routing/takeover.yml"
    prefix:   /takeover

SpoutletBundle_admin_takeover:
    resource: "@SpoutletBundle/Resources/config/routing/admin_takeover.yml"
    prefix:   /admin/takeover

SpoutletBundle_admin_timeline:
    resource: "@SpoutletBundle/Resources/config/routing/admin_timeline.yml"
    prefix:   /admin/timeline

SpoutletBundle_timeline:
    resource: "@SpoutletBundle/Resources/config/routing/timeline.yml"
    prefix:   /timeline

TagBundle_admin:
    resource: "@SpoutletBundle/Resources/config/routing/admin_tags.yml"
    prefix: /admin/tags

TagBundle_frontend:
    resource: "@SpoutletBundle/Resources/config/routing/tags.yml"
    prefix: /tags

SpoutletBundle_export_queries:
    resource: "@SpoutletBundle/Resources/config/routing/admin_export_queries.yml"
    prefix: /admin
