default_index:
    pattern:  /
    defaults: { _controller: SpoutletBundle:Default:index }

privacy:
    pattern: /legal/privacy
    defaults: { _controller: SpoutletBundle:Default:privacy }

terms_conditions:
    pattern: /legal/terms
    defaults: { _controller: SpoutletBundle:Default:terms_conditions }

about:
    pattern: /about
    defaults: { _controller: SpoutletBundle:Default:about }

contact:
    pattern: /contact
    defaults: { _controller: SpoutletBundle:Default:contact }

microsoft:
    pattern: /microsoft
    defaults: { _controller: SpoutletBundle:Default:microsoft }

content_reporting:
    pattern:  /report
    defaults: { _controller: "SpoutletBundle:ContentReporting:reportContent" }
    requirements:
        _format: json
        _method: POST

forums:
    pattern: /forums
    defaults: { _controller: SpoutletBundle:Default:forums }

arp:
    pattern: /arp
    defaults: { _controller: SpoutletBundle:Default:arp }

_spoutlet_admin:
    resource: routing/admin.yml

_spoutlet_events:
    resource: routing/events.yml
    prefix:   /events

_spoutlet_account:
    resource: routing/account.yml
    prefix:   /account

military:
    pattern: /groups/military
    defaults: { _controller: SpoutletBundle:Default:military }

wallpapers:
    pattern: /wallpapers
    defaults: { _controller: SpoutletBundle:Default:wallpapers }

SpoutletBundle_age:
    resource: "@SpoutletBundle/Resources/config/routing/age.yml"
    prefix:   /age

SpoutletBundle_admin_content_reports:
    resource: "@SpoutletBundle/Resources/config/routing/admin_content_reports.yml"
    prefix:   /admin/contentReports

SpoutletBundle_group:
    resource: "@SpoutletBundle/Resources/config/routing/group.yml"
    prefix:   /groups

SpoutletBundle_gallery:
    resource: "@SpoutletBundle/Resources/config/routing/gallery.yml"
    prefix:   /galleries

SpoutletBundle_media:
    resource: "@SpoutletBundle/Resources/config/routing/media.yml"
    prefix:   /media

SpoutletBundle_contest:
    resource: "@SpoutletBundle/Resources/config/routing/contest.yml"
    prefix:   /contest

SpoutletBundle_contests:
    resource: "@SpoutletBundle/Resources/config/routing/contests.yml"
    prefix:   /contests

SpoutletBundle_admin_group:
    resource: "@SpoutletBundle/Resources/config/routing/admin_group.yml"
    prefix:   /admin/groups

SpoutletBundle_admin_wallpapers:
    resource: "@SpoutletBundle/Resources/config/routing/admin_wallpaper.yml"
    prefix:   /admin/wallpapers

SpoutletBundle_comments:
    resource: "@SpoutletBundle/Resources/config/routing/comments.yml"
    prefix: /comments

SpoutletBundle_admin_gallery:
    resource: "@SpoutletBundle/Resources/config/routing/admin_gallery.yml"
    prefix:   /admin/galleries

SpoutletBundle_admin_contest:
    resource: "@SpoutletBundle/Resources/config/routing/admin_contest.yml"
    prefix:   /admin/contests

SpoutletBundle_admin_featured_media:
    resource: "@SpoutletBundle/Resources/config/routing/admin_featured_media.yml"
    prefix:   /admin/featured-media
