default_index:
    pattern:  /
    defaults: { _controller: SpoutletBundle:Default:index }

support:
    pattern: /pages/support
    defaults: { _controller: SpoutletBundle:Default:support }

privacy:
    pattern: /privacy_policy
    defaults: { _controller: SpoutletBundle:Default:privacy }

terms_conditions:
    pattern: terms_and_conditions
    defaults: { _controller: SpoutletBundle:Default:terms_conditions }

microsoft:
    pattern: /microsoft
    defaults: { _controller: SpoutletBundle:Default:microsoft }

_spoutlet_admin:
    resource: routing/admin.yml

_spoutlet_events:
    resource: routing/events.yml
    prefix:   /events

_spoutlet_account:
    resource: routing/account.yml
    prefix:   /account