default_index:
    pattern:  /
    defaults: { _controller: SpoutletBundle:Default:index }

support:
    pattern: /pages/support
    defaults: { _controller: SpoutletBundle:Default:support }

_spoutlet_admin:
    resource: routing/admin.yml

_spoutlet_events:
    resource: routing/events.yml
    prefix:   /events

_spoutlet_account:
    resource: routing/account.yml
    prefix:   /account