default_index:
    pattern:  /
    defaults: { _controller: SpoutletBundle:Default:index }

privacy:
    pattern: /legal/privacy
    defaults: { _controller: SpoutletBundle:Default:privacy }

terms_conditions:
    pattern: /legal/terms
    defaults: { _controller: SpoutletBundle:Default:terms_conditions }

about:
    pattern: /about
    defaults: { _controller: SpoutletBundle:Default:about }

contact:
    pattern: /contact
    defaults: { _controller: SpoutletBundle:Default:contact }

microsoft:
    pattern: /microsoft
    defaults: { _controller: SpoutletBundle:Default:microsoft }

_spoutlet_admin:
    resource: routing/admin.yml

_spoutlet_events:
    resource: routing/events.yml
    prefix:   /events

_spoutlet_account:
    resource: routing/account.yml
    prefix:   /account

military:
    pattern: /groups/military
    defaults: { _controller: SpoutletBundle:Default:military }
