parameters:
#    spoutlet.example.class: Platformd\SpoutletBundle\Example

services:
#    spoutlet.example:
#        class: %spoutlet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
