parameters:
    # this is repeated in the multitenancy manager - should not be
    platformd_sites:
        en: Demo
        ja: Japan
        zh: China

services:
    platformd.s3: 
        class: AmazonS3
        arguments:
            - %s3.access_key%
            - %s3.secret_key%
    
    platformd.path_resolver:
        class:  'Platformd\SpoutletBundle\PathResolver'
        public: false
        abstract: true
        calls:
            - [ setBucket, [ "%s3_bucket_name%" ]]

    platformd.avatar.s3.adapter:
        class: Gaufrette\Adapter\AmazonS3
        arguments:
            - @platformd.s3
            - "%s3_bucket_name%"

    platformd.event.s3.adapter:
        class: Gaufrette\Adapter\AmazonS3
        arguments:
            - @platformd.s3
            - "%s3_bucket_name%"

    twig.extension_text:
        class: Twig_Extensions_Extension_Text
        arguments: []
        tags:
            - { name: twig.extension }

    platformd.multitenancy_extension:
        class: Platformd\SpoutletBundle\Twig\MultitenancyExtension
        tags:
            - { name: twig.extension }

    platformd.breadcrumbs_renderer:
        class: Platformd\SpoutletBundle\Menu\BreadcrumbsRenderer
        tags:
            - { name: knp_menu.renderer, alias: breadcrumbs }

    platformd.menu_builder:
        class: Platformd\SpoutletBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@router"

    platformd.breadcrumbs_menu:
        class: Knp\Menu\MenuItem
        scope: request
        factory_service: "platformd.menu_builder"
        factory_method: createBreadcrumbs
        arguments:
            - "@request"
        tags:
            - { name: knp_menu.menu, alias: breadcrumbs }