parameters:
#    spoutlet.example.class: Platformd\SpoutletBundle\Example

services:
    platformd.s3: 
        class: AmazonS3
        arguments:
            - %s3.access_key%
            - %s3.secret_key%
    
    platformd.path_resolver:
        class:  'Platformd\SpoutletBundle\PathResolver'
        public: false
        abstract: true
        calls:
            - [ setBucket, [ "platformd-testing" ]]
