parameters:
    # this is repeated in the multitenancy manager - should not be
    platformd_sites:
        en: Demo
        ja: Japan
        zh: China

services:
    platformd.s3: 
        class: AmazonS3
        arguments:
            - %s3.access_key%
            - %s3.secret_key%

    # adapters for Gaufrette filesystems
    platformd.avatar.s3.adapter:
        class: Gaufrette\Adapter\AmazonS3
        arguments:
            - @platformd.s3
            - "%s3_bucket_name%"
    platformd.event.s3.adapter:
        class: Gaufrette\Adapter\AmazonS3
        arguments:
            - @platformd.s3
            - "%s3_bucket_name%"

    platformd.path_resolver:
        class:  'Platformd\SpoutletBundle\PathResolver'
        public: false
        abstract: true
        calls:
            - [ setBucket, [ "%s3_bucket_name%" ]]

    twig.extension_text:
        class: Twig_Extensions_Extension_Text
        arguments: []
        tags:
            - { name: twig.extension }

    platformd.spoutlet_extension:
        class: Platformd\SpoutletBundle\Twig\SpoutletExtension
        arguments:
            - "@service_container"
        tags:
            - { name: twig.extension }

    platformd.breadcrumbs_renderer:
        class: Platformd\SpoutletBundle\Menu\BreadcrumbsRenderer
        tags:
            - { name: knp_menu.renderer, alias: breadcrumbs }

    platformd.menu_builder:
        class: Platformd\SpoutletBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@router"

    platformd.breadcrumbs_menu:
        class: Knp\Menu\MenuItem
        scope: request
        factory_service: "platformd.menu_builder"
        factory_method: createBreadcrumbs
        arguments:
            - "@request"
        tags:
            - { name: knp_menu.menu, alias: breadcrumbs }

    # our metric manager service
    platformd.metric_manager:
        class: Platformd\SpoutletBundle\Metric\MetricManager
        arguments:
            - "@doctrine.orm.entity_manager"
            # this should NOT be hardcoded
            - %platformd_sites%

    # the custom slug constraint for AbstractEvent
    platformd.validation.abstract_event_unique_slug_validator:
        class: Platformd\SpoutletBundle\Validator\AbstractEventUniqueSlugValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: abstract_event.unique_slug }