services:
    platformd.s3:
        class: AmazonS3
        arguments:
            - { key: %s3.access_key%, secret: %s3.secret_key% }

    # adapters for Gaufrette filesystems
    platformd.avatar.s3.adapter:
        class: Gaufrette\Adapter\AmazonS3
        arguments:
            - @platformd.s3
            - "%s3_bucket_name%"
    platformd.event.s3.adapter:
        class: Gaufrette\Adapter\AmazonS3
        arguments:
            - @platformd.s3
            - "%s3_bucket_name%"

    platformd.path_resolver:
        class:  'Platformd\SpoutletBundle\PathResolver'
        public: false
        abstract: true
        calls:
            - [ setBucket, [ "%s3_bucket_name%" ]]

    twig.extension_text:
        class: Twig_Extensions_Extension_Text
        arguments: []
        tags:
            - { name: twig.extension }

    platformd.breadcrumbs_renderer:
        class: Platformd\SpoutletBundle\Menu\BreadcrumbsRenderer
        tags:
            - { name: knp_menu.renderer, alias: breadcrumbs }

    platformd.menu_builder:
        class: Platformd\SpoutletBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@router"

    platformd.breadcrumbs_admin_menu:
        class: Knp\Menu\MenuItem
        scope: request
        factory_service: "platformd.menu_builder"
        factory_method: createAdminBreadcrumbs
        arguments:
            - "@request"
        tags:
            - { name: knp_menu.menu, alias: admin_breadcrumbs }

    # our metric manager service
    platformd.metric_manager:
        class: Platformd\SpoutletBundle\Metric\MetricManager
        arguments:
            - "@doctrine.orm.entity_manager"
            # TODO this should NOT be hardcoded
            - %platformd_sites%

    # the custom slug constraint for AbstractEvent
    platformd.validation.abstract_event_unique_slug_validator:
        class: Platformd\SpoutletBundle\Validator\AbstractEventUniqueSlugValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: abstract_event.unique_slug }

    # the linkable manager
    platformd.link.linkable_manager:
        class: Platformd\SpoutletBundle\Link\LinkableManager
        arguments:
            - "@router"

    # our generic twig extension
    platformd.twig.spoutlet_extension:
        class: Platformd\SpoutletBundle\Twig\SpoutletExtension
        arguments:
            - "@service_container"
        public: false
        tags:
            - { name: twig.extension }

    platformd.form.extension.help_form_type_extension:
        class: Platformd\SpoutletBundle\Form\Extension\HelpFormTypeExtension
        tags:
            - { name: form.type_extension, alias: field }

    platformd.model.site_util:
        class: Platformd\SpoutletBundle\Util\SiteUtil
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"

    platformd.model.email_manager:
        class: Platformd\SpoutletBundle\Model\EmailManager
        arguments:
            - "@service_container"
            - "@doctrine.orm.entity_manager"
            - "@aws_ses"

    platformd.model.group_manager:
        class: Platformd\GroupBundle\Model\GroupManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@session"
            - "@knp_media.util.media_util"
            - "@platformd.model.site_util"
            - "@pd.cevo.api.api_manager"
            - "@security.context"
            - "@event_dispatcher"

    # activity manager service
    platformd.model.activity_manager:
        class: Platformd\SpoutletBundle\Model\ActivityManager
        arguments:
            - "@doctrine.orm.entity_manager"

    platformd.doctrine.locales_relationship_listener:
        class: Platformd\SpoutletBundle\Doctrine\LocalesRelationshipListener
        tags:
            - { name: doctrine.event_subscriber }

    platformd.age.age_manager:
        class: Platformd\SpoutletBundle\Age\AgeManager
        arguments:
            - "@security.context"
            - "@session"
        scope: request

    platformd.cache.memcached:
        class: Memcached

    pagerfanta.view.spoutlet:
        class: Platformd\SpoutletBundle\Pagerfanta\View\SpoutletView
        arguments:
            - @pagerfanta.view.default
        public: false
        tags: [{ name: pagerfanta.view, alias: spoutlet }]

    platformd.form.transformer.html_purifier_basic:
        class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
        arguments:
            - "@exercise_html_purifier.editor_basic"

    platformd.form.transformer.html_purifier_admin:
        class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
        arguments:
            - "@exercise_html_purifier.editor_admin"

    platformd.form.type.purified_textarea_field:
        class: Platformd\SpoutletBundle\Form\Type\PurifiedTextareaType
        arguments:
            - "@platformd.form.transformer.html_purifier_basic"
            - "@platformd.form.transformer.html_purifier_admin"
            - "@security.context"
        tags:
            - { name: form.type, alias: purifiedTextarea }

    platformd.doctrine.listener.group:
        class: Platformd\SpoutletBundle\Doctrine\Listener\GroupListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_subscriber }

    platformd.locale.locales_relationship_helper:
        class: Platformd\SpoutletBundle\Locale\LocalesRelationshipHelper
        arguments:
            - "@doctrine.orm.entity_manager"

    platformd.form.type.gmtOffsetTimezone:
        class: Platformd\SpoutletBundle\Form\Type\GmtOffsetTimezoneType
        tags:
            - { name: form.type, alias: gmtTimezone }
