services:
    platformd.spoutlet.theme_tenant_detection:
        class: Platformd\SpoutletBundle\Theme\SiteThemeDetection
        arguments:
            - "@liip_theme.active_theme"
            - "@platformd.model.site_util"
        tags:
            - { name: kernel.event_listener, event: "kernel.request", method: "onKernelRequest" }
