
imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: "@CEVOBundle/Resources/config/services.yml" }
    - { resource: version.php }
    - { resource: "@GiveawayBundle/Resources/config/services.yml" }
    - { resource: "@GroupBundle/Resources/config/services.yml" }
    - { resource: "@KnpMediaBundle/Resources/config/services.yml" }
    - { resource: "@MediaBundle/Resources/config/services.yml" }
    - { resource: "@CommentBundle/Resources/config/services.yml" }
    - { resource: "@EventBundle/Resources/config/services.yml" }
    - { resource: "@GameBundle/Resources/config/services.yml" }
    - { resource: "@HtmlWidgetBundle/Resources/config/services.yml" }
    - { resource: "@VideoBundle/Resources/config/services.yml" }
    - { resource: "@SearchBundle/Resources/config/services.yml" }
    - { resource: "@TagBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %app.version%
        assets_version_format: %%s?v=%%s
    session:
        default_locale: %locale%
        auto_start:     true
        domain:         .%base_host%
        storage_id:     session.storage.pdo
    esi: true

cybernox_amazon_web_services:
    key:                        %s3.access_key%
    secret:                     %s3.secret_key%

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'SpoutletBundle::forms.html.twig'
    globals:
        base_host:    %base_host%
        showVideo:    false
        facebook_app_id: %facebook_app_id%
        google_api_key: %google_api_key%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

            acl:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %acl_database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    sender_address: %sender_email_address%
    encryption: %mailer_encryption%
    port: %mailer_port%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver:       orm
    firewall_name:   main
    user_class:      Platformd\UserBundle\Entity\User
    from_email:
        address:        %sender_email_address%
        sender_name:    %sender_email_name%
    registration:
        form:
            type: platformd_user_registration
            handler: platformd_user.registration.form.handler
        confirmation:
            enabled: true
    profile:
        form:
            type: platformd_user_profile
    service:
        user_manager: platformd_user.manager
        mailer:       platformd_user.mailer

vich_geographical:
    db_driver: orm

parameters:

    services_queue_util_class: Platformd\SpoutletBundle\Util\QueueUtil

    mock_data_directory: %kernel.root_dir%/../mock_data/
    mock_queue_util_full_filename: %mock_data_directory%queue_util_mock_data.txt

    search_dev_mode: false

    services_queue_util_class: Platformd\SpoutletBundle\Util\QueueUtil

    mock_data_directory: %kernel.root_dir%/../mock_data/
    mock_queue_util_full_filename: %mock_data_directory%queue_util_mock_data.txt

    doctrine.orm.validator.unique.class: Knp\Validator\UniqueEntityValidator

    # false = CEVO login, true = local login
    local_auth: true

    # Used by ReCAPTCHA bundle
    kernel.default_locale: en

    # a setting used in the test environment with CEVOAuthenticationListener
    allow_faked_auth:   false

    # This determines whether to silently forward the user to the CEVO site if the current
    # site (japan, china, na, etc) isn't enabled to host the content for the requested page
    # or resource. If set this to false then a NotFoundHttpException will be thrown instead
    # of forwarding the user to the CEVO site
    allow_cevo_forwarding: true

    # this allows config_dev.yml to override where emails that are sent from the system (instead of the "real" recipient)... do not change this in config.yml though
    email_destination_override: false
    email_destination_override_with: chris.magee@gametheworld.com

    # used in security.yml to enforce https for viewing admin pages
    admin_url_scheme: %admin_prod_url_scheme%

    # if set to true, the ipLookupUtil will read the contents of a file named "overrideCountry"
    # in the %ip2location_lookup_directory% directory and return it after an ip address lookup.
    # This allows developers to fake the country that they are logged in from by writing a string
    # to this file that is the 2 character country code of the desired country.
    # If the file does not exist or is empty, default country is "US".
    ip_lookup_override: false
    ip2location_lookup_directory: %kernel.root_dir%/../external_data/ip2location/

    available_locales:
        # we're abusing the locales to make our many "sites"
        # this will change in the future
        - en    # demo.
        - ja    # japan.
        - zh    # china.
        - en_AU # au. (australia + new zealand)
        - en_GB # europe.
        - en_IN # india.
        - es    # latinam. (Latin America)
        - en_SG # singapore. Malaysia / Singapore
        - en_US # us. (USA!)

    # used by the router
    site_host_map:
        # %host_suffix% might be something like "staging"
        en:     demo%host_suffix%.%base_host%
        ja:     japan%host_suffix%.%base_host%
        zh:     china%host_suffix%.%base_host%
        en_AU:  anz%host_suffix%.%base_host%
        en_GB:  eu%host_suffix%.%base_host%
        en_IN:  in%host_suffix%.%base_host%
        es:     latam%host_suffix%.%base_host%
        en_SG:  mysg%host_suffix%.%base_host%
        en_US:  na%host_suffix%.%base_host%

    # this is repeated in the multitenancy manager - should not be
    platformd_sites:
        en: Demo
        ja: Japan
        zh: China
        en_AU: Australia / New Zealand
        en_GB: Europe
        en_IN: India
        es:    Latin America
        en_SG: Singapore
        en_US: North America

    # an array of "sites" where we host their main site
    # used by the SiteProtectionListener to prevent, for example, Latin America users
    # from accessing pages on our site, other than the few that we host of theirs
    allowed_sites: [en, ja, zh]


    # Used for the translation admin
    locale_translations:
        en: English
        ja: Japanese
        zh: Chinese
        es: Spanish

    # important to setup the translation DB loader to load things for these domains
    available_translation_domains: [messages, forms, FOSCommentBundle, FOSUserBundle, messages, validators, galleries]

    email_destination_override: false
    email_destination_override_with: ""

    sender_email_address: "noreply@%base_host%"
    sender_email_name: Alienware Arena
    platformd.news_source:
        alienware: source_alienware
        cevo: CEVO
        it_news_site: Tech News Site
        email: Email
        facebook: Facebook
        twitter: Twitter
        youtube: Youtube
        friends: Friends or Family
        blog: Blog
        search_engine: Search Engine
        live_event: Live Event
        other: Other
    # this is repeated in routing_dev.yml
    cevo_fake_api_url: /cevo/api/stub

    pdo.session_db_options:
        db_table:    session
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time

    platformd.prefectures:
        ja:
            - 北海道
            - 青森県
            - 岩手県
            - 宮城県
            - 秋田県
            - 山形県
            - 福島県
            - 茨城県
            - 栃木県
            - 群馬県
            - 埼玉県
            - 千葉県
            - 東京都
            - 神奈川県
            - 新潟県
            - 富山県
            - 石川県
            - 福井県
            - 山梨県
            - 長野県
            - 岐阜県
            - 静岡県
            - 愛知県
            - 三重県
            - 滋賀県
            - 京都府
            - 大阪府
            - 兵庫県
            - 奈良県
            - 和歌山県
            - 鳥取県
            - 島根県
            - 岡山県
            - 広島県
            - 山口県
            - 徳島県
            - 香川県
            - 愛媛県
            - 高知県
            - 福岡県
            - 佐賀県
            - 長崎県
            - 熊本県
            - 大分県
            - 宮崎県
            - 鹿児島県
            - 沖縄県
        zh:
            - 北京市
            - 天津市
            - 河北省
            - 山西省
            - 內蒙古自治区
            - 辽宁省
            - 吉林省
            - 黑龙江省
            - 上海市
            - 江苏省
            - 浙江省
            - 安徽省
            - 福建省
            - 江西省
            - 山东省
            - 河南省
            - 湖北省
            - 湖南省
            - 广东省
            - 广西壮族自治区
            - 海南省
            - 重庆市
            - 四川省
            - 贵州省
            - 云南省
            - 西藏自治区
            - 陕西省
            - 甘肃省
            - 青海省
            - 宁夏回族自治区
            - 新疆维吾尔自治区
            - 香港特别行政区
            - 澳门特别行政区
            - 台湾省

jms_i18n_routing:
    default_locale: %locale%
    locales: %available_locales%
    strategy: custom
    hosts: %site_host_map%

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Platformd\CommentBundle\Entity\Comment
            thread: Platformd\CommentBundle\Entity\Thread
    service:
        sorting:
            default: date_desc
        blamer:
            comment: fos_comment.blamer.comment.security
        manager:
            # our own custom CommentManager
            comment: platformd.comment.model.comment_manager

ewz_recaptcha:
    public_key: %recaptcha.public_key%
    private_key: %recaptcha.private_key%
    secure: false
    enabled: true

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sluggable: true
            timestampable: true


services:
    pdo_session:
        class: PDO
        arguments:
            dsn:      "mysql:dbname=%database_name%;host=%database_host%"
            user:     %database_user%
            password: %database_password%

    session.storage.pdo:
        class:     Symfony\Component\HttpFoundation\SessionStorage\PdoSessionStorage
        arguments: [@pdo_session, %session.storage.options%, %pdo.session_db_options% ]

knp_gaufrette:
    adapters:
        platformd.avatar:
            service:
                id: platformd.avatar.s3.adapter
        platformd.event:
            service:
                id: platformd.event.s3.adapter
        platformd.homepage_banners:
            service:
                id: platformd.homepage_banner.s3.adapter
        # todo - ideally this would be the only one, and we'd use Media everywhere
        platformd.media:
            service:
                id: platformd.media.s3.adapter
    filesystems:
        platformd.avatar:
            adapter: platformd.avatar
            alias: avatar_filesystem
        platformd.event:
            adapter: platformd.event
            alias: event_filesystem
        platformd.homepage_banners:
            adapter: platformd.homepage_banners
            alias: homepage_banners_filesystem
        platformd.media:
            adapter: platformd.media
            alias: pd_media_filesystem

knp_media_exposer:
    base_url: http://%base_host%

jms_translation:
    configs:
        entity_extract:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: [*TestCase.php, *Test.php]
            excluded_dirs: [cache, data, logs, Features]

liip_imagine:
    data_loader:    s3
    cache: amazon_s3
    filter_sets:
        # on a list of articles, for example
        article_list:
            quality: 100
            filters:
                # usually 200x113 - but we don't care much about the height
                thumbnail: { size: [200, 150], mode: inset }
        article_full:
            quality: 100
            filters:
                # usually 634x400 - but we don't care much about the height
                thumbnail: { size: [634, 500], mode: inset }

        game_list_logo:
            quality: 100
            filters:
                thumbnail: { size: [195, 80], mode: inset }

        game_show_logo:
            quality: 100
            filters:
                thumbnail: { size: [440, 166], mode: inset }

        image_thumb:
            quality: 100
            filters:
                thumbnail: { size: [204, 114], mode: inset }
                relative_resize: { widen: 204 }
                crop: { start: [0, 0], size: [204, 114] }

        image_thumb_small:
            quality: 100
            filters:
                thumbnail: { size: [135, 80], mode: inset }

        lightbox_medium:
            quality: 100
            filters:
                thumbnail: { size: [400, 400], mode: inset }

        nivo_slider:
            quality: 100
            filters:
                relative_resize: { widen: 636, heighten: 295 }
                crop: { start: [0, 0], size: [636, 295] }

        media_photo_thumb:
            quality: 100
            filters:
                relative_resize: { widen: 135, heighten: 80 }
                crop: { start: [0, 0], size: [135, 80] }

        media_photo_thumb_square:
            quality: 100
            filters:
                relative_resize: { widen: 150, heighten: 150 }
                crop: { start: [0, 0], size: [92, 92] }

        gallery_image_square:
            quality: 100
            filters:
                relative_resize: { widen: 400, heighten: 400 }
                crop: { start: [0, 0], size: [300, 300] }

        media_photo_show:
            quality: 100
            filters:
                relative_resize: { widen: 636 }

        media_contest_winner:
            quality: 100
            filters:
                relative_resize: { widen: 300, heighten: 250 }
                crop: { start: [0, 0], size: [300, 250] }

        media_feed_thumbnail:
            quality: 100
            filters:
                relative_resize: { heighten: 300 }
                crop: { start: [0, 0], size: [250, 250] }

knp_time: ~

exercise_html_purifier:
    default:
        Cache.SerializerPath: '%kernel.cache_dir%/htmlpurifier'
    editor_basic:
        HTML.Allowed: a[href], p, strong, u, em, ul, ol, li, div, *[style], br
    editor_admin:
        HTML.Allowed: a[href], p, strong, hr, u, em, ul, ol, li, h1, h2, h3, h4, img[src|width|height], strike, sub, sup, blockquote, table[border|cellpadding|cellspacing], tbody, tr, td[width|colspan], thead, tfoot, th[width], pre, span, div, *[style], *[class], br

liip_theme:
    themes: %liip_enabled_themes%
    active_theme: 'default'
    path_patterns:
        app_resource:
            - %%app_path%%/themes/%%current_theme%%/%%template%%
            - %%app_path%%/views/%%template%%
        bundle_resource_dir:
            - %%dir%%/themes/%%current_theme%%/%%bundle_name%%/views/%%template%%
            - %%dir%%/%%bundle_name%%/%%override_path%%

fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
    alias:  facebook
    app_id: 402844226440419
    secret: dd8882ad44a3c60da1a1dc415a8c4b51
    cookie: true
    permissions: [email, user_birthday, user_location, publish_stream]

fos_twitter:
    file: %kernel.root_dir%/../vendor/twitteroauth/twitteroauth/twitteroauth.php
    consumer_key: nCv7pi6N8ZibCxmW2lAvQ
    consumer_secret: Clw9FSeWw6RP1AOCKpGsPL4z2If6FS2sHNsk0hjYA
    callback_url: http://demo.alienwarearena.local/app_dev.php/twitter/login-check
