imports:
    - { resource: config_dev.yml }

parameters:
    base_host: localhost
    allow_faked_auth:   true

    # This says to use the current host, but prefix the URLs with this
    # this allows us to fake CEVO's api right on our own site
    cevo_base_url: %mink_base_url%/cevo/api/stub

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

mink:
    base_url:   %mink_base_url%

doctrine:
    dbal:
        dbname:   %database_name%_test