imports:
    - { resource: config_dev.yml }

parameters:
    base_host: pd.l

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

mink:
    base_url:   %mink_base_url%