imports:
    - { resource: config_dev.yml }

parameters:
    allow_faked_auth:   true

    # This says to use the current host, but prefix the URLs with this
    # this allows us to fake CEVO's api right on our own site
    cevo_base_url: %mink_base_url%/cevo/api/stub

    # This determines whether to silently forward the user to the CEVO site if the current
    # site (japan, china, na, etc) isn't enabled to host the content for the requested page
    # or resource. If set this to false then a NotFoundHttpException will be thrown instead
    # of forwarding the user to the CEVO site
    allow_cevo_forwarding: true

    # keep this (allow_caching) off as you can get inconsistent results in a dev/test environment.
    allow_caching: false

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
        domain:         ~

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

mink:
    base_url:   %mink_base_url%
    goutte: ~

doctrine:
    dbal:
        connections:
            default:
                dbname:   %database_name%_test
            acl:
                dbname:   %acl_database_name%_test
