imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: "@CEVOBundle/Resources/config/services.yml" }
    - { resource: version.php }
    - { resource: "@GiveawayBundle/Resources/config/services.yml" }
    - { resource: "@GroupBundle/Resources/config/services.yml" }
    - { resource: "@KnpMediaBundle/Resources/config/services.yml" }
    - { resource: "@MediaBundle/Resources/config/services.yml" }
    - { resource: "@EventBundle/Resources/config/services.yml" }
    - { resource: "@GameBundle/Resources/config/services.yml" }
    - { resource: "@HtmlWidgetBundle/Resources/config/services.yml" }
    - { resource: "@VideoBundle/Resources/config/services.yml" }
    - { resource: "@SearchBundle/Resources/config/services.yml" }
    - { resource: "@TagBundle/Resources/config/services.yml" }
    - { resource: "@SweepstakesBundle/Resources/config/services.yml" }
    - { resource: "@IdeaBundle/Resources/config/services.yml" }
   # - { resource: "@UserBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %app.version%
        assets_version_format: %%s?v=%%s
    session:
        default_locale: %locale%
        auto_start:     true
        domain:         .%base_host%
        storage_id:     session.storage.pdo
    esi: true

cybernox_amazon_web_services:
    key:                        %s3.access_key%
    secret:                     %s3.secret_key%

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'SpoutletBundle::forms.html.twig'
    globals:
        base_host:    %base_host%
        showVideo:    false
        facebook_app_id: %facebook_app_id%
        google_api_key: %google_api_key%
        feedback_ids: %feedback_ids%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

            acl:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %acl_database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    sender_address: %sender_email_address%
    encryption: %mailer_encryption%
    port: %mailer_port%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver:       orm
    firewall_name:   main
    user_class:      Platformd\UserBundle\Entity\User
    from_email:
        address:        %sender_email_address%
        sender_name:    %sender_email_name%
    resetting:
        form:
            handler: platformd_user.resetting.form.handler
            type: platformd_user_resetting
    registration:
        form:
            type: platformd_user_registration
            handler: platformd_user.registration.form.handler
        confirmation:
            enabled: true
    profile:
        form:
            type: platformd_user_profile
    service:
        user_manager: platformd_user.manager
        mailer:       platformd_user.mailer

vich_geographical:
    db_driver: orm

parameters:

    feedback_ids:
        accounts_groups: %accounts_groups% # my groups
        accounts_events: %accounts_events% # my events
        default_index: %default_index% # front page
        about: %about%
        contact: %contact%
        groups: %groups% # all groups
        global_events_index: %global_events_index% # all events
        profile: %profile%
        accounts_settings: %accounts_settings%
        entry_set_view: %entry_set_view%
        profile_edit: %profile_edit%
        group_event_contact: %group_event_contact%
        group_event_attendees: %group_event_attendees%
        group_show: %group_show% # show group
        group_event_view: %group_event_view% # show event
        group_new: %group_new%
        group_edit: %group_edit%
        entry_set_new: %entry_set_new%
        idea_admin_event: %idea_admin_event% # new event
        idea_admin: %idea_admin% # event admin
        idea_admin_event: %idea_admin_event% # edit event
        idea_admin_images: %idea_admin_images%
        idea_admin_member_approvals: %idea_admin_member_approvals
        idea_admin_criteria_all: %idea_admin_criteria_all%
        idea_admin_criteria: %idea_admin_criteria% # new criteria
        idea_admin_criteria_get: %idea_admin_criteria_get% # edit criteria
        idea_summary: %idea_summary% # round summery
        idea_create_form: %idea_create_form%
        idea_show: %idea_show%
        idea_edit_form: %idea_edit_form% # add/edit idea
        idea_upload_form: %idea_upload_form% # idea image upload
        idea_add_link_form: %idea_add_link_form%
        fos_user_security_login: %fos_user_security_login% # login
        fos_user_resetting_request: %fos_user_resetting_request% # forgot password

    services_queue_util_class: Platformd\SpoutletBundle\Util\QueueUtil

    mock_data_directory: %kernel.root_dir%/../mock_data/
    mock_queue_util_full_filename: %mock_data_directory%queue_util_mock_data.txt

    search_dev_mode: false

    services_queue_util_class: Platformd\SpoutletBundle\Util\QueueUtil

    mock_data_directory: %kernel.root_dir%/../mock_data/
    mock_queue_util_full_filename: %mock_data_directory%queue_util_mock_data.txt

    doctrine.orm.validator.unique.class: Knp\Validator\UniqueEntityValidator

    # false = CEVO login, true = local login
    local_auth: true

    # Used by ReCAPTCHA bundle
    kernel.default_locale: en

    # a setting used in the test environment with CEVOAuthenticationListener
    allow_faked_auth:   false

    # This determines whether to silently forward the user to the CEVO site if the current
    # site (japan, china, na, etc) isn't enabled to host the content for the requested page
    # or resource. If set this to false then a NotFoundHttpException will be thrown instead
    # of forwarding the user to the CEVO site
    allow_cevo_forwarding: true

    # this allows config_dev.yml to override where emails that are sent from the system (instead of the "real" recipient)... do not change this in config.yml though
    email_destination_override: false
    email_destination_override_with: osman@platformd.com

    # if set to true, the ipLookupUtil will read the contents of a file named "overrideCountry"
    # in the %ip2location_lookup_directory% directory and return it after an ip address lookup.
    # This allows developers to fake the country that they are logged in from by writing a string
    # to this file that is the 2 character country code of the desired country.
    # If the file does not exist or is empty, default country is "US".
    ip_lookup_override: false
    ip2location_lookup_directory: %kernel.root_dir%/../external_data/ip2location/
    object_storage: %objectStorage%
   
    queue_service: %queue.service%   
    rabbitmq_host: %rabbitmq.host%
    rabbitmq_port: %rabbitmq.port%
    rabbitmq_username:  %rabbitmq.username%
    rabbitmq_password:  %rabbitmq.password%
    hpcloud_accesskey:  %hpcloudAccesskey%
    hpcloud_secreatkey: %hpcloudSecreatkey%
    hpcloud_tenantid:   %hpcloudTenantid%
    hpcloud_url:        %hpcloudUrl%
    hpcloud_messaging_url: %hpcloudMessagingUrl%
    hpcloud_container: %hpcloudContainer%
    #email_service (1) AWS_SES (2) SendGrid
    email_service: %emailService%
    sendgrid_username: %sendgridUsername%
    sendgrid_password: %sendgridPassword%
    maxmind_lookup_directory: %kernel.root_dir%/../external_data/maxmind/


    available_locales:
        # we're abusing the locales to make our many "sites"
        # this will change in the future
        - en_campsite       # www.
        - en_dev            # no prefix
        - en_staging        # staging.
        - en_sjsu           # sjsu.
        - en_bigdatacamp    # bigdatacamp.
        - en_dataminingcamp # dataminingcamp.
        - en_hackomaha      # hackomaha.
        - en_platformd      # platformd.
        - en_toyota         # quantified-car.
        - en_cloudcampbd    # cloudcampbd.

    # used by the router
    site_host_map:
        # %host_suffix% might be something like "staging"
        en_campsite:        www%host_suffix%.%base_host%
        en_dev:             %base_host%
        en_staging:         %host_suffix%.%base_host%
        en_sjsu:            sjsu%host_suffix%.%base_host%
        en_bigdatacamp:     bigdatacamp%host_suffix%.%base_host%
        en_dataminingcamp:  dataminingcamp%host_suffix%.%base_host%
        en_hackomaha:       hackomaha%host_suffix%.%base_host%
        en_platformd:       platformd%host_suffix%.%base_host%
        en_toyota:          quantified-car%host_suffix%.%base_host%
        en_cloudcampbd:     cloudcampbd%host_suffix%.%base_host%

    # this is repeated in the multitenancy manager - should not be
    platformd_sites:
        en_campsite:        Campsite
        en_dev:             Dev
        en_staging:         Staging
        en_sjsu:            SanJoseStateUniversity
        en_bigdatacamp:     BigDataCamp
        en_dataminingcamp:  DataMiningCamp
        en_hackomaha:       HackOmaha
        en_platformd:       PlatformD
        en_toyota:          Toyota
        en_cloudcampbd:     CloudCampBD

    # an array of "sites" where we host their main site
    # used by the SiteProtectionListener to prevent, for example, Latin America users
    # from accessing pages on our site, other than the few that we host of theirs
    allowed_sites: [en, ja, zh]


    # Used for the translation admin
    locale_translations:
        en: English
        ja: Japanese
        zh: Chinese
        es: Spanish

    # important to setup the translation DB loader to load things for these domains
    available_translation_domains: [messages, forms, FOSUserBundle, messages, validators]

    email_destination_override: false
    email_destination_override_with: ""

    sender_email_address: "noreply@cloudcamp.org"
    sender_email_name: Campsite
    platformd.news_source:
        alienware: source_alienware
        cevo: CEVO
        it_news_site: News Site
        email: Email
        facebook: Facebook
        twitter: Twitter
        youtube: Youtube
        friends: Friends or Family
        blog: Blog
        search_engine: Search Engine
        live_event: Live Event
        other: Other
    # this is repeated in routing_dev.yml
    cevo_fake_api_url: /cevo/api/stub

    pdo.session_db_options:
        db_table:    session
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time

    platformd.prefectures:
        ja:
            - 北海道
            - 青森県
            - 岩手県
            - 宮城県
            - 秋田県
            - 山形県
            - 福島県
            - 茨城県
            - 栃木県
            - 群馬県
            - 埼玉県
            - 千葉県
            - 東京都
            - 神奈川県
            - 新潟県
            - 富山県
            - 石川県
            - 福井県
            - 山梨県
            - 長野県
            - 岐阜県
            - 静岡県
            - 愛知県
            - 三重県
            - 滋賀県
            - 京都府
            - 大阪府
            - 兵庫県
            - 奈良県
            - 和歌山県
            - 鳥取県
            - 島根県
            - 岡山県
            - 広島県
            - 山口県
            - 徳島県
            - 香川県
            - 愛媛県
            - 高知県
            - 福岡県
            - 佐賀県
            - 長崎県
            - 熊本県
            - 大分県
            - 宮崎県
            - 鹿児島県
            - 沖縄県
        zh:
            - 北京市
            - 天津市
            - 河北省
            - 山西省
            - 內蒙古自治区
            - 辽宁省
            - 吉林省
            - 黑龙江省
            - 上海市
            - 江苏省
            - 浙江省
            - 安徽省
            - 福建省
            - 江西省
            - 山东省
            - 河南省
            - 湖北省
            - 湖南省
            - 广东省
            - 广西壮族自治区
            - 海南省
            - 重庆市
            - 四川省
            - 贵州省
            - 云南省
            - 西藏自治区
            - 陕西省
            - 甘肃省
            - 青海省
            - 宁夏回族自治区
            - 新疆维吾尔自治区
            - 香港特别行政区
            - 澳门特别行政区
            - 台湾省

jms_i18n_routing:
    default_locale: en_campsite
    locales: %available_locales%
    strategy: custom
    hosts: %site_host_map%

ewz_recaptcha:
    public_key: %recaptcha.public_key%
    private_key: %recaptcha.private_key%
    secure: true
    enabled: true

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sluggable: true
            timestampable: true


services:
    pdo_session:
        class: PDO
        arguments:
            dsn:      "mysql:dbname=%database_name%;host=%database_host%"
            user:     %database_user%
            password: %database_password%

    session.storage.pdo:
        class:     Symfony\Component\HttpFoundation\SessionStorage\PdoSessionStorage
        arguments: [@pdo_session, %session.storage.options%, %pdo.session_db_options% ]
    upload_picture_service:
        class: Platformd\SpoutletBundle\Consumer\UploadPictureConsumer
         
knp_gaufrette:
    adapters:
        platformd.avatar:
            service:
                id: platformd.avatar.s3.adapter
        platformd.gallary:
            service:
                id: platformd.gallary.s3.adapter
        platformd.event:
            service:
                id: platformd.event.s3.adapter
        platformd.homepage_banners:
            service:
                id: platformd.homepage_banner.s3.adapter
        # todo - ideally this would be the only one, and we'd use Media everywhere
        platformd.media:
            service:
                id: platformd.media.s3.adapter
    filesystems:
        platformd.avatar:
            adapter: platformd.avatar
            alias: avatar_filesystem
        platformd.gallary:
            adapter: platformd.gallary
            alias: gallary_filesystem
        platformd.event:
            adapter: platformd.event
            alias: event_filesystem
        platformd.homepage_banners:
            adapter: platformd.homepage_banners
            alias: homepage_banners_filesystem
        platformd.media:
            adapter: platformd.media
            alias: pd_media_filesystem

knp_media_exposer:
    base_url: http://%base_host%

jms_translation:
    configs:
        entity_extract:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: [*TestCase.php, *Test.php]
            excluded_dirs: [cache, data, logs, Features]

liip_imagine:
    data_loader:    s3
    cache: amazon_s3
    filter_sets:
        # on a list of articles, for example
        article_list:
            quality: 100
            filters:
                # usually 200x113 - but we don't care much about the height
                thumbnail: { size: [200, 150], mode: inset }
        article_full:
            quality: 100
            filters:
                # usually 634x400 - but we don't care much about the height
                thumbnail: { size: [634, 500], mode: inset }

        game_list_logo:
            quality: 100
            filters:
                thumbnail: { size: [195, 80], mode: inset }

        game_show_logo:
            quality: 100
            filters:
                thumbnail: { size: [440, 166], mode: inset }

        image_thumb:
            quality: 100
            filters:
                thumbnail: { size: [204, 114], mode: inset }
                relative_resize: { widen: 204 }
                crop: { start: [0, 0], size: [204, 114] }

        image_thumb_small:
            quality: 100
            filters:
                thumbnail: { size: [135, 80], mode: inset }

        lightbox_medium:
            quality: 100
            filters:
                thumbnail: { size: [400, 400], mode: inset }

        nivo_slider:
            quality: 100
            filters:
                relative_resize: { widen: 636, heighten: 295 }
                crop: { start: [0, 0], size: [636, 295] }

        media_photo_thumb:
            quality: 100
            filters:
                relative_resize: { widen: 135, heighten: 80 }
                crop: { start: [0, 0], size: [135, 80] }

        media_photo_thumb_square:
            quality: 100
            filters:
                relative_resize: { widen: 150, heighten: 150 }
                crop: { start: [0, 0], size: [92, 92] }

        gallery_image_square:
            quality: 100
            filters:
                relative_resize: { widen: 400, heighten: 400 }
                crop: { start: [0, 0], size: [300, 300] }

        media_photo_show:
            quality: 100
            filters:
                relative_resize: { widen: 636 }

        media_contest_winner:
            quality: 100
            filters:
                relative_resize: { widen: 300, heighten: 250 }
                crop: { start: [0, 0], size: [300, 250] }

        media_feed_thumbnail:
            quality: 100
            filters:
                relative_resize: { heighten: 300 }
                crop: { start: [0, 0], size: [250, 250] }

        featured_article_thumb:
            quality: 100
            filters:
                crop: { start: [0, 0], size: [274, 92] }

knp_time: ~

exercise_html_purifier:
    default:
        Cache.SerializerPath: '%kernel.cache_dir%/htmlpurifier'
    editor_basic:
        HTML.Allowed: a[href], p, strong, u, em, ul, ol, li, div, *[style], br
    editor_admin:
        HTML.Allowed: a[href], p, strong, hr, u, em, ul, ol, li, h1, h2, h3, h4, img[src|width|height], strike, sub, sup, blockquote, table[border|cellpadding|cellspacing], tbody, tr, td[width|colspan], thead, tfoot, th[width], pre, span, div, *[style], *[class], br

liip_theme:
    themes: %liip_enabled_themes%
    active_theme: 'default'
    path_patterns:
        app_resource:
            - %%app_path%%/themes/%%current_theme%%/%%template%%
            - %%app_path%%/views/%%template%%
        bundle_resource_dir:
            - %%dir%%/themes/%%current_theme%%/%%bundle_name%%/views/%%template%%
            - %%dir%%/%%bundle_name%%/%%override_path%%
