imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
        domain:         .%base_host%
        storage_id:     session.storage.pdo


# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'SpoutletBundle::forms.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    sender_address: %sender_email_address%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver:       orm
    firewall_name:   main
    user_class:      Platformd\UserBundle\Entity\User
    from_email:
        address:        %sender_email_address%
        sender_name:    Alienware Arena
    registration:
        form:
            type: platformd_user_registration
        confirmation:
            enabled: true
    profile:
        form:
            type: platformd_user_profile
    service:
        user_manager: platformd_user.manager
        mailer:       platformd_user.mailer

parameters:
    sender_email_address: "noreply@%base_host%"
    platformd.news_source:
        alienware: source_alienware
        cevo: CEVO
        it_news_site: Tech News Site
        email: Email
        facebook: Facebook
        twitter: Twitter
        youtube: Youtube
        friends: Friends or Family
        blog: Blog
        other: Other

    pdo.session_db_options:
        db_table:    session
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time

    platformd.prefectures:
        ja:
            - 北海道
            - 青森県
            - 岩手県
            - 宮城県
            - 秋田県
            - 山形県
            - 福島県
            - 茨城県
            - 栃木県
            - 群馬県
            - 埼玉県
            - 千葉県
            - 東京都
            - 神奈川県
            - 新潟県
            - 富山県
            - 石川県
            - 福井県
            - 山梨県
            - 長野県
            - 岐阜県
            - 静岡県
            - 愛知県
            - 三重県
            - 滋賀県
            - 京都府
            - 大阪府
            - 兵庫県
            - 奈良県
            - 和歌山県
            - 鳥取県
            - 島根県
            - 岡山県
            - 広島県
            - 山口県
            - 徳島県
            - 香川県
            - 愛媛県
            - 高知県
            - 福岡県
            - 佐賀県
            - 長崎県
            - 熊本県
            - 大分県
            - 宮崎県
            - 鹿児島県
            - 沖縄県 
        zh:
            - 北京市
            - 天津市
            - 河北省
            - 山西省
            - 內蒙古自治区
            - 辽宁省
            - 吉林省
            - 黑龙江省
            - 上海市
            - 江苏省
            - 浙江省
            - 安徽省
            - 福建省
            - 江西省
            - 山东省
            - 河南省
            - 湖北省
            - 湖南省
            - 广东省
            - 广西壮族自治区
            - 海南省
            - 重庆市
            - 四川省
            - 贵州省
            - 云南省
            - 西藏自治区
            - 陕西省
            - 甘肃省
            - 青海省
            - 宁夏回族自治区
            - 新疆维吾尔自治区
            - 香港特别行政区
            - 澳门特别行政区
            - 台湾省

jms_i18n_routing:
    default_locale: %locale%
    locales: [en, ja, zh]
    strategy: custom
    hosts:
        # %host_suffix% might be something like "staging"
        en: demo%host_suffix%.%base_host%
        ja: japan%host_suffix%.%base_host%
        zh: china%host_suffix%.%base_host%

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Platformd\CommentBundle\Entity\Comment
            thread: Platformd\CommentBundle\Entity\Thread
    service:
        sorting:
            default: date_asc
        blamer:
            comment: fos_comment.blamer.comment.security

ewz_recaptcha:
    public_key: %recaptcha.public_key%
    private_key: %recaptcha.private_key%
    secure: false

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sluggable: true


services:
    pdo_session:
        class: PDO
        arguments:
            dsn:      "mysql:dbname=%database_name%;host=%database_host%"
            user:     %database_user%
            password: %database_password%

    session.storage.pdo:
        class:     Symfony\Component\HttpFoundation\SessionStorage\PdoSessionStorage
        arguments: [@pdo_session, %session.storage.options%, %pdo.session_db_options% ]

knp_gaufrette:
    adapters:
        platformd.avatar:
            service:
                id: platformd.avatar.s3.adapter 
        platformd.event:
            service:
                id: platformd.event.s3.adapter 
    filesystems:
        platformd.avatar:
            adapter: platformd.avatar
            alias: avatar_filesystem
        platformd.event:
            adapter: platformd.event
            alias: event_filesystem

knp_media_exposer:
    base_url: http://%base_host%
