security:
    # import our CEVO security system
    factories:
        - "%kernel.root_dir%/../src/Platformd/CEVOBundle/Resources/config/security_factory.yml"

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # turn security off entirely for the fake cevo site
        cevo_fake_site:
            pattern: ^%cevo_fake_api_url%
            security: false

        main:
            pattern: ^/
            cevo-auth: true
            anonymous:    true
            logout:
                path:     /logout
                target:   default_index
                success_handler: platformd_user.security_logout_handler
            switch_user: ~

    access_control:
        # the "([\w]+\/)?" pattern allows for the optional locale prefix (e.g. /jp/comments/new or just /comments/new)
        - { path: ^/([\w]+\/)?comments/new, role: ROLE_USER }

        - { path: ^/([\w]+\/)?admin/game, role: ROLE_ADMIN_GAME }
        - { path: ^/([\w]+\/)?admin/events, role: ROLE_ORGANIZER }
        - { path: ^/([\w]+\/)?admin/giveaways, role: ROLE_ORGANIZER }
        - { path: ^/([\w]+\/)?admin/news, role: ROLE_ORGANIZER }
        - { path: ^/([\w]+\/)?admin/homepage-banners, role: ROLE_ORGANIZER }
        - { path: ^/([\w]+\/)?admin/sweepstakes, role: ROLE_ORGANIZER }

        - { path: ^/([\w]+\/)?admin/users, role: ROLE_SUPER_ADMIN }
        # admin is the lowest admin role - catch all for admin routes
        - { path: ^/([\w]+\/)?admin, role: ROLE_ADMIN }

    role_hierarchy:
        # generic "admin" role - you don't really get to do anything, but you can see the admin page
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_ORGANIZER:   [ROLE_ADMIN, ROLE_ADMIN_GAME]
        ROLE_SUPER_ADMIN: [ROLE_ORGANIZER, ROLE_STATS_ADMIN, ROLE_USER_ADMIN, ROLE_ADMIN_TRANSLATIONS, ROLE_ALLOWED_TO_SWITCH]
