security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
            anonymous:    true
            logout:
                path:     /logout
                target:   default_index

    access_control:
        # the "([\w]+\/)?" pattern allows for the optional locale prefix (e.g. /jp/comments/new or just /comments/new)
        - { path: ^/([\w]+\/)?comments/new, role: ROLE_USER }
        - { path: ^/([\w]+\/)?admin/events/(approve|unpublish).*, role: ROLE_SUPER_ADMIN }
        - { path: ^/([\w]+\/)?admin/events, role: ROLE_ORGANIZER }
        - { path: ^/([\w]+\/)?admin/giveaways, role: ROLE_ORGANIZER }
        # admin is the lowest admin role - catch all for admin routes
        - { path: ^/([\w]+\/)?admin, role: ROLE_ADMIN }

    role_hierarchy:
        # generic "admin" role - you don't really get to do anything, but you can see the admin page
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_ORGANIZER:   [ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ORGANIZER]
