security:

    encoders:
        "FOS\UserBundle\Model\UserInterface":
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    factories:
            - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # turn security off entirely for the fake cevo site
        cevo_fake_site:
            pattern: ^%cevo_fake_api_url%
            security: false

        main:
            pattern: ^/
            anonymous:    true
            form_login:
                check_path: /login_check
            logout:
                path:     /logout
                target:   default_index
            switch_user: ~

        public:
            pattern:   ^/.*
            fos_facebook:
                app_url: "http://apps.facebook.com/AlienwareArena/"
                server_url: "http://alienwarearena.com/"
                login_path: ^/login
                check_path: security_check
                default_target_path: /
                provider: fos_userbundle
            anonymous: true
            logout:
                handlers: ["fos_facebook.logout_handler"]

    acl:
        connection: acl

    access_control:
        # the "([\w]+\/)?" pattern allows for the optional locale prefix (e.g. /jp/comments/new or just /comments/new)
        - { path: ^/([\w]+\/)?comments/new, role: ROLE_USER }

        # protects games and game pages
        - { path: ^/([\w]+\/)?admin/game, role: ROLE_ADMIN_GAME }
        - { path: ^/([\w]+\/)?admin/deal, role: ROLE_ADMIN_DEAL }
        - { path: ^/([\w]+\/)?admin/events, role: ROLE_ORGANIZER }
        - { path: ^/([\w]+\/)?admin/giveaways, role: ROLE_ORGANIZER }
        - { path: ^/([\w]+\/)?admin/news, role: ROLE_ORGANIZER }
        - { path: ^/([\w]+\/)?admin/homepage-banners, role: ROLE_ORGANIZER }
        - { path: ^/([\w]+\/)?admin/sweepstakes, role: ROLE_ORGANIZER }

        - { path: ^/([\w]+\/)?admin/users, role: ROLE_SUPER_ADMIN }
        # admin is the lowest admin role - catch all for admin routes
        - { path: ^/([\w]+\/)?admin, role: ROLE_ADMIN, requires_channel: %admin_url_scheme% }
        - { path: ^/([\w]+\/)?account/settings, role: IS_AUTHENTICATED_FULLY }

        # facebook protection
        - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook
        - { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }

    role_hierarchy:
        # generic "admin" role - you don't really get to do anything, but you can see the admin page
        ROLE_ADMIN:       [ROLE_USER]
        # the dell contacts role
        ROLE_PARTNER:     [ROLE_ADMIN, ROLE_ADMIN_GAME, ROLE_ADMIN_DEAL]
        ROLE_ORGANIZER:   [ROLE_PARTNER]
        ROLE_JAPAN_ADMIN: [ROLE_ORGANIZER, ROLE_STATS_ADMIN, ROLE_ADMIN_TRANSLATIONS]
        ROLE_SUPER_ADMIN: [ROLE_ORGANIZER, ROLE_STATS_ADMIN, ROLE_USER_ADMIN, ROLE_ADMIN_TRANSLATIONS, ROLE_ALLOWED_TO_SWITCH]
