services:
    platformd.form.type.youtube:
        class: Platformd\VideoBundle\Form\Type\YoutubeType
        arguments:
            - '@platformd.util.site_util'
            - '@platformd.repository.gallery'
            - '@platformd.repository.group'
            - "@security.token_storage"
            - "@request"
            - "@platformd.tags.model.tag_manager"
        scope: request
        tags:
            - { name: form.type }
