services:
    platformd.form.type.youtube:
        class: Platformd\VideoBundle\Form\Type\YoutubeType
        arguments:
            - '@platformd.model.site_util'
            - '@platformd.repository.gallery'
            - '@platformd.repository.group'
            - "@security.context"
            - "@request"
        scope: request
        tags:
            - { name: form.type, alias: youtube }
