_video_user_info:
    pattern: /esi/USER_SPECIFIC/videoUserInfo/{id}
    defaults: { _controller: VideoBundle:Youtube:_videoUserInfo }

VideoBundle_youtube:
    resource: "@VideoBundle/Resources/config/routing/youtube.yml"
    prefix:   /videos

VideoBundle_youtube_admin:
    resource: "@VideoBundle/Resources/config/routing/youtube_admin.yml"
    prefix:   /admin/videos
