<?php

namespace Platformd\GiveawayBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Platformd\UserBundle\Entity\User;
use Platformd\GiveawayBundle\Entity\Giveaway;

/**
 * MachineCodeEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineCodeEntryRepository extends EntityRepository
{
    /**
     * Returns all entries related to the User that do *not* yet have a giveaway key associated with them
     *
     * @param \Platformd\UserBundle\Entity\User $user
     * @return \Platformd\GiveawayBundle\Entity\MachineCodeEntry[]
     */
    public function findAssignedToUserWithoutGiveawayKey(User $user)
    {
        return $this->createQueryBuilder('mce')
            ->andWhere('mce.user = :user')
            ->andWhere('mce.key IS NULL')
            ->setParameter('user', $user)
            ->getQuery()
            ->execute()
        ;
    }

    /**
     * @param \Platformd\GiveawayBundle\Entity\Giveaway $giveaway
     * @return \Platformd\GiveawayBundle\Entity\MachineCodeEntry[]
     */
    public function findPendingForGiveaway(Giveaway $giveaway)
    {
        return $this->createQueryBuilder('mce')
            ->andWhere('mce.giveaway = :giveaway')
            ->andWhere('mce.status = :status')
            ->setParameter('giveaway', $giveaway)
            ->setParameter('status', MachineCodeEntry::STATUS_PENDING)
            ->getQuery()
            ->execute()
        ;
    }
}