use campsite_production;
ALTER TABLE entry_set_registry AUTO_INCREMENT = 1;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('SpoutletBundle:Site', 1);
UPDATE pd_site SET entrySetRegistration_id=1 WHERE id=1;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('SpoutletBundle:Site', 2);
UPDATE pd_site SET entrySetRegistration_id=2 WHERE id=2;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('SpoutletBundle:Site', 3);
UPDATE pd_site SET entrySetRegistration_id=3 WHERE id=3;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('SpoutletBundle:Site', 4);
UPDATE pd_site SET entrySetRegistration_id=4 WHERE id=4;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('SpoutletBundle:Site', 5);
UPDATE pd_site SET entrySetRegistration_id=5 WHERE id=5;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('SpoutletBundle:Site', 6);
UPDATE pd_site SET entrySetRegistration_id=6 WHERE id=6;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('SpoutletBundle:Site', 7);
UPDATE pd_site SET entrySetRegistration_id=7 WHERE id=7;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('SpoutletBundle:Site', 8);
UPDATE pd_site SET entrySetRegistration_id=8 WHERE id=8;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('SpoutletBundle:Site', 9);
UPDATE pd_site SET entrySetRegistration_id=9 WHERE id=9;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('SpoutletBundle:Site', 10);
UPDATE pd_site SET entrySetRegistration_id=10 WHERE id=10;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 1);
UPDATE pd_groups SET entrySetRegistration_id=11 WHERE id=1;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 2);
UPDATE pd_groups SET entrySetRegistration_id=12 WHERE id=2;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 3);
UPDATE pd_groups SET entrySetRegistration_id=13 WHERE id=3;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 5);
UPDATE pd_groups SET entrySetRegistration_id=14 WHERE id=5;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 6);
UPDATE pd_groups SET entrySetRegistration_id=15 WHERE id=6;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 7);
UPDATE pd_groups SET entrySetRegistration_id=16 WHERE id=7;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 8);
UPDATE pd_groups SET entrySetRegistration_id=17 WHERE id=8;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 9);
UPDATE pd_groups SET entrySetRegistration_id=18 WHERE id=9;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 10);
UPDATE pd_groups SET entrySetRegistration_id=19 WHERE id=10;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 11);
UPDATE pd_groups SET entrySetRegistration_id=20 WHERE id=11;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 12);
UPDATE pd_groups SET entrySetRegistration_id=21 WHERE id=12;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 13);
UPDATE pd_groups SET entrySetRegistration_id=22 WHERE id=13;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 14);
UPDATE pd_groups SET entrySetRegistration_id=23 WHERE id=14;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 15);
UPDATE pd_groups SET entrySetRegistration_id=24 WHERE id=15;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('GroupBundle:Group', 16);
UPDATE pd_groups SET entrySetRegistration_id=25 WHERE id=16;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 1);
UPDATE group_event SET entrySetRegistration_id=26 WHERE id=1;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 2);
UPDATE group_event SET entrySetRegistration_id=27 WHERE id=2;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 4);
UPDATE group_event SET entrySetRegistration_id=28 WHERE id=4;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 6);
UPDATE group_event SET entrySetRegistration_id=29 WHERE id=6;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 10);
UPDATE group_event SET entrySetRegistration_id=30 WHERE id=10;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 11);
UPDATE group_event SET entrySetRegistration_id=31 WHERE id=11;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 12);
UPDATE group_event SET entrySetRegistration_id=32 WHERE id=12;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 13);
UPDATE group_event SET entrySetRegistration_id=33 WHERE id=13;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 15);
UPDATE group_event SET entrySetRegistration_id=34 WHERE id=15;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 16);
UPDATE group_event SET entrySetRegistration_id=35 WHERE id=16;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 17);
UPDATE group_event SET entrySetRegistration_id=36 WHERE id=17;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 18);
UPDATE group_event SET entrySetRegistration_id=37 WHERE id=18;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 19);
UPDATE group_event SET entrySetRegistration_id=38 WHERE id=19;
INSERT INTO entry_set_registry (scope, containerId) VALUES ('EventBundle:GroupEvent', 20);
UPDATE group_event SET entrySetRegistration_id=39 WHERE id=20;
INSERT INTO entry_set (entrySetRegistration_id, name, type, isVotingActive, isSubmissionActive, allowedVoters) SELECT g.entrySetRegistration_id, 'Proposed Ideas', g.type, g.isVotingActive, g.isSubmissionActive, g.allowedVoters FROM group_event as g;
ALTER TABLE group_event DROP isVotingActive, DROP isSubmissionActive, DROP allowedVoters, DROP type;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=1;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=3;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=7;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=8;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=9;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=10;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=11;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=12;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=13;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=14;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=15;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=16;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=21;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=23;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=25;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=26;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=27;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=28;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=29;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=30;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=38;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=45;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=46;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=47;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=48;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=49;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=57;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=58;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=59;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=60;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=61;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=62;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=63;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=64;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=65;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=66;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=67;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=68;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=69;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=70;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=71;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=72;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=73;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=74;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=75;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=76;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=77;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=78;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=79;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=80;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=81;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=82;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=83;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=84;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=85;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=86;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=87;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=88;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=89;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=90;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=91;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=92;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=94;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=95;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=96;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=97;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=98;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=99;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=100;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=102;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=103;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=104;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=105;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=106;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=107;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=108;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=109;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=110;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=111;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=112;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=113;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=114;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=115;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=116;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=117;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=118;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=119;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=120;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=121;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=122;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=123;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=124;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=125;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=126;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=127;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=128;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=130;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=131;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=132;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=133;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=134;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=135;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=136;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=137;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=138;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=139;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=140;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=141;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=142;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=143;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=144;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=145;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=146;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=147;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=148;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=149;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=150;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=151;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=152;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=154;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=155;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=156;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=157;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=158;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=159;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=160;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=161;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=162;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=163;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=164;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=165;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=166;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=167;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=168;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=169;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=170;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=171;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=172;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=174;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=175;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=176;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=177;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=178;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=179;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=180;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=181;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=182;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=183;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=184;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=185;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=186;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=187;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=188;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=189;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=190;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=191;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=192;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=193;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=194;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=195;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=196;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=197;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=199;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=200;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=201;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=202;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=204;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=205;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=206;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=207;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=208;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=209;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=210;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=211;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=212;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=213;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=214;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=215;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=217;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=218;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=219;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=220;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=221;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=222;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=223;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=224;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=225;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=226;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=227;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=228;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=229;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=18;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=31;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=32;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=34;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=33;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=93;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=101;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=173;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=153;
UPDATE idea SET entrySet_id=( SELECT list.id FROM (group_event as event join entry_set as list) WHERE event.entrySetRegistration_id = list.entrySetRegistration_id AND event.id = idea.entrySet_id ) WHERE id=216;
