<?php

namespace Platformd\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\QueryBuilder;
use DateTime;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuspendedIpAddressRepository extends EntityRepository
{
    public function isIpAddressSuspended($ipAddress)
    {
        $result = $this->createQueryBuilder('s')
            ->select('COUNT(s.id)')
            ->andWhere('s.ipAddress = :ipAddress')
            ->andWhere('s.suspendedUntil > :now OR s.suspendedUntil IS NULL')
            ->setParameter('ipAddress', $ipAddress)
            ->setParameter('now', new DateTime())
            ->getQuery()
            ->getSingleScalarResult();

        return $result;
    }

    public function getIpAddressSuspensions($ipAddress)
    {
        $result = $this->createQueryBuilder('s')
            ->andWhere('s.ipAddress = :ipAddress')
            ->andWhere('s.suspendedUntil > :now OR s.suspendedUntil IS NULL')
            ->setParameter('ipAddress', $ipAddress)
            ->setParameter('now', new DateTime())
            ->addOrderBy('s.suspendedUntil')
            ->getQuery()
            ->getResult();

        return $result;
    }
}
