parameters:
    # I don't believe these are used
    # I don't believe these are used
    media_bucket_name: knp_media_test
    media_subdirectory: media

services:
    knp_media.media_persistence_listener:
        class: Knp\MediaBundle\Listener\MediaPersistenceListener
        arguments:
            # todo - refactor this to be configurable - is hardcoded for us right now
            - @pd_media_filesystem
            - @service_container
        calls:
            - [ setLogger, ["@logger"]]
        tags:
            - { name: doctrine.event_subscriber }


    knp_media.listener.unique_filename_generation_exception_listener:
        class: Knp\MediaBundle\Listener\UniqueFilenameGenerationExceptionListener
        arguments:
            - "@templating"
            - "%kernel.debug%"
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    knp_media.util.media_util:
        class : Knp\MediaBundle\Util\MediaUtil
        arguments:
            - "@doctrine.orm.entity_manager"