# file for security-related services
services:
  cevo.authentication.provider.cevo:
    class:  Platformd\CEVOBundle\Security\CEVO\CEVOAuthenticationProvider
    arguments:
        - "@fos_user.user_manager"
        - "@pd.cevo.api.api_manager"

  cevo.authentication.listener.cevo:
    class:  Platformd\CEVOBundle\Security\CEVO\CEVOAuthenticationListener
    arguments:
        - "@security.context"
        - "@security.authentication.manager"
        - "%base_host%"
        - "%kernel.debug%"
        - "%allow_faked_auth%"
    calls:
        - [ setLogger, [ @?logger ] ]

  cevo.authentication.entry_point.cevo:
    class:  Platformd\CEVOBundle\Security\CEVO\CEVOAuthenticationEntryPoint
    arguments:
        - "@pd.cevo.cevo_auth_manager"