parameters:
    # can be changed just in development environment in config_dev.yml
    cevo_base_url: http://alienwarearena.com

services:
    pd.cevo.cevo_auth_manager:
        class: Platformd\CEVOBundle\CEVOAuthManager
        arguments:
            - %cevo_base_url%
            - "@service_container"

    pd.cevo.api.api_manager:
        class: Platformd\CEVOBundle\Api\ApiManager
        arguments:
            - "@service_container"
            - "@pd.cevo.cevo_auth_manager"
            - "%kernel.debug%"
        calls:
            - [ setLogger, [ @logger] ]