<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120329084952 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP INDEX UNIQ_D18AE7925F37A13B ON pd_translation_token");
        $this->addSql("CREATE UNIQUE INDEX token_domain_idx ON pd_translation_token (token, domain)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP INDEX token_domain_idx ON pd_translation_token");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_D18AE7925F37A13B ON pd_translation_token (token)");
    }
}
