<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130418193409 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        $this->addSql("ALTER TABLE GiveawayTranslation DROP FOREIGN KEY FK_5FD133F2C2AC5D3");
        $this->addSql("ALTER TABLE GiveawayTranslation ADD CONSTRAINT FK_5FD133F2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES pd_giveaway(id) ON DELETE CASCADE");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        $this->addSql("ALTER TABLE GiveawayTranslation DROP FOREIGN KEY FK_5FD133F2C2AC5D3");
        $this->addSql("ALTER TABLE GiveawayTranslation ADD CONSTRAINT FK_5FD133F2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES event(id) ON DELETE CASCADE");
    }
}
