<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130415122419 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("UPDATE `pd_site_features` SET `has_video`=1,`has_steam_xfire_communities`=1,`has_sweepstakes`=0,`has_forums`=1,`has_arp`=1,`has_news`=1,`has_deals`=1,`has_games`=1,`has_games_nav_drop_down`=1,`has_messages`=1,`has_groups`=1,`has_wallpapers`=1,`has_microsoft`=1,`has_photos`=1,`has_contests`=1,`has_comments`=1,`has_events`=1 WHERE `site_id`=1");
        $this->addSql("UPDATE `pd_site_features` SET `has_video`=1,`has_steam_xfire_communities`=0,`has_sweepstakes`=0,`has_forums`=0,`has_arp`=0,`has_news`=1,`has_deals`=0,`has_games`=0,`has_games_nav_drop_down`=0,`has_messages`=0,`has_groups`=0,`has_wallpapers`=0,`has_microsoft`=0,`has_photos`=0,`has_contests`=0,`has_comments`=1,`has_events`=1 WHERE `site_id`=2");
        $this->addSql("UPDATE `pd_site_features` SET `has_video`=0,`has_steam_xfire_communities`=0,`has_sweepstakes`=0,`has_forums`=0,`has_arp`=0,`has_news`=0,`has_deals`=0,`has_games`=0,`has_games_nav_drop_down`=0,`has_messages`=0,`has_groups`=0,`has_wallpapers`=0,`has_microsoft`=0,`has_photos`=0,`has_contests`=0,`has_comments`=0,`has_events`=0 WHERE `site_id`=3");
        $this->addSql("UPDATE `pd_site_features` SET `has_video`=1,`has_steam_xfire_communities`=1,`has_sweepstakes`=0,`has_forums`=1,`has_arp`=1,`has_news`=0,`has_deals`=1,`has_games`=1,`has_games_nav_drop_down`=1,`has_messages`=1,`has_groups`=1,`has_wallpapers`=1,`has_microsoft`=1,`has_photos`=1,`has_contests`=1,`has_comments`=1,`has_events`=1 WHERE `site_id`=4");
        $this->addSql("UPDATE `pd_site_features` SET `has_video`=1,`has_steam_xfire_communities`=1,`has_sweepstakes`=0,`has_forums`=1,`has_arp`=1,`has_news`=0,`has_deals`=1,`has_games`=1,`has_games_nav_drop_down`=1,`has_messages`=1,`has_groups`=1,`has_wallpapers`=1,`has_microsoft`=1,`has_photos`=1,`has_contests`=1,`has_comments`=1,`has_events`=1 WHERE `site_id`=5");
        $this->addSql("UPDATE `pd_site_features` SET `has_video`=1,`has_steam_xfire_communities`=1,`has_sweepstakes`=0,`has_forums`=1,`has_arp`=1,`has_news`=0,`has_deals`=0,`has_games`=1,`has_games_nav_drop_down`=1,`has_messages`=1,`has_groups`=0,`has_wallpapers`=1,`has_microsoft`=1,`has_photos`=1,`has_contests`=0,`has_comments`=1,`has_events`=1 WHERE `site_id`=6");
        $this->addSql("UPDATE `pd_site_features` SET `has_video`=1,`has_steam_xfire_communities`=1,`has_sweepstakes`=0,`has_forums`=1,`has_arp`=1,`has_news`=0,`has_deals`=0,`has_games`=1,`has_games_nav_drop_down`=1,`has_messages`=1,`has_groups`=0,`has_wallpapers`=1,`has_microsoft`=1,`has_photos`=0,`has_contests`=0,`has_comments`=0,`has_events`=1 WHERE `site_id`=7");
        $this->addSql("UPDATE `pd_site_features` SET `has_video`=1,`has_steam_xfire_communities`=1,`has_sweepstakes`=0,`has_forums`=1,`has_arp`=1,`has_news`=0,`has_deals`=0,`has_games`=1,`has_games_nav_drop_down`=1,`has_messages`=1,`has_groups`=0,`has_wallpapers`=1,`has_microsoft`=1,`has_photos`=0,`has_contests`=0,`has_comments`=0,`has_events`=1 WHERE `site_id`=8");
        $this->addSql("UPDATE `pd_site_features` SET `has_video`=1,`has_steam_xfire_communities`=1,`has_sweepstakes`=0,`has_forums`=1,`has_arp`=1,`has_news`=0,`has_deals`=0,`has_games`=1,`has_games_nav_drop_down`=1,`has_messages`=1,`has_groups`=0,`has_wallpapers`=1,`has_microsoft`=1,`has_photos`=0,`has_contests`=0,`has_comments`=0,`has_events`=1 WHERE `site_id`=9");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

    }
}
