<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111108110357 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE giveaway_key ADD user INT DEFAULT NULL, ADD assigned_at DATETIME NOT NULL");
        $this->addSql("ALTER TABLE giveaway_key ADD CONSTRAINT FK_57EA7EF8D93D649 FOREIGN KEY (user) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_57EA7EF8D93D649 ON giveaway_key (user)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE giveaway_key DROP FOREIGN KEY FK_57EA7EF8D93D649");
        $this->addSql("DROP INDEX IDX_57EA7EF8D93D649 ON giveaway_key");
        $this->addSql("ALTER TABLE giveaway_key DROP user, DROP assigned_at");
    }
}
