<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121114172331 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule CHANGE min_age min_age INT DEFAULT NULL, CHANGE max_age max_age INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_vote ADD ip_address VARCHAR(20) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule CHANGE min_age min_age INT NOT NULL, CHANGE max_age max_age INT NOT NULL");
        $this->addSql("ALTER TABLE pd_vote DROP ip_address");
    }
}
