<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120621143722 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_deal_page_gallery_media (deal_id INT NOT NULL, media_id INT NOT NULL, INDEX IDX_6FE2784CF60E2305 (deal_id), INDEX IDX_6FE2784CEA9FDD75 (media_id), PRIMARY KEY(deal_id, media_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_deal_page_gallery_media ADD CONSTRAINT FK_6FE2784CF60E2305 FOREIGN KEY (deal_id) REFERENCES pd_deal(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_deal_page_gallery_media ADD CONSTRAINT FK_6FE2784CEA9FDD75 FOREIGN KEY (media_id) REFERENCES pd_media(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE pd_deal_page_gallery_media");
    }
}
