<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131023114305 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fos_user CHANGE linkedIn linkedIn VARCHAR(255) DEFAULT NULL, CHANGE professionalEmail professionalEmail VARCHAR(255) DEFAULT NULL, CHANGE twitterUsername twitterUsername VARCHAR(255) DEFAULT NULL, CHANGE website website VARCHAR(255) DEFAULT NULL, CHANGE mailingAddress mailingAddress VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fos_user CHANGE linkedIn linkedIn LONGTEXT DEFAULT NULL, CHANGE professionalEmail professionalEmail LONGTEXT DEFAULT NULL, CHANGE twitterUsername twitterUsername LONGTEXT DEFAULT NULL, CHANGE website website LONGTEXT DEFAULT NULL, CHANGE mailingAddress mailingAddress LONGTEXT DEFAULT NULL");
    }
}
