<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140707115924 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE watched_groups (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, group_id INT DEFAULT NULL, createdAt DATETIME NOT NULL, INDEX IDX_77510688A76ED395 (user_id), INDEX IDX_77510688FE54D947 (group_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE watched_groups ADD CONSTRAINT FK_77510688A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id)");
        $this->addSql("ALTER TABLE watched_groups ADD CONSTRAINT FK_77510688FE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE watched_groups");
    }
}
