<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120830190213 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_group_image (id INT AUTO_INCREMENT NOT NULL, group_id INT DEFAULT NULL, image_id INT DEFAULT NULL, author_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted TINYINT(1) NOT NULL, INDEX IDX_45E721E3FE54D947 (group_id), INDEX IDX_45E721E33DA5256D (image_id), INDEX IDX_45E721E3F675F31B (author_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE groupimage_contentreport (groupimage_id INT NOT NULL, contentreport_id INT NOT NULL, INDEX IDX_6EAD52A7CFED901C (groupimage_id), INDEX IDX_6EAD52A737A50B4F (contentreport_id), PRIMARY KEY(groupimage_id, contentreport_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_group_image ADD CONSTRAINT FK_45E721E3FE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE pd_group_image ADD CONSTRAINT FK_45E721E33DA5256D FOREIGN KEY (image_id) REFERENCES pd_media(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE pd_group_image ADD CONSTRAINT FK_45E721E3F675F31B FOREIGN KEY (author_id) REFERENCES fos_user(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE groupimage_contentreport ADD CONSTRAINT FK_6EAD52A7CFED901C FOREIGN KEY (groupimage_id) REFERENCES pd_group_image(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE groupimage_contentreport ADD CONSTRAINT FK_6EAD52A737A50B4F FOREIGN KEY (contentreport_id) REFERENCES pd_content_report(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE groupimage_contentreport DROP FOREIGN KEY FK_6EAD52A7CFED901C");
        $this->addSql("DROP TABLE pd_group_image");
        $this->addSql("DROP TABLE groupimage_contentreport");
    }
}
