<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130724130602 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE UserAvatar");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE UserAvatar (id INT AUTO_INCREMENT NOT NULL, media_id INT DEFAULT NULL, user_id INT DEFAULT NULL, isApproved TINYINT(1) NOT NULL, isSelected TINYINT(1) NOT NULL, INDEX IDX_367C630DA76ED395 (user_id), INDEX IDX_367C630DEA9FDD75 (media_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE UserAvatar ADD CONSTRAINT FK_367C630DEA9FDD75 FOREIGN KEY (media_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE UserAvatar ADD CONSTRAINT FK_367C630DA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id)");
    }
}
