<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130510033415 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_videos_youtube_restriction_countries (youtubevideo_id INT NOT NULL, country_id INT NOT NULL, INDEX IDX_E5F5EA2AFD53B1D7 (youtubevideo_id), INDEX IDX_E5F5EA2AF92F3E70 (country_id), PRIMARY KEY(youtubevideo_id, country_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_videos_youtube_restriction_countries ADD CONSTRAINT FK_E5F5EA2AFD53B1D7 FOREIGN KEY (youtubevideo_id) REFERENCES pd_videos_youtube(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_videos_youtube_restriction_countries ADD CONSTRAINT FK_E5F5EA2AF92F3E70 FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_videos_youtube ADD restriction_type TINYINT(1) DEFAULT NULL, ADD restrictions_checked DATETIME DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE pd_videos_youtube_restriction_countries");
        $this->addSql("ALTER TABLE pd_videos_youtube DROP restriction_type, DROP restrictions_checked");
    }
}
