<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130418182402 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE event DROP backgroundImagePath, DROP backgroundLink");
        $this->addSql("ALTER TABLE pd_giveaway ADD backgroundImagePath VARCHAR(255) DEFAULT NULL, ADD backgroundLink VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE event ADD backgroundImagePath VARCHAR(255) DEFAULT NULL, ADD backgroundLink VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_giveaway DROP backgroundImagePath, DROP backgroundLink");
    }
}
