<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130402135539 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE html_widget (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, notes VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE html_widget_site (htmlwidget_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_517B0C4F31B25BB7 (htmlwidget_id), INDEX IDX_517B0C4FF6BD1646 (site_id), PRIMARY KEY(htmlwidget_id, site_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE html_widget_site ADD CONSTRAINT FK_517B0C4F31B25BB7 FOREIGN KEY (htmlwidget_id) REFERENCES html_widget(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE html_widget_site ADD CONSTRAINT FK_517B0C4FF6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE html_widget_site DROP FOREIGN KEY FK_517B0C4F31B25BB7");
        $this->addSql("DROP TABLE html_widget");
        $this->addSql("DROP TABLE html_widget_site");
    }
}
