<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130816154201 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_sweepstakes_entry (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, sweepstakes_id INT DEFAULT NULL, ip_address VARCHAR(40) NOT NULL, phone_number VARCHAR(50) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_5E4CD12CA76ED395 (user_id), INDEX IDX_5E4CD12CF89702A0 (sweepstakes_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_sweepstakes_question (id INT AUTO_INCREMENT NOT NULL, sweepstakes_id INT DEFAULT NULL, content VARCHAR(255) NOT NULL, INDEX IDX_BC9E8303F89702A0 (sweepstakes_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_sweepstakes (id INT AUTO_INCREMENT NOT NULL, group_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, published TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, timezone VARCHAR(50) NOT NULL, external_url VARCHAR(255) DEFAULT NULL, starts_at DATETIME NOT NULL, ends_at DATETIME NOT NULL, hidden TINYINT(1) NOT NULL, content LONGTEXT DEFAULT NULL, official_rules LONGTEXT DEFAULT NULL, test_only TINYINT(1) DEFAULT NULL, meta_description VARCHAR(150) DEFAULT NULL, backgroundImage_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_3DC99D98745FB76C (backgroundImage_id), INDEX IDX_3DC99D98FE54D947 (group_id), UNIQUE INDEX slug_unique (slug), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_sweepstakes_site (sweepstakes_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_6EACC926F89702A0 (sweepstakes_id), INDEX IDX_6EACC926F6BD1646 (site_id), PRIMARY KEY(sweepstakes_id, site_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_sweepstakes_answer (id INT AUTO_INCREMENT NOT NULL, question_id INT DEFAULT NULL, content VARCHAR(255) NOT NULL, INDEX IDX_B8753AB61E27F6BF (question_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_sweepstakes_entry ADD CONSTRAINT FK_5E4CD12CA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_sweepstakes_entry ADD CONSTRAINT FK_5E4CD12CF89702A0 FOREIGN KEY (sweepstakes_id) REFERENCES pd_sweepstakes(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_sweepstakes_question ADD CONSTRAINT FK_BC9E8303F89702A0 FOREIGN KEY (sweepstakes_id) REFERENCES pd_sweepstakes(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE pd_sweepstakes ADD CONSTRAINT FK_3DC99D98745FB76C FOREIGN KEY (backgroundImage_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE pd_sweepstakes ADD CONSTRAINT FK_3DC99D98FE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE pd_sweepstakes_site ADD CONSTRAINT FK_6EACC926F89702A0 FOREIGN KEY (sweepstakes_id) REFERENCES pd_sweepstakes(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_sweepstakes_site ADD CONSTRAINT FK_6EACC926F6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_sweepstakes_answer ADD CONSTRAINT FK_B8753AB61E27F6BF FOREIGN KEY (question_id) REFERENCES pd_sweepstakes_question(id) ON DELETE SET NULL");
        $this->addSql("DROP TABLE sweepstakes_entry");
        $this->addSql("ALTER TABLE event CHANGE allowedCountries allowedCountries LONGTEXT NOT NULL COMMENT '(DC2Type:array)'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_sweepstakes_answer DROP FOREIGN KEY FK_B8753AB61E27F6BF");
        $this->addSql("ALTER TABLE pd_sweepstakes_entry DROP FOREIGN KEY FK_5E4CD12CF89702A0");
        $this->addSql("ALTER TABLE pd_sweepstakes_question DROP FOREIGN KEY FK_BC9E8303F89702A0");
        $this->addSql("ALTER TABLE pd_sweepstakes_site DROP FOREIGN KEY FK_6EACC926F89702A0");
        $this->addSql("CREATE TABLE sweepstakes_entry (id INT AUTO_INCREMENT NOT NULL, sweepstakes_id INT DEFAULT NULL, user_id INT DEFAULT NULL, ipAddress VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_B701FFEAA76ED395 (user_id), INDEX IDX_B701FFEAF89702A0 (sweepstakes_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE sweepstakes_entry ADD CONSTRAINT FK_B701FFEAF89702A0 FOREIGN KEY (sweepstakes_id) REFERENCES event(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE sweepstakes_entry ADD CONSTRAINT FK_B701FFEAA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE pd_sweepstakes_entry");
        $this->addSql("DROP TABLE pd_sweepstakes_question");
        $this->addSql("DROP TABLE pd_sweepstakes");
        $this->addSql("DROP TABLE pd_sweepstakes_site");
        $this->addSql("DROP TABLE pd_sweepstakes_answer");
        $this->addSql("ALTER TABLE event CHANGE allowedCountries allowedCountries LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)'");
    }
}
