<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130225124852 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE pd_site_features (id INT AUTO_INCREMENT NOT NULL, site_id INT DEFAULT NULL, has_video TINYINT(1) NOT NULL, has_steam_xfire_communities TINYINT(1) NOT NULL, has_sweepstakes TINYINT(1) NOT NULL, has_forums TINYINT(1) NOT NULL, has_arp TINYINT(1) NOT NULL, has_news TINYINT(1) NOT NULL, has_deals TINYINT(1) NOT NULL, has_games TINYINT(1) NOT NULL, has_games_nav_drop_down TINYINT(1) NOT NULL, has_messages TINYINT(1) NOT NULL, has_groups TINYINT(1) NOT NULL, has_wallpapers TINYINT(1) NOT NULL, has_microsoft TINYINT(1) NOT NULL, has_photos TINYINT(1) NOT NULL, has_contests TINYINT(1) NOT NULL, has_comments TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_36F982ECF6BD1646 (site_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_site_features ADD CONSTRAINT FK_36F982ECF6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE SET NULL");

        $this->addSql("INSERT INTO `pd_site_features` (`id`,`site_id`,`has_video`,`has_steam_xfire_communities`,`has_sweepstakes`,`has_forums`,`has_arp`,`has_news`,`has_deals`,`has_games`,`has_games_nav_drop_down`,`has_messages`,`has_groups`,`has_wallpapers`,`has_microsoft`,`has_photos`,`has_contests`,`has_comments`) VALUES (1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1);");
        $this->addSql("INSERT INTO `pd_site_features` (`id`,`site_id`,`has_video`,`has_steam_xfire_communities`,`has_sweepstakes`,`has_forums`,`has_arp`,`has_news`,`has_deals`,`has_games`,`has_games_nav_drop_down`,`has_messages`,`has_groups`,`has_wallpapers`,`has_microsoft`,`has_photos`,`has_contests`,`has_comments`) VALUES (2,2,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1);");
        $this->addSql("INSERT INTO `pd_site_features` (`id`,`site_id`,`has_video`,`has_steam_xfire_communities`,`has_sweepstakes`,`has_forums`,`has_arp`,`has_news`,`has_deals`,`has_games`,`has_games_nav_drop_down`,`has_messages`,`has_groups`,`has_wallpapers`,`has_microsoft`,`has_photos`,`has_contests`,`has_comments`) VALUES (3,3,1,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0);");
        $this->addSql("INSERT INTO `pd_site_features` (`id`,`site_id`,`has_video`,`has_steam_xfire_communities`,`has_sweepstakes`,`has_forums`,`has_arp`,`has_news`,`has_deals`,`has_games`,`has_games_nav_drop_down`,`has_messages`,`has_groups`,`has_wallpapers`,`has_microsoft`,`has_photos`,`has_contests`,`has_comments`) VALUES (4,4,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1);");
        $this->addSql("INSERT INTO `pd_site_features` (`id`,`site_id`,`has_video`,`has_steam_xfire_communities`,`has_sweepstakes`,`has_forums`,`has_arp`,`has_news`,`has_deals`,`has_games`,`has_games_nav_drop_down`,`has_messages`,`has_groups`,`has_wallpapers`,`has_microsoft`,`has_photos`,`has_contests`,`has_comments`) VALUES (5,5,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1);");
        $this->addSql("INSERT INTO `pd_site_features` (`id`,`site_id`,`has_video`,`has_steam_xfire_communities`,`has_sweepstakes`,`has_forums`,`has_arp`,`has_news`,`has_deals`,`has_games`,`has_games_nav_drop_down`,`has_messages`,`has_groups`,`has_wallpapers`,`has_microsoft`,`has_photos`,`has_contests`,`has_comments`) VALUES (6,6,1,1,0,1,1,0,0,1,1,1,0,1,1,1,1,1);");
        $this->addSql("INSERT INTO `pd_site_features` (`id`,`site_id`,`has_video`,`has_steam_xfire_communities`,`has_sweepstakes`,`has_forums`,`has_arp`,`has_news`,`has_deals`,`has_games`,`has_games_nav_drop_down`,`has_messages`,`has_groups`,`has_wallpapers`,`has_microsoft`,`has_photos`,`has_contests`,`has_comments`) VALUES (7,7,1,1,0,1,1,0,0,1,1,1,0,1,1,0,0,0);");
        $this->addSql("INSERT INTO `pd_site_features` (`id`,`site_id`,`has_video`,`has_steam_xfire_communities`,`has_sweepstakes`,`has_forums`,`has_arp`,`has_news`,`has_deals`,`has_games`,`has_games_nav_drop_down`,`has_messages`,`has_groups`,`has_wallpapers`,`has_microsoft`,`has_photos`,`has_contests`,`has_comments`) VALUES (8,8,1,1,0,1,1,0,0,1,1,1,0,1,1,0,0,0);");
        $this->addSql("INSERT INTO `pd_site_features` (`id`,`site_id`,`has_video`,`has_steam_xfire_communities`,`has_sweepstakes`,`has_forums`,`has_arp`,`has_news`,`has_deals`,`has_games`,`has_games_nav_drop_down`,`has_messages`,`has_groups`,`has_wallpapers`,`has_microsoft`,`has_photos`,`has_contests`,`has_comments`) VALUES (9,9,1,1,0,1,1,0,0,1,1,1,0,1,1,0,0,0);");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE pd_site_features");
    }
}
