<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130821182920 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_sweepstakes_answer ADD entry_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_sweepstakes_answer ADD CONSTRAINT FK_B8753AB6BA364942 FOREIGN KEY (entry_id) REFERENCES pd_sweepstakes_entry(id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_B8753AB6BA364942 ON pd_sweepstakes_answer (entry_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_sweepstakes_answer DROP FOREIGN KEY FK_B8753AB6BA364942");
        $this->addSql("DROP INDEX IDX_B8753AB6BA364942 ON pd_sweepstakes_answer");
        $this->addSql("ALTER TABLE pd_sweepstakes_answer DROP entry_id");
    }
}
