<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131107162507 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Vote DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE Vote ADD PRIMARY KEY (idea_id, criteria_id, voter, round)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Vote DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE Vote ADD PRIMARY KEY (idea_id, criteria_id, voter)");
    }
}
