<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130704174112 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_filtered_media DROP FOREIGN KEY FK_5B5FC3CD727ACA70");
        $this->addSql("ALTER TABLE pd_filtered_media ADD CONSTRAINT FK_5B5FC3CD727ACA70 FOREIGN KEY (parent_id) REFERENCES pd_media(id) ON DELETE SET NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_filtered_media DROP FOREIGN KEY FK_5B5FC3CD727ACA70");
        $this->addSql("ALTER TABLE pd_filtered_media ADD CONSTRAINT FK_5B5FC3CD727ACA70 FOREIGN KEY (parent_id) REFERENCES pd_media(id)");
    }
}
