<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120628112053 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_game_page ADD openGraphOverride_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_game_page ADD CONSTRAINT FK_EE9BB146675CEC9 FOREIGN KEY (openGraphOverride_id) REFERENCES pd_opengraphoverride(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_EE9BB146675CEC9 ON pd_game_page (openGraphOverride_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_game_page DROP FOREIGN KEY FK_EE9BB146675CEC9");
        $this->addSql("DROP INDEX UNIQ_EE9BB146675CEC9 ON pd_game_page");
        $this->addSql("ALTER TABLE pd_game_page DROP openGraphOverride_id");
    }
}
