<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120214112959 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE event ADD disallowedCountries LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', ADD minimumAgeRequirement INT DEFAULT NULL, ADD officialRules LONGTEXT DEFAULT NULL, ADD liabilityRelease LONGTEXT DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE event DROP disallowedCountries, DROP minimumAgeRequirement, DROP officialRules, DROP liabilityRelease");
    }
}
