<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120625155058 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE dealpool_country (dealpool_id INT NOT NULL, country_id INT NOT NULL, INDEX IDX_CA2D45F2964062D0 (dealpool_id), INDEX IDX_CA2D45F2F92F3E70 (country_id), PRIMARY KEY(dealpool_id, country_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE dealpool_country ADD CONSTRAINT FK_CA2D45F2964062D0 FOREIGN KEY (dealpool_id) REFERENCES deal_pool(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE dealpool_country ADD CONSTRAINT FK_CA2D45F2F92F3E70 FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE dealpool_country");
    }
}
