<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120621130040 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_deal ADD website_url VARCHAR(255) NOT NULL, ADD thumbnailLarge_id INT DEFAULT NULL, ADD thumbnailComment_id INT DEFAULT NULL, ADD claimCodeButton_id INT DEFAULT NULL, ADD visitWebsiteButton_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A980409983DD91A FOREIGN KEY (thumbnailLarge_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A980409DE358715 FOREIGN KEY (thumbnailComment_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A9804095C70034E FOREIGN KEY (claimCodeButton_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A980409BC21E280 FOREIGN KEY (visitWebsiteButton_id) REFERENCES pd_media(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_9A980409983DD91A ON pd_deal (thumbnailLarge_id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_9A980409DE358715 ON pd_deal (thumbnailComment_id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_9A9804095C70034E ON pd_deal (claimCodeButton_id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_9A980409BC21E280 ON pd_deal (visitWebsiteButton_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_deal DROP FOREIGN KEY FK_9A980409983DD91A");
        $this->addSql("ALTER TABLE pd_deal DROP FOREIGN KEY FK_9A980409DE358715");
        $this->addSql("ALTER TABLE pd_deal DROP FOREIGN KEY FK_9A9804095C70034E");
        $this->addSql("ALTER TABLE pd_deal DROP FOREIGN KEY FK_9A980409BC21E280");
        $this->addSql("DROP INDEX UNIQ_9A980409983DD91A ON pd_deal");
        $this->addSql("DROP INDEX UNIQ_9A980409DE358715 ON pd_deal");
        $this->addSql("DROP INDEX UNIQ_9A9804095C70034E ON pd_deal");
        $this->addSql("DROP INDEX UNIQ_9A980409BC21E280 ON pd_deal");
        $this->addSql("ALTER TABLE pd_deal DROP website_url, DROP thumbnailLarge_id, DROP thumbnailComment_id, DROP claimCodeButton_id, DROP visitWebsiteButton_id");
    }
}
