<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130725121604 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_avatar DROP FOREIGN KEY FK_302333E8A76ED395");
        $this->addSql("ALTER TABLE pd_avatar ADD CONSTRAINT FK_302333E8A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE SET NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_avatar DROP FOREIGN KEY FK_302333E8A76ED395");
        $this->addSql("ALTER TABLE pd_avatar ADD CONSTRAINT FK_302333E8A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id)");
    }
}
