<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140207182456 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE gallary (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, uuid VARCHAR(255) DEFAULT NULL, approved TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, cropped TINYINT(1) NOT NULL, resized TINYINT(1) NOT NULL, processed TINYINT(1) NOT NULL, reviewed TINYINT(1) NOT NULL, deleted TINYINT(1) NOT NULL, crop_dimensions VARCHAR(40) DEFAULT NULL, initial_format VARCHAR(10) DEFAULT NULL, initial_width INT DEFAULT NULL, initial_height INT DEFAULT NULL, INDEX IDX_4022D0E6A76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE gallary ADD CONSTRAINT FK_4022D0E6A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE fos_user ADD gallary_id INT DEFAULT NULL, ADD faceprintId INT DEFAULT NULL, ADD faceprint_image VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE fos_user ADD CONSTRAINT FK_957A64799F76ED99 FOREIGN KEY (gallary_id) REFERENCES gallary(id) ON DELETE SET NULL");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_957A64799F76ED99 ON fos_user (gallary_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fos_user DROP FOREIGN KEY FK_957A64799F76ED99");
        $this->addSql("DROP TABLE gallary");
        $this->addSql("ALTER TABLE fos_user DROP FOREIGN KEY FK_957A64799F76ED99");
        $this->addSql("DROP INDEX UNIQ_957A64799F76ED99 ON fos_user");
        $this->addSql("ALTER TABLE fos_user DROP gallary_id, DROP faceprintId, DROP faceprint_image");
    }
}
