<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130314182114 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE pd_deal_locale");
        $this->addSql("ALTER TABLE event ADD thumbnail_id INT DEFAULT NULL, ADD featured TINYINT(1) DEFAULT NULL, ADD featured_at DATETIME DEFAULT NULL");
        $this->addSql("ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7FDFF2E92 FOREIGN KEY (thumbnail_id) REFERENCES pd_media(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_3BAE0AA7FDFF2E92 ON event (thumbnail_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_deal_locale (id INT AUTO_INCREMENT NOT NULL, deal_id INT DEFAULT NULL, locale VARCHAR(255) NOT NULL, UNIQUE INDEX deal_locale (deal_id, locale), INDEX IDX_85314BCFF60E2305 (deal_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_deal_locale ADD CONSTRAINT FK_85314BCFF60E2305 FOREIGN KEY (deal_id) REFERENCES pd_deal(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7FDFF2E92");
        $this->addSql("DROP INDEX UNIQ_3BAE0AA7FDFF2E92 ON event");
        $this->addSql("ALTER TABLE event DROP thumbnail_id, DROP featured, DROP featured_at");
    }
}
