<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130626185055 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fos_user ADD facebook_id VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE pd_groups_members DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE pd_groups_members ADD PRIMARY KEY (user_id, group_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fos_user DROP facebook_id");
        $this->addSql("ALTER TABLE pd_groups_members DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE pd_groups_members ADD PRIMARY KEY (group_id, user_id)");
    }
}
