<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130129211242 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE deal_pool_region (dealpool_id INT NOT NULL, region_id INT NOT NULL, INDEX IDX_A6B86BE964062D0 (dealpool_id), INDEX IDX_A6B86BE98260155 (region_id), PRIMARY KEY(dealpool_id, region_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE giveaway_pool_region (giveawaypool_id INT NOT NULL, region_id INT NOT NULL, INDEX IDX_ED4072471D1790D2 (giveawaypool_id), INDEX IDX_ED40724798260155 (region_id), PRIMARY KEY(giveawaypool_id, region_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE deal_pool_region ADD CONSTRAINT FK_A6B86BE964062D0 FOREIGN KEY (dealpool_id) REFERENCES deal_pool(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE deal_pool_region ADD CONSTRAINT FK_A6B86BE98260155 FOREIGN KEY (region_id) REFERENCES region(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE giveaway_pool_region ADD CONSTRAINT FK_ED4072471D1790D2 FOREIGN KEY (giveawaypool_id) REFERENCES giveaway_pool(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE giveaway_pool_region ADD CONSTRAINT FK_ED40724798260155 FOREIGN KEY (region_id) REFERENCES region(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE deal_pool_region");
        $this->addSql("DROP TABLE giveaway_pool_region");
    }
}
