<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130401233315 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE global_event_rsvp_actions (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, user_id INT DEFAULT NULL, rsvp_at DATETIME DEFAULT NULL, updated_at DATETIME NOT NULL, created_at DATETIME NOT NULL, attendance VARCHAR(255) NOT NULL, INDEX IDX_E9D819C71F7E88B (event_id), INDEX IDX_E9D819CA76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE group_event_rsvp_actions (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, user_id INT DEFAULT NULL, rsvp_at DATETIME DEFAULT NULL, updated_at DATETIME NOT NULL, created_at DATETIME NOT NULL, attendance VARCHAR(255) NOT NULL, INDEX IDX_910265C71F7E88B (event_id), INDEX IDX_910265CA76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE global_event_rsvp_actions ADD CONSTRAINT FK_E9D819C71F7E88B FOREIGN KEY (event_id) REFERENCES global_event(id)");
        $this->addSql("ALTER TABLE global_event_rsvp_actions ADD CONSTRAINT FK_E9D819CA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE group_event_rsvp_actions ADD CONSTRAINT FK_910265C71F7E88B FOREIGN KEY (event_id) REFERENCES group_event(id)");
        $this->addSql("ALTER TABLE group_event_rsvp_actions ADD CONSTRAINT FK_910265CA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE SET NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE global_event_rsvp_actions");
        $this->addSql("DROP TABLE group_event_rsvp_actions");
    }
}
