<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140109121201 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE entry_set ADD creator_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE entry_set ADD CONSTRAINT FK_15A85BBA61220EA6 FOREIGN KEY (creator_id) REFERENCES fos_user(id)");
        $this->addSql("CREATE INDEX IDX_15A85BBA61220EA6 ON entry_set (creator_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE entry_set DROP FOREIGN KEY FK_15A85BBA61220EA6");
        $this->addSql("DROP INDEX IDX_15A85BBA61220EA6 ON entry_set");
        $this->addSql("ALTER TABLE entry_set DROP creator_id");
    }
}
