<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130221194943 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_groups_applications ADD event_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_groups_applications ADD CONSTRAINT FK_549CB7A471F7E88B FOREIGN KEY (event_id) REFERENCES group_event(id)");
        $this->addSql("CREATE INDEX IDX_549CB7A471F7E88B ON pd_groups_applications (event_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_groups_applications DROP FOREIGN KEY FK_549CB7A471F7E88B");
        $this->addSql("DROP INDEX IDX_549CB7A471F7E88B ON pd_groups_applications");
        $this->addSql("ALTER TABLE pd_groups_applications DROP event_id");
    }
}
