<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121101165506 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule DROP FOREIGN KEY FK_870AA50F54F1C144");
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule ADD CONSTRAINT FK_870AA50F54F1C144 FOREIGN KEY (ruleset_id) REFERENCES pd_country_age_restriction_ruleset(id) ON DELETE SET NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule DROP FOREIGN KEY FK_870AA50F54F1C144");
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule ADD CONSTRAINT FK_870AA50F54F1C144 FOREIGN KEY (ruleset_id) REFERENCES pd_country_age_restriction_ruleset(id) ON DELETE CASCADE");
    }
}
