<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121023143820 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_gallery_media (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, category VARCHAR(50) NOT NULL, INDEX IDX_BC5900A3DA5256D (image_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_gallery_media_galleries (gallerymedia_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_576400F4A6AD7D20 (gallerymedia_id), INDEX IDX_576400F44E7AF8F (gallery_id), PRIMARY KEY(gallerymedia_id, gallery_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_gallery_media ADD CONSTRAINT FK_BC5900A3DA5256D FOREIGN KEY (image_id) REFERENCES pd_gallery_image(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE pd_gallery_media_galleries ADD CONSTRAINT FK_576400F4A6AD7D20 FOREIGN KEY (gallerymedia_id) REFERENCES pd_gallery_media(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_gallery_media_galleries ADD CONSTRAINT FK_576400F44E7AF8F FOREIGN KEY (gallery_id) REFERENCES pd_gallery(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE pd_gallery_image_galleries");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_gallery_media_galleries DROP FOREIGN KEY FK_576400F4A6AD7D20");
        $this->addSql("CREATE TABLE pd_gallery_image_galleries (galleryimage_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_AA86682E71978538 (galleryimage_id), INDEX IDX_AA86682E4E7AF8F (gallery_id), PRIMARY KEY(galleryimage_id, gallery_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_gallery_image_galleries ADD CONSTRAINT FK_AA86682E4E7AF8F FOREIGN KEY (gallery_id) REFERENCES pd_gallery(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_gallery_image_galleries ADD CONSTRAINT FK_AA86682E71978538 FOREIGN KEY (galleryimage_id) REFERENCES pd_gallery_image(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE pd_gallery_media");
        $this->addSql("DROP TABLE pd_gallery_media_galleries");
    }
}
