<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120803172843 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_wallpaper (id INT AUTO_INCREMENT NOT NULL, thumbnail_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, resolutionPack_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_C4160F66FDFF2E92 (thumbnail_id), UNIQUE INDEX UNIQ_C4160F66B1CD4711 (resolutionPack_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_wallpaper ADD CONSTRAINT FK_C4160F66FDFF2E92 FOREIGN KEY (thumbnail_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE pd_wallpaper ADD CONSTRAINT FK_C4160F66B1CD4711 FOREIGN KEY (resolutionPack_id) REFERENCES pd_media(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE pd_wallpaper");
    }
}
