<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120813233317 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_group_news (id INT AUTO_INCREMENT NOT NULL, group_id INT DEFAULT NULL, author_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, article LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted TINYINT(1) NOT NULL, INDEX IDX_A291EEC5FE54D947 (group_id), INDEX IDX_A291EEC5F675F31B (author_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_group_news ADD CONSTRAINT FK_A291EEC5FE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_group_news ADD CONSTRAINT FK_A291EEC5F675F31B FOREIGN KEY (author_id) REFERENCES fos_user(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE pd_group_news");
    }
}
