<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130604231723 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE giveaway_key ADD country_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE giveaway_key ADD CONSTRAINT FK_57EA7EFF92F3E70 FOREIGN KEY (country_id) REFERENCES country(id)");
        $this->addSql("CREATE INDEX IDX_57EA7EFF92F3E70 ON giveaway_key (country_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE giveaway_key DROP FOREIGN KEY FK_57EA7EFF92F3E70");
        $this->addSql("DROP INDEX IDX_57EA7EFF92F3E70 ON giveaway_key");
        $this->addSql("ALTER TABLE giveaway_key DROP country_id");
    }
}
