<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120725175617 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_opengraphoverride DROP FOREIGN KEY FK_A024DC45FDFF2E92");
        $this->addSql("ALTER TABLE pd_opengraphoverride ADD CONSTRAINT FK_A024DC45FDFF2E92 FOREIGN KEY (thumbnail_id) REFERENCES pd_media(id) ON DELETE SET NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_opengraphoverride DROP FOREIGN KEY FK_A024DC45FDFF2E92");
        $this->addSql("ALTER TABLE pd_opengraphoverride ADD CONSTRAINT FK_A024DC45FDFF2E92 FOREIGN KEY (thumbnail_id) REFERENCES pd_media(id)");
    }
}
