<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120727145648 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_group_locale (id INT AUTO_INCREMENT NOT NULL, group_id INT DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_83D7E31AFE54D947 (group_id), UNIQUE INDEX group_locale (group_id, locale), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_group_locale ADD CONSTRAINT FK_83D7E31AFE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_groups ADD created_at DATETIME NOT NULL, ADD updated_at DATETIME NOT NULL, ADD allLocales TINYINT(1) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE pd_group_locale");
        $this->addSql("ALTER TABLE pd_groups DROP created_at, DROP updated_at, DROP allLocales");
    }
}
