<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140526211212 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE group_recommendation (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, group_id INT DEFAULT NULL, createdAt DATETIME NOT NULL, type VARCHAR(255) NOT NULL, referredBy_id INT DEFAULT NULL, INDEX IDX_DBBFEDA0A76ED395 (user_id), INDEX IDX_DBBFEDA0FE54D947 (group_id), INDEX IDX_DBBFEDA03D4DACB7 (referredBy_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE group_recommendation ADD CONSTRAINT FK_DBBFEDA0A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id)");
        $this->addSql("ALTER TABLE group_recommendation ADD CONSTRAINT FK_DBBFEDA0FE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id)");
        $this->addSql("ALTER TABLE group_recommendation ADD CONSTRAINT FK_DBBFEDA03D4DACB7 FOREIGN KEY (referredBy_id) REFERENCES fos_user(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE group_recommendation");
    }
}
