<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121030213201 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule DROP FOREIGN KEY FK_870AA50FBF396750");
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule ADD ruleset_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule ADD CONSTRAINT FK_870AA50F54F1C144 FOREIGN KEY (ruleset_id) REFERENCES pd_country_age_restriction_ruleset(id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_870AA50F54F1C144 ON pd_country_age_restriction_rule (ruleset_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule DROP FOREIGN KEY FK_870AA50F54F1C144");
        $this->addSql("DROP INDEX IDX_870AA50F54F1C144 ON pd_country_age_restriction_rule");
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule DROP ruleset_id");
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule ADD CONSTRAINT FK_870AA50FBF396750 FOREIGN KEY (id) REFERENCES pd_country_age_restriction_ruleset(id) ON DELETE CASCADE");
    }
}
