<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121129102856 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_content_report ADD group_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_content_report ADD CONSTRAINT FK_E798A78EFE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_E798A78EFE54D947 ON pd_content_report (group_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_content_report DROP FOREIGN KEY FK_E798A78EFE54D947");
        $this->addSql("DROP INDEX IDX_E798A78EFE54D947 ON pd_content_report");
        $this->addSql("ALTER TABLE pd_content_report DROP group_id");
    }
}
