<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130419130816 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE rsvp_event_attendee DROP FOREIGN KEY FK_B56C8F3F71F7E88B");
        $this->addSql("ALTER TABLE rsvp_event_code DROP FOREIGN KEY FK_B14EE14E71F7E88B");
        $this->addSql("ALTER TABLE rsvp_event_site DROP FOREIGN KEY FK_AF18D832CB45EC1E");
        $this->addSql("ALTER TABLE rsvp_event_attendee DROP FOREIGN KEY FK_B56C8F3F27DAFE17");
        $this->addSql("CREATE TABLE rsvp_code (id INT AUTO_INCREMENT NOT NULL, rsvp_id INT NOT NULL, value VARCHAR(255) NOT NULL, INDEX IDX_720B36C0EF80C8C2 (rsvp_id), UNIQUE INDEX unique_code_per_rsvp (value, rsvp_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rsvp_attendee (id INT AUTO_INCREMENT NOT NULL, rsvp_id INT NOT NULL, code_id INT DEFAULT NULL, firstName VARCHAR(255) NOT NULL, lastName VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phoneNumber VARCHAR(255) NOT NULL, INDEX IDX_BF4F45C8EF80C8C2 (rsvp_id), INDEX IDX_BF4F45C827DAFE17 (code_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rsvp (id INT AUTO_INCREMENT NOT NULL, background_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, isCodeRequired TINYINT(1) NOT NULL, isPublished TINYINT(1) NOT NULL, slug VARCHAR(255) NOT NULL, createdAt DATETIME NOT NULL, INDEX IDX_9FA5CE4EC93D69EA (background_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rsvp_site (rsvp_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_6C5D0FBCEF80C8C2 (rsvp_id), INDEX IDX_6C5D0FBCF6BD1646 (site_id), PRIMARY KEY(rsvp_id, site_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE rsvp_code ADD CONSTRAINT FK_720B36C0EF80C8C2 FOREIGN KEY (rsvp_id) REFERENCES rsvp(id)");
        $this->addSql("ALTER TABLE rsvp_attendee ADD CONSTRAINT FK_BF4F45C8EF80C8C2 FOREIGN KEY (rsvp_id) REFERENCES rsvp(id)");
        $this->addSql("ALTER TABLE rsvp_attendee ADD CONSTRAINT FK_BF4F45C827DAFE17 FOREIGN KEY (code_id) REFERENCES rsvp_code(id)");
        $this->addSql("ALTER TABLE rsvp ADD CONSTRAINT FK_9FA5CE4EC93D69EA FOREIGN KEY (background_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE rsvp_site ADD CONSTRAINT FK_6C5D0FBCEF80C8C2 FOREIGN KEY (rsvp_id) REFERENCES rsvp(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE rsvp_site ADD CONSTRAINT FK_6C5D0FBCF6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");
        $this->addSql("INSERT INTO rsvp (`id`, `background_id`, `name`, `content`, `isCodeRequired`, `isPublished`, `createdAt`) SELECT `id`, `background_id`, `name`, `content`, `isCodeRequired`, `isPublished`, `createdAt` FROM rsvp_event");
        $this->addSql("INSERT INTO rsvp_code (`id`, `rsvp_id`, `value`) SELECT `id`, `event_id`, `value` FROM rsvp_event_code");
        $this->addSql("INSERT INTO rsvp_attendee (`id`, `rsvp_id`, `code_id`, `firstName`, `lastName`, `email`, `phoneNumber`) SELECT `id`, `event_id`, `code_id`, `firstName`, `lastName`, `email`, `phoneNumber` FROM rsvp_event_attendee");
        $this->addSql("INSERT INTO rsvp_site (`rsvp_id`, `site_id`) SELECT `rsvpevent_id`, `site_id` FROM rsvp_event_site");
        $this->addSql("DROP TABLE rsvp_event");
        $this->addSql("DROP TABLE rsvp_event_attendee");
        $this->addSql("DROP TABLE rsvp_event_code");
        $this->addSql("DROP TABLE rsvp_event_site");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE rsvp_attendee DROP FOREIGN KEY FK_BF4F45C827DAFE17");
        $this->addSql("ALTER TABLE rsvp_code DROP FOREIGN KEY FK_720B36C0EF80C8C2");
        $this->addSql("ALTER TABLE rsvp_attendee DROP FOREIGN KEY FK_BF4F45C8EF80C8C2");
        $this->addSql("ALTER TABLE rsvp_site DROP FOREIGN KEY FK_6C5D0FBCEF80C8C2");
        $this->addSql("CREATE TABLE rsvp_event (id INT AUTO_INCREMENT NOT NULL, background_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, isCodeRequired TINYINT(1) NOT NULL, isPublished TINYINT(1) NOT NULL, url VARCHAR(255) NOT NULL, createdAt DATETIME NOT NULL, INDEX IDX_5E1BCD67C93D69EA (background_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rsvp_event_attendee (id INT AUTO_INCREMENT NOT NULL, code_id INT DEFAULT NULL, event_id INT NOT NULL, firstName VARCHAR(255) NOT NULL, lastName VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phoneNumber VARCHAR(255) NOT NULL, INDEX IDX_B56C8F3F71F7E88B (event_id), INDEX IDX_B56C8F3F27DAFE17 (code_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rsvp_event_code (id INT AUTO_INCREMENT NOT NULL, event_id INT NOT NULL, value VARCHAR(255) NOT NULL, UNIQUE INDEX unique_code_per_event (value, event_id), INDEX IDX_B14EE14E71F7E88B (event_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rsvp_event_site (rsvpevent_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_AF18D832CB45EC1E (rsvpevent_id), INDEX IDX_AF18D832F6BD1646 (site_id), PRIMARY KEY(rsvpevent_id, site_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE rsvp_event ADD CONSTRAINT FK_5E1BCD67C93D69EA FOREIGN KEY (background_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE rsvp_event_attendee ADD CONSTRAINT FK_B56C8F3F27DAFE17 FOREIGN KEY (code_id) REFERENCES rsvp_event_code(id)");
        $this->addSql("ALTER TABLE rsvp_event_attendee ADD CONSTRAINT FK_B56C8F3F71F7E88B FOREIGN KEY (event_id) REFERENCES rsvp_event(id)");
        $this->addSql("ALTER TABLE rsvp_event_code ADD CONSTRAINT FK_B14EE14E71F7E88B FOREIGN KEY (event_id) REFERENCES rsvp_event(id)");
        $this->addSql("ALTER TABLE rsvp_event_site ADD CONSTRAINT FK_AF18D832F6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE rsvp_event_site ADD CONSTRAINT FK_AF18D832CB45EC1E FOREIGN KEY (rsvpevent_id) REFERENCES rsvp_event(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE rsvp_code");
        $this->addSql("DROP TABLE rsvp_attendee");
        $this->addSql("DROP TABLE rsvp");
        $this->addSql("DROP TABLE rsvp_site");
    }
}
