<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121105203614 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_event_site (abstractevent_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_E09069AAA7086F66 (abstractevent_id), INDEX IDX_E09069AAF6BD1646 (site_id), PRIMARY KEY(abstractevent_id, site_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_game_page_site (gamepage_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_77A0749A884029AF (gamepage_id), INDEX IDX_77A0749AF6BD1646 (site_id), PRIMARY KEY(gamepage_id, site_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_deal_site (deal_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_CEBA0701F60E2305 (deal_id), INDEX IDX_CEBA0701F6BD1646 (site_id), PRIMARY KEY(deal_id, site_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_news_site (news_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_AD1A9425B5A459A0 (news_id), INDEX IDX_AD1A9425F6BD1646 (site_id), PRIMARY KEY(news_id, site_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_event_site ADD CONSTRAINT FK_E09069AAA7086F66 FOREIGN KEY (abstractevent_id) REFERENCES event(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_event_site ADD CONSTRAINT FK_E09069AAF6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_game_page_site ADD CONSTRAINT FK_77A0749A884029AF FOREIGN KEY (gamepage_id) REFERENCES pd_game_page(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_game_page_site ADD CONSTRAINT FK_77A0749AF6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_deal_site ADD CONSTRAINT FK_CEBA0701F60E2305 FOREIGN KEY (deal_id) REFERENCES pd_deal(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_deal_site ADD CONSTRAINT FK_CEBA0701F6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_news_site ADD CONSTRAINT FK_AD1A9425B5A459A0 FOREIGN KEY (news_id) REFERENCES sp_news(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_news_site ADD CONSTRAINT FK_AD1A9425F6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE event CHANGE locale locale VARCHAR(10) DEFAULT NULL");
        $this->addSql("ALTER TABLE sp_news CHANGE locale locale VARCHAR(2) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE pd_event_site");
        $this->addSql("DROP TABLE pd_game_page_site");
        $this->addSql("DROP TABLE pd_deal_site");
        $this->addSql("DROP TABLE pd_news_site");
        $this->addSql("ALTER TABLE event CHANGE locale locale VARCHAR(10) NOT NULL");
        $this->addSql("ALTER TABLE sp_news CHANGE locale locale VARCHAR(2) NOT NULL");
    }
}
