<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120327104956 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_translation (id INT AUTO_INCREMENT NOT NULL, language VARCHAR(10) NOT NULL, translation LONGTEXT NOT NULL, translationToken_id INT DEFAULT NULL, INDEX IDX_649F4BB46DEC9D60 (translationToken_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_translation_token (id INT AUTO_INCREMENT NOT NULL, domain VARCHAR(200) NOT NULL, token VARCHAR(200) NOT NULL, UNIQUE INDEX UNIQ_D18AE7925F37A13B (token), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_translation ADD CONSTRAINT FK_649F4BB46DEC9D60 FOREIGN KEY (translationToken_id) REFERENCES pd_translation_token(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_translation DROP FOREIGN KEY FK_649F4BB46DEC9D60");
        $this->addSql("DROP TABLE pd_translation");
        $this->addSql("DROP TABLE pd_translation_token");
    }
}
