<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120725163143 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_groups (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(50) NOT NULL, description LONGTEXT NOT NULL, howToJoin LONGTEXT NOT NULL, isPublic TINYINT(1) NOT NULL, backgroundImage_id INT DEFAULT NULL, groupAvatar_id INT DEFAULT NULL, INDEX IDX_D63978B7745FB76C (backgroundImage_id), INDEX IDX_D63978B72339B0AC (groupAvatar_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_groups ADD CONSTRAINT FK_D63978B7745FB76C FOREIGN KEY (backgroundImage_id) REFERENCES pd_media(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE pd_groups ADD CONSTRAINT FK_D63978B72339B0AC FOREIGN KEY (groupAvatar_id) REFERENCES pd_media(id) ON DELETE SET NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE pd_groups");
    }
}
