<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130823123717 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_group_email CHANGE sent_at created_at DATETIME NOT NULL, ADD sent_at DATETIME DEFAULT NULL");
        $this->addSql("ALTER TABLE global_event_email CHANGE sent_at created_at DATETIME NOT NULL, ADD sent_at DATETIME DEFAULT NULL");
        $this->addSql("ALTER TABLE group_event_email CHANGE sent_at created_at DATETIME NOT NULL, ADD sent_at DATETIME DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE global_event_email DROP sent_at, CHANGE sent_at created_at DATETIME NOT NULL");
        $this->addSql("ALTER TABLE group_event_email DROP sent_at, CHANGE sent_at created_at DATETIME NOT NULL");
        $this->addSql("ALTER TABLE pd_group_email DROP sent_at, CHANGE sent_at created_at DATETIME NOT NULL");
    }
}
