<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131104165408 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE JudgeIdeaMap (idea INT NOT NULL, judge INT NOT NULL, INDEX IDX_92EEA103A8BCA45 (idea), INDEX IDX_92EEA10311FBC314 (judge), PRIMARY KEY(idea, judge)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE JudgeIdeaMap ADD CONSTRAINT FK_92EEA103A8BCA45 FOREIGN KEY (idea) REFERENCES idea(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE JudgeIdeaMap ADD CONSTRAINT FK_92EEA10311FBC314 FOREIGN KEY (judge) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE group_event CHANGE allowedVoters allowedVoters VARCHAR(5000) DEFAULT NULL");
        $this->addSql("ALTER TABLE global_event CHANGE allowedVoters allowedVoters VARCHAR(5000) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE JudgeIdeaMap");
        $this->addSql("ALTER TABLE global_event CHANGE allowedVoters allowedVoters VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE group_event CHANGE allowedVoters allowedVoters VARCHAR(255) DEFAULT NULL");
    }
}
