<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140826041018 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE idea_speakers (id INT AUTO_INCREMENT NOT NULL, idea_id INT DEFAULT NULL, speaker_id INT DEFAULT NULL, biography LONGTEXT DEFAULT NULL, role LONGTEXT DEFAULT NULL, INDEX IDX_5BE9DEA75B6FEF7D (idea_id), INDEX IDX_5BE9DEA7D04A0F27 (speaker_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE idea_speakers ADD CONSTRAINT FK_5BE9DEA75B6FEF7D FOREIGN KEY (idea_id) REFERENCES idea(id)");
        $this->addSql("ALTER TABLE idea_speakers ADD CONSTRAINT FK_5BE9DEA7D04A0F27 FOREIGN KEY (speaker_id) REFERENCES fos_user(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE idea_speakers");
    }
}
