<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121023135019 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_gallery (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted TINYINT(1) NOT NULL, deleted_reason VARCHAR(50) DEFAULT NULL, UNIQUE INDEX UNIQ_420D7B685E237E06 (name), INDEX IDX_420D7B687E3C61F9 (owner_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_gallery_site (gallery_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_EB8DDC3A4E7AF8F (gallery_id), INDEX IDX_EB8DDC3AF6BD1646 (site_id), PRIMARY KEY(gallery_id, site_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_gallery_image (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, author_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted TINYINT(1) NOT NULL, deletedReason VARCHAR(255) DEFAULT NULL, INDEX IDX_A4D435593DA5256D (image_id), INDEX IDX_A4D43559F675F31B (author_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_gallery_image_galleries (galleryimage_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_AA86682E71978538 (galleryimage_id), INDEX IDX_AA86682E4E7AF8F (gallery_id), PRIMARY KEY(galleryimage_id, gallery_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_gallery ADD CONSTRAINT FK_420D7B687E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_gallery_site ADD CONSTRAINT FK_EB8DDC3A4E7AF8F FOREIGN KEY (gallery_id) REFERENCES pd_gallery(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_gallery_site ADD CONSTRAINT FK_EB8DDC3AF6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_gallery_image ADD CONSTRAINT FK_A4D435593DA5256D FOREIGN KEY (image_id) REFERENCES pd_media(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE pd_gallery_image ADD CONSTRAINT FK_A4D43559F675F31B FOREIGN KEY (author_id) REFERENCES fos_user(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE pd_gallery_image_galleries ADD CONSTRAINT FK_AA86682E71978538 FOREIGN KEY (galleryimage_id) REFERENCES pd_gallery_image(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_gallery_image_galleries ADD CONSTRAINT FK_AA86682E4E7AF8F FOREIGN KEY (gallery_id) REFERENCES pd_gallery(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_gallery_site DROP FOREIGN KEY FK_EB8DDC3A4E7AF8F");
        $this->addSql("ALTER TABLE pd_gallery_image_galleries DROP FOREIGN KEY FK_AA86682E4E7AF8F");
        $this->addSql("ALTER TABLE pd_gallery_image_galleries DROP FOREIGN KEY FK_AA86682E71978538");
        $this->addSql("DROP TABLE pd_gallery");
        $this->addSql("DROP TABLE pd_gallery_site");
        $this->addSql("DROP TABLE pd_gallery_image");
        $this->addSql("DROP TABLE pd_gallery_image_galleries");
    }
}
