<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120823131126 extends AbstractMigration
{

    # This migration is "special" in that it tries to take the country list that we had (which was imported from
    # Symfony's official country list) into one that is more inline with CEVO.  We needed to do this because the Deal
    # Redemption code now relies on the country code we recieve from CEVO... however we ran into major timeline
    # issues and couldn't complete this correct way of repairing back data... so for now we have just marked all "extra"
    # countries that we have as [DO NOT USE].  We also switched the "United Kingdom" code from "GB" to "UK".

    # In total we have marked 16 countries as [DO NOT USE] and changed 1 country code in place ("GB" => "UK").

    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("UPDATE `country` SET `code`= 'UK' WHERE `code` = 'GB' AND `id` > 0;");
        $this->addSql("UPDATE `country` SET `name`= CONCAT('[DO NOT USE] ', `name`) WHERE `code` IN ('AX','AC','IC','EA','CP','DG','GG','IM','JE','QO','BL','MF','TL','TA', 'EU', 'CS') AND `id` > 0 AND SUBSTRING(`name`, 0, CHAR_LENGTH('[DO NOT USE] ')) != '[DO NOT USE] ';");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

    }
}
