<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120906191818 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_groups_applications ADD site_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_groups_applications ADD CONSTRAINT FK_549CB7A4F6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id)");
        $this->addSql("CREATE INDEX IDX_549CB7A4F6BD1646 ON pd_groups_applications (site_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_groups_applications DROP FOREIGN KEY FK_549CB7A4F6BD1646");
        $this->addSql("DROP INDEX IDX_549CB7A4F6BD1646 ON pd_groups_applications");
        $this->addSql("ALTER TABLE pd_groups_applications DROP site_id");
    }
}
