<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130918112326 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Document (id INT AUTO_INCREMENT NOT NULL, path VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE links (id INT AUTO_INCREMENT NOT NULL, idea_id INT DEFAULT NULL, title VARCHAR(100) NOT NULL, linkDescription VARCHAR(255) NOT NULL, url VARCHAR(2048) NOT NULL, type VARCHAR(100) NOT NULL, INDEX IDX_D182A1185B6FEF7D (idea_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE VoteCriteria (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, displayName VARCHAR(100) NOT NULL, description VARCHAR(1000) NOT NULL, INDEX IDX_A8A29CCA71F7E88B (event_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE comments (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, idea_id INT DEFAULT NULL, text VARCHAR(1000) NOT NULL, timestamp DATETIME NOT NULL, INDEX IDX_5F9E962AA76ED395 (user_id), INDEX IDX_5F9E962A5B6FEF7D (idea_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE tags (tag VARCHAR(100) NOT NULL, PRIMARY KEY(tag)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE idea (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, image_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, createdAt DATETIME NOT NULL, description LONGTEXT NOT NULL, stage VARCHAR(255) DEFAULT NULL, forCourse TINYINT(1) DEFAULT NULL, professors VARCHAR(255) DEFAULT NULL, amount VARCHAR(255) DEFAULT NULL, members LONGTEXT NOT NULL, highestRound INT NOT NULL, isPrivate TINYINT(1) NOT NULL, INDEX IDX_A8BCA4571F7E88B (event_id), INDEX IDX_A8BCA4561220EA6 (creator_id), UNIQUE INDEX UNIQ_A8BCA453DA5256D (image_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE TagIdeaMap (idea INT NOT NULL, tag VARCHAR(100) NOT NULL, INDEX IDX_65C52F5A8BCA45 (idea), INDEX IDX_65C52F5389B783 (tag), PRIMARY KEY(idea, tag)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Vote (idea_id INT NOT NULL, criteria_id INT NOT NULL, voter VARCHAR(100) NOT NULL, value INT NOT NULL, round INT NOT NULL, INDEX IDX_FA222A5A5B6FEF7D (idea_id), INDEX IDX_FA222A5A990BEA15 (criteria_id), PRIMARY KEY(idea_id, criteria_id, voter)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE followMappings (user VARCHAR(100) NOT NULL, idea INT NOT NULL, INDEX IDX_C5E19882A8BCA45 (idea), PRIMARY KEY(user, idea)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE links ADD CONSTRAINT FK_D182A1185B6FEF7D FOREIGN KEY (idea_id) REFERENCES idea(id)");
        $this->addSql("ALTER TABLE VoteCriteria ADD CONSTRAINT FK_A8A29CCA71F7E88B FOREIGN KEY (event_id) REFERENCES group_event(id)");
        $this->addSql("ALTER TABLE comments ADD CONSTRAINT FK_5F9E962AA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id)");
        $this->addSql("ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A5B6FEF7D FOREIGN KEY (idea_id) REFERENCES idea(id)");
        $this->addSql("ALTER TABLE idea ADD CONSTRAINT FK_A8BCA4571F7E88B FOREIGN KEY (event_id) REFERENCES group_event(id)");
        $this->addSql("ALTER TABLE idea ADD CONSTRAINT FK_A8BCA4561220EA6 FOREIGN KEY (creator_id) REFERENCES fos_user(id)");
        $this->addSql("ALTER TABLE idea ADD CONSTRAINT FK_A8BCA453DA5256D FOREIGN KEY (image_id) REFERENCES Document(id)");
        $this->addSql("ALTER TABLE TagIdeaMap ADD CONSTRAINT FK_65C52F5A8BCA45 FOREIGN KEY (idea) REFERENCES idea(id)");
        $this->addSql("ALTER TABLE TagIdeaMap ADD CONSTRAINT FK_65C52F5389B783 FOREIGN KEY (tag) REFERENCES tags(tag)");
        $this->addSql("ALTER TABLE Vote ADD CONSTRAINT FK_FA222A5A5B6FEF7D FOREIGN KEY (idea_id) REFERENCES idea(id)");
        $this->addSql("ALTER TABLE Vote ADD CONSTRAINT FK_FA222A5A990BEA15 FOREIGN KEY (criteria_id) REFERENCES VoteCriteria(id)");
        $this->addSql("ALTER TABLE followMappings ADD CONSTRAINT FK_C5E19882A8BCA45 FOREIGN KEY (idea) REFERENCES idea(id)");
        $this->addSql("ALTER TABLE pd_site_features ADD has_multi_site_groups TINYINT(1) NOT NULL");
        $this->addSql("ALTER TABLE global_event ADD isVotingActive TINYINT(1) NOT NULL, ADD isSubmissionActive TINYINT(1) NOT NULL, ADD allowedVoters VARCHAR(255) NOT NULL, ADD currentRound INT NOT NULL");
        $this->addSql("ALTER TABLE group_event ADD isVotingActive TINYINT(1) NOT NULL, ADD isSubmissionActive TINYINT(1) NOT NULL, ADD allowedVoters VARCHAR(255) NOT NULL, ADD currentRound INT NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE idea DROP FOREIGN KEY FK_A8BCA453DA5256D");
        $this->addSql("ALTER TABLE Vote DROP FOREIGN KEY FK_FA222A5A990BEA15");
        $this->addSql("ALTER TABLE TagIdeaMap DROP FOREIGN KEY FK_65C52F5389B783");
        $this->addSql("ALTER TABLE links DROP FOREIGN KEY FK_D182A1185B6FEF7D");
        $this->addSql("ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962A5B6FEF7D");
        $this->addSql("ALTER TABLE TagIdeaMap DROP FOREIGN KEY FK_65C52F5A8BCA45");
        $this->addSql("ALTER TABLE Vote DROP FOREIGN KEY FK_FA222A5A5B6FEF7D");
        $this->addSql("ALTER TABLE followMappings DROP FOREIGN KEY FK_C5E19882A8BCA45");
        $this->addSql("DROP TABLE Document");
        $this->addSql("DROP TABLE links");
        $this->addSql("DROP TABLE VoteCriteria");
        $this->addSql("DROP TABLE comments");
        $this->addSql("DROP TABLE tags");
        $this->addSql("DROP TABLE idea");
        $this->addSql("DROP TABLE TagIdeaMap");
        $this->addSql("DROP TABLE Vote");
        $this->addSql("DROP TABLE followMappings");
        $this->addSql("ALTER TABLE global_event DROP isVotingActive, DROP isSubmissionActive, DROP allowedVoters, DROP currentRound");
        $this->addSql("ALTER TABLE group_event DROP isVotingActive, DROP isSubmissionActive, DROP allowedVoters, DROP currentRound");
        $this->addSql("ALTER TABLE pd_site_features DROP has_multi_site_groups");
    }
}
