<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120628092756 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE dealpool_country DROP FOREIGN KEY FK_CA2D45F2F92F3E70");
        $this->addSql("ALTER TABLE deal_code DROP FOREIGN KEY FK_C1685537AF91A986");
        $this->addSql("ALTER TABLE dealpool_country DROP FOREIGN KEY FK_CA2D45F2964062D0");
        $this->addSql("ALTER TABLE deal_pool DROP FOREIGN KEY FK_19ECCC29F60E2305");
        $this->addSql("ALTER TABLE pd_deal_locale DROP FOREIGN KEY FK_85314BCFF60E2305");
        $this->addSql("ALTER TABLE pd_deal_page_gallery_media DROP FOREIGN KEY FK_6FE2784CF60E2305");
        $this->addSql("DROP TABLE country");
        $this->addSql("DROP TABLE deal_code");
        $this->addSql("DROP TABLE deal_pool");
        $this->addSql("DROP TABLE dealpool_country");
        $this->addSql("DROP TABLE pd_deal");
        $this->addSql("DROP TABLE pd_deal_locale");
        $this->addSql("DROP TABLE pd_deal_page_gallery_media");
        $this->addSql("ALTER TABLE pd_game_page ADD openGraphOverride_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_game_page ADD CONSTRAINT FK_EE9BB146675CEC9 FOREIGN KEY (openGraphOverride_id) REFERENCES pd_opengraphoverride(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_EE9BB146675CEC9 ON pd_game_page (openGraphOverride_id)");
        $this->addSql("ALTER TABLE sp_homepage_banner DROP published");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE country (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(10) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE deal_code (id INT AUTO_INCREMENT NOT NULL, user INT DEFAULT NULL, pool INT DEFAULT NULL, value VARCHAR(255) NOT NULL, assigned_at DATETIME DEFAULT NULL, assigned_site VARCHAR(10) DEFAULT NULL, ip_address VARCHAR(100) DEFAULT NULL, INDEX IDX_C1685537AF91A986 (pool), INDEX IDX_C16855378D93D649 (user), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE deal_pool (id INT AUTO_INCREMENT NOT NULL, deal_id INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, maxKeysPerIp INT DEFAULT NULL, upperLimit INT DEFAULT NULL, lowerLimit INT DEFAULT NULL, isActive TINYINT(1) DEFAULT NULL, INDEX IDX_19ECCC29F60E2305 (deal_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE dealpool_country (dealpool_id INT NOT NULL, country_id INT NOT NULL, INDEX IDX_CA2D45F2964062D0 (dealpool_id), INDEX IDX_CA2D45F2F92F3E70 (country_id), PRIMARY KEY(dealpool_id, country_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_deal (id INT AUTO_INCREMENT NOT NULL, banner_id INT DEFAULT NULL, game_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, external_url VARCHAR(255) DEFAULT NULL, starts_at DATETIME DEFAULT NULL, ends_at DATETIME DEFAULT NULL, timezone VARCHAR(255) NOT NULL, openGraphOverride_id INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, redemptionInstructions LONGTEXT NOT NULL, website_url VARCHAR(255) DEFAULT NULL, thumbnailLarge_id INT DEFAULT NULL, thumbnailComment_id INT DEFAULT NULL, claimCodeButton_id INT DEFAULT NULL, visitWebsiteButton_id INT DEFAULT NULL, status VARCHAR(50) NOT NULL, legal_verbiage LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, top_color VARCHAR(255) DEFAULT NULL, bottom_color VARCHAR(255) DEFAULT NULL, UNIQUE INDEX slug_unique (slug), UNIQUE INDEX UNIQ_9A980409684EC833 (banner_id), UNIQUE INDEX UNIQ_9A980409675CEC9 (openGraphOverride_id), UNIQUE INDEX UNIQ_9A980409983DD91A (thumbnailLarge_id), UNIQUE INDEX UNIQ_9A980409DE358715 (thumbnailComment_id), UNIQUE INDEX UNIQ_9A9804095C70034E (claimCodeButton_id), UNIQUE INDEX UNIQ_9A980409BC21E280 (visitWebsiteButton_id), INDEX IDX_9A980409E48FD905 (game_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_deal_locale (id INT AUTO_INCREMENT NOT NULL, deal_id INT DEFAULT NULL, locale VARCHAR(255) NOT NULL, UNIQUE INDEX deal_locale (deal_id, locale), INDEX IDX_85314BCFF60E2305 (deal_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_deal_page_gallery_media (deal_id INT NOT NULL, media_id INT NOT NULL, INDEX IDX_6FE2784CF60E2305 (deal_id), INDEX IDX_6FE2784CEA9FDD75 (media_id), PRIMARY KEY(deal_id, media_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE deal_code ADD CONSTRAINT FK_C16855378D93D649 FOREIGN KEY (user) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE deal_code ADD CONSTRAINT FK_C1685537AF91A986 FOREIGN KEY (pool) REFERENCES deal_pool(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE deal_pool ADD CONSTRAINT FK_19ECCC29F60E2305 FOREIGN KEY (deal_id) REFERENCES pd_deal(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE dealpool_country ADD CONSTRAINT FK_CA2D45F2964062D0 FOREIGN KEY (dealpool_id) REFERENCES deal_pool(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE dealpool_country ADD CONSTRAINT FK_CA2D45F2F92F3E70 FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A9804095C70034E FOREIGN KEY (claimCodeButton_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A980409675CEC9 FOREIGN KEY (openGraphOverride_id) REFERENCES pd_opengraphoverride(id)");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A980409684EC833 FOREIGN KEY (banner_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A980409983DD91A FOREIGN KEY (thumbnailLarge_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A980409BC21E280 FOREIGN KEY (visitWebsiteButton_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A980409DE358715 FOREIGN KEY (thumbnailComment_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A980409E48FD905 FOREIGN KEY (game_id) REFERENCES pd_game(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE pd_deal_locale ADD CONSTRAINT FK_85314BCFF60E2305 FOREIGN KEY (deal_id) REFERENCES pd_deal(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_deal_page_gallery_media ADD CONSTRAINT FK_6FE2784CEA9FDD75 FOREIGN KEY (media_id) REFERENCES pd_media(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_deal_page_gallery_media ADD CONSTRAINT FK_6FE2784CF60E2305 FOREIGN KEY (deal_id) REFERENCES pd_deal(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_game_page DROP FOREIGN KEY FK_EE9BB146675CEC9");
        $this->addSql("DROP INDEX UNIQ_EE9BB146675CEC9 ON pd_game_page");
        $this->addSql("ALTER TABLE pd_game_page DROP openGraphOverride_id");
        $this->addSql("ALTER TABLE sp_homepage_banner ADD published TINYINT(1) NOT NULL");
    }
}
