<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120705115444 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE region (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(10) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE country ADD region_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE country ADD CONSTRAINT FK_5373C96698260155 FOREIGN KEY (region_id) REFERENCES country(id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_5373C96698260155 ON country (region_id)");

        $this->addSql("INSERT INTO `region` (`id`, `code`, `name`) VALUES (1, '-', 'Other'), (2, 'na', 'North America'), (3, 'eu', 'Europe')");

        $this->addSql("UPDATE `country` SET `region_id`= 1 WHERE `id` >= 0");
        $this->addSql("UPDATE `country` SET `region_id`= 2 WHERE `id` IN (244)"); # more country 'region-ification' is required
        $this->addSql("UPDATE `country` SET `region_id`= 3 WHERE `id` IN (81, 80, 88, 91, 111, 112, 114, 159, 170, 182, 214, 220, 221, 234, 243)"); # more country 'region-ification' is required

        $this->addSql("ALTER TABLE `country` CHANGE COLUMN `region_id` `region_id` INT(11) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE region");
        $this->addSql("ALTER TABLE country DROP FOREIGN KEY FK_5373C96698260155");
        $this->addSql("DROP INDEX IDX_5373C96698260155 ON country");
        $this->addSql("ALTER TABLE country DROP region_id");
    }
}
