<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130104164558 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE global_activity (id INT AUTO_INCREMENT NOT NULL, subject SMALLINT NOT NULL, verb SMALLINT NOT NULL, object SMALLINT NOT NULL, date DATETIME DEFAULT NULL, data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', subjectId BIGINT DEFAULT NULL, objectId BIGINT DEFAULT NULL, ip_address VARCHAR(20) DEFAULT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE metric_group (id INT AUTO_INCREMENT NOT NULL, group_id INT DEFAULT NULL, newMembers INT DEFAULT NULL, newDiscussions INT DEFAULT NULL, deletedDiscussions INT DEFAULT NULL, date DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_EE9CBB50FE54D947 (group_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE metric_discussion (id INT AUTO_INCREMENT NOT NULL, replies INT DEFAULT NULL, views INT DEFAULT NULL, activeUsers INT DEFAULT NULL, date DATETIME NOT NULL, updated DATETIME NOT NULL, groupDiscussion_id INT DEFAULT NULL, INDEX IDX_72524BC21FBDB074 (groupDiscussion_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE metric_group ADD CONSTRAINT FK_EE9CBB50FE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE metric_discussion ADD CONSTRAINT FK_72524BC21FBDB074 FOREIGN KEY (groupDiscussion_id) REFERENCES pd_group_discussion(id) ON DELETE SET NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE global_activity");
        $this->addSql("DROP TABLE metric_group");
        $this->addSql("DROP TABLE metric_discussion");
    }
}
