<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140203135122 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE registration_field (id INT AUTO_INCREMENT NOT NULL, group_id INT DEFAULT NULL, event_id INT DEFAULT NULL, question VARCHAR(255) NOT NULL, INDEX IDX_D45FE5B0FE54D947 (group_id), INDEX IDX_D45FE5B071F7E88B (event_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE registration_answer (id INT AUTO_INCREMENT NOT NULL, field_id INT DEFAULT NULL, user_id INT DEFAULT NULL, answer VARCHAR(255) NOT NULL, INDEX IDX_74838ACF443707B0 (field_id), INDEX IDX_74838ACFA76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE registration_field ADD CONSTRAINT FK_D45FE5B0FE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id)");
        $this->addSql("ALTER TABLE registration_field ADD CONSTRAINT FK_D45FE5B071F7E88B FOREIGN KEY (event_id) REFERENCES group_event(id)");
        $this->addSql("ALTER TABLE registration_answer ADD CONSTRAINT FK_74838ACF443707B0 FOREIGN KEY (field_id) REFERENCES registration_field(id)");
        $this->addSql("ALTER TABLE registration_answer ADD CONSTRAINT FK_74838ACFA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE registration_answer DROP FOREIGN KEY FK_74838ACF443707B0");
        $this->addSql("DROP TABLE registration_field");
        $this->addSql("DROP TABLE registration_answer");
    }
}
