<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120513122127 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE gamepage_media (gamepage_id INT NOT NULL, media_id INT NOT NULL, INDEX IDX_93973EC5884029AF (gamepage_id), INDEX IDX_93973EC5EA9FDD75 (media_id), PRIMARY KEY(gamepage_id, media_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE gamepage_media ADD CONSTRAINT FK_93973EC5884029AF FOREIGN KEY (gamepage_id) REFERENCES pd_game_page(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE gamepage_media ADD CONSTRAINT FK_93973EC5EA9FDD75 FOREIGN KEY (media_id) REFERENCES pd_media(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE gamepage_media");
    }
}
