<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120622154711 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE deal_pool (id INT AUTO_INCREMENT NOT NULL, deal_id INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, maxKeysPerIp INT DEFAULT NULL, upperLimit INT DEFAULT NULL, lowerLimit INT DEFAULT NULL, isActive TINYINT(1) DEFAULT NULL, INDEX IDX_19ECCC29F60E2305 (deal_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE deal_code (id INT AUTO_INCREMENT NOT NULL, pool INT DEFAULT NULL, user INT DEFAULT NULL, value VARCHAR(255) NOT NULL, assigned_at DATETIME DEFAULT NULL, assigned_site VARCHAR(10) DEFAULT NULL, ip_address VARCHAR(100) DEFAULT NULL, INDEX IDX_C1685537AF91A986 (pool), INDEX IDX_C16855378D93D649 (user), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE deal_pool ADD CONSTRAINT FK_19ECCC29F60E2305 FOREIGN KEY (deal_id) REFERENCES pd_deal(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE deal_code ADD CONSTRAINT FK_C1685537AF91A986 FOREIGN KEY (pool) REFERENCES deal_pool(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE deal_code ADD CONSTRAINT FK_C16855378D93D649 FOREIGN KEY (user) REFERENCES fos_user(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE deal_code DROP FOREIGN KEY FK_C1685537AF91A986");
        $this->addSql("DROP TABLE deal_pool");
        $this->addSql("DROP TABLE deal_code");
    }
}
