<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130222152302 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE global_event_email ADD sender_id INT DEFAULT NULL, site_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE global_event_email ADD CONSTRAINT FK_DC6A98DAF624B39D FOREIGN KEY (sender_id) REFERENCES fos_user(id) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_DC6A98DAF624B39D ON global_event_email (sender_id)");
        $this->addSql("ALTER TABLE global_event_email ADD CONSTRAINT FK_DC6A98DAF6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_DC6A98DAF6BD1646 ON global_event_email (site_id)");
        $this->addSql("ALTER TABLE group_event_email ADD sender_id INT DEFAULT NULL, site_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE group_event_email ADD CONSTRAINT FK_8331D299F624B39D FOREIGN KEY (sender_id) REFERENCES fos_user(id) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_8331D299F624B39D ON group_event_email (sender_id)");
        $this->addSql("ALTER TABLE group_event_email ADD CONSTRAINT FK_8331D299F6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_8331D299F6BD1646 ON group_event_email (site_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE global_event_email DROP FOREIGN KEY FK_DC6A98DAF6BD1646");
        $this->addSql("DROP INDEX IDX_DC6A98DAF6BD1646 ON global_event_email");
        $this->addSql("ALTER TABLE global_event_email DROP site_id");
        $this->addSql("ALTER TABLE group_event_email DROP FOREIGN KEY FK_8331D299F6BD1646");
        $this->addSql("DROP INDEX IDX_8331D299F6BD1646 ON group_event_email");
        $this->addSql("ALTER TABLE group_event_email DROP site_id");
        $this->addSql("ALTER TABLE global_event_email DROP FOREIGN KEY FK_DC6A98DAF624B39D");
        $this->addSql("DROP INDEX IDX_DC6A98DAF624B39D ON global_event_email");
        $this->addSql("ALTER TABLE global_event_email DROP sender_id");
        $this->addSql("ALTER TABLE group_event_email DROP FOREIGN KEY FK_8331D299F624B39D");
        $this->addSql("DROP INDEX IDX_8331D299F624B39D ON group_event_email");
        $this->addSql("ALTER TABLE group_event_email DROP sender_id");
    }
}
