<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140526141953 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE event_recommendation (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, global_event INT DEFAULT NULL, group_event INT DEFAULT NULL, createdAt DATETIME NOT NULL, referredBy_id INT DEFAULT NULL, INDEX IDX_9C7692A1A76ED395 (user_id), INDEX IDX_9C7692A17FAB70E4 (global_event), INDEX IDX_9C7692A16B8221C0 (group_event), INDEX IDX_9C7692A13D4DACB7 (referredBy_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE event_recommendation ADD CONSTRAINT FK_9C7692A1A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id)");
        $this->addSql("ALTER TABLE event_recommendation ADD CONSTRAINT FK_9C7692A17FAB70E4 FOREIGN KEY (global_event) REFERENCES global_event(id)");
        $this->addSql("ALTER TABLE event_recommendation ADD CONSTRAINT FK_9C7692A16B8221C0 FOREIGN KEY (group_event) REFERENCES group_event(id)");
        $this->addSql("ALTER TABLE event_recommendation ADD CONSTRAINT FK_9C7692A13D4DACB7 FOREIGN KEY (referredBy_id) REFERENCES fos_user(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE event_recommendation");
    }
}
