<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130122222006 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE site_takeover (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, starts_at DATETIME NOT NULL, ends_at DATETIME NOT NULL, timezone VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE site_takeover_site (sitetakeover_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_5493511CB7476F10 (sitetakeover_id), INDEX IDX_5493511CF6BD1646 (site_id), PRIMARY KEY(sitetakeover_id, site_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE site_takeover_site ADD CONSTRAINT FK_5493511CB7476F10 FOREIGN KEY (sitetakeover_id) REFERENCES site_takeover(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE site_takeover_site ADD CONSTRAINT FK_5493511CF6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE site_takeover_site DROP FOREIGN KEY FK_5493511CB7476F10");
        $this->addSql("DROP TABLE site_takeover");
        $this->addSql("DROP TABLE site_takeover_site");
    }
}
