<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120405101131 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_translation_token ADD parent_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_translation_token ADD CONSTRAINT FK_D18AE792727ACA70 FOREIGN KEY (parent_id) REFERENCES pd_translation_token(id) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_D18AE792727ACA70 ON pd_translation_token (parent_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_translation_token DROP FOREIGN KEY FK_D18AE792727ACA70");
        $this->addSql("DROP INDEX IDX_D18AE792727ACA70 ON pd_translation_token");
        $this->addSql("ALTER TABLE pd_translation_token DROP parent_id");
    }
}
