<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130318205632 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE commenting_thread ADD site_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE commenting_thread ADD CONSTRAINT FK_716A806DF6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_716A806DF6BD1646 ON commenting_thread (site_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE commenting_thread DROP FOREIGN KEY FK_716A806DF6BD1646");
        $this->addSql("DROP INDEX IDX_716A806DF6BD1646 ON commenting_thread");
        $this->addSql("ALTER TABLE commenting_thread DROP site_id");
    }
}
