<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140730153341 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_site ADD communityGroup_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_site ADD CONSTRAINT FK_1025CCFB57AF333F FOREIGN KEY (communityGroup_id) REFERENCES pd_groups(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_1025CCFB57AF333F ON pd_site (communityGroup_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_site DROP FOREIGN KEY FK_1025CCFB57AF333F");
        $this->addSql("DROP INDEX UNIQ_1025CCFB57AF333F ON pd_site");
        $this->addSql("ALTER TABLE pd_site DROP communityGroup_id");
    }
}
