<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131205224541 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE entry_set DROP FOREIGN KEY FK_15A85BBABC21F742");
        $this->addSql("DROP INDEX IDX_15A85BBABC21F742 ON entry_set");
        $this->addSql("ALTER TABLE entry_set CHANGE container_id entrySetRegistration_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE entry_set ADD CONSTRAINT FK_15A85BBAD0E9DF32 FOREIGN KEY (entrySetRegistration_id) REFERENCES EntrySetRegistry(id)");
        $this->addSql("CREATE INDEX IDX_15A85BBAD0E9DF32 ON entry_set (entrySetRegistration_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE entry_set DROP FOREIGN KEY FK_15A85BBAD0E9DF32");
        $this->addSql("DROP INDEX IDX_15A85BBAD0E9DF32 ON entry_set");
        $this->addSql("ALTER TABLE entry_set CHANGE entrysetregistration_id container_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE entry_set ADD CONSTRAINT FK_15A85BBABC21F742 FOREIGN KEY (container_id) REFERENCES EntrySetRegistry(id)");
        $this->addSql("CREATE INDEX IDX_15A85BBABC21F742 ON entry_set (container_id)");
    }
}
