<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111220165347 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE session");
        $this->addSql("ALTER TABLE sp_news ADD locale VARCHAR(2) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE session (session_id VARCHAR(255) NOT NULL, session_value LONGTEXT NOT NULL, session_time INT NOT NULL, PRIMARY KEY(session_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE sp_news DROP locale");
    }
}
