<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140826055447 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE event_session DROP FOREIGN KEY FK_55137C7BD04A0F27");
        $this->addSql("DROP INDEX IDX_55137C7BD04A0F27 ON event_session");
        $this->addSql("ALTER TABLE event_session DROP speaker_id, DROP speaker_bio");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE event_session ADD speaker_id INT DEFAULT NULL, ADD speaker_bio LONGTEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE event_session ADD CONSTRAINT FK_55137C7BD04A0F27 FOREIGN KEY (speaker_id) REFERENCES fos_user(id)");
        $this->addSql("CREATE INDEX IDX_55137C7BD04A0F27 ON event_session (speaker_id)");
    }
}
