<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120620143946 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_opengraphoverride (id INT AUTO_INCREMENT NOT NULL, thumbnail_id INT DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_A024DC45FDFF2E92 (thumbnail_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_opengraphoverride ADD CONSTRAINT FK_A024DC45FDFF2E92 FOREIGN KEY (thumbnail_id) REFERENCES pd_media(id)");
        $this->addSql("ALTER TABLE pd_deal ADD openGraphOverride_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A980409675CEC9 FOREIGN KEY (openGraphOverride_id) REFERENCES pd_opengraphoverride(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_9A980409675CEC9 ON pd_deal (openGraphOverride_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_deal DROP FOREIGN KEY FK_9A980409675CEC9");
        $this->addSql("DROP TABLE pd_opengraphoverride");
        $this->addSql("ALTER TABLE pd_deal DROP FOREIGN KEY FK_9A980409675CEC9");
        $this->addSql("DROP INDEX UNIQ_9A980409675CEC9 ON pd_deal");
        $this->addSql("ALTER TABLE pd_deal DROP openGraphOverride_id");
    }
}
