<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121217214800 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_machine_code_entry ADD siteAppliedFrom_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_machine_code_entry ADD CONSTRAINT FK_C13FB6367136C4B3 FOREIGN KEY (siteAppliedFrom_id) REFERENCES pd_site(id) ON DELETE CASCADE");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_C13FB6367136C4B3 ON pd_machine_code_entry (siteAppliedFrom_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_machine_code_entry DROP FOREIGN KEY FK_C13FB6367136C4B3");
        $this->addSql("DROP INDEX UNIQ_C13FB6367136C4B3 ON pd_machine_code_entry");
        $this->addSql("ALTER TABLE pd_machine_code_entry DROP siteAppliedFrom_id");
    }
}
