<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121220002125 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_content_report ADD comment_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_content_report ADD CONSTRAINT FK_E798A78EF8697D13 FOREIGN KEY (comment_id) REFERENCES commenting_comment(id) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_E798A78EF8697D13 ON pd_content_report (comment_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_content_report DROP FOREIGN KEY FK_E798A78EF8697D13");
        $this->addSql("DROP INDEX IDX_E798A78EF8697D13 ON pd_content_report");
        $this->addSql("ALTER TABLE pd_content_report DROP comment_id");
    }
}
