<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130821114443 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_sweepstakes_entry ADD country_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_sweepstakes_entry ADD CONSTRAINT FK_5E4CD12CF92F3E70 FOREIGN KEY (country_id) REFERENCES country(id)");
        $this->addSql("CREATE INDEX IDX_5E4CD12CF92F3E70 ON pd_sweepstakes_entry (country_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_sweepstakes_entry DROP FOREIGN KEY FK_5E4CD12CF92F3E70");
        $this->addSql("DROP INDEX IDX_5E4CD12CF92F3E70 ON pd_sweepstakes_entry");
        $this->addSql("ALTER TABLE pd_sweepstakes_entry DROP country_id");
    }
}
