<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111108072753 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE giveaway_key (id INT AUTO_INCREMENT NOT NULL, pool INT DEFAULT NULL, value VARCHAR(255) NOT NULL, INDEX IDX_57EA7EFAF91A986 (pool), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE giveaway_key ADD CONSTRAINT FK_57EA7EFAF91A986 FOREIGN KEY (pool) REFERENCES giveaway_pool(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE giveaway_key");
    }
}
