<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140819112801 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE session_speakers (id INT AUTO_INCREMENT NOT NULL, session_id INT DEFAULT NULL, speaker_id INT DEFAULT NULL, biography LONGTEXT DEFAULT NULL, role LONGTEXT DEFAULT NULL, INDEX IDX_695D593B613FECDF (session_id), INDEX IDX_695D593BD04A0F27 (speaker_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE session_speakers ADD CONSTRAINT FK_695D593B613FECDF FOREIGN KEY (session_id) REFERENCES event_session(id)");
        $this->addSql("ALTER TABLE session_speakers ADD CONSTRAINT FK_695D593BD04A0F27 FOREIGN KEY (speaker_id) REFERENCES fos_user(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE session_speakers");
    }
}
