<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130215152309 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE group_event_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, locale_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, bannerImage_id INT DEFAULT NULL, INDEX IDX_C1A4B9D32C2AC5D3 (translatable_id), INDEX IDX_C1A4B9D3E559DFD1 (locale_id), INDEX IDX_C1A4B9D3E4C68F85 (bannerImage_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE global_event_email (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, subject VARCHAR(255) NOT NULL, message LONGTEXT DEFAULT NULL, sent_at DATETIME NOT NULL, INDEX IDX_DC6A98DA71F7E88B (event_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE global_event_email_recipient (globaleventemail_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_31AE70B0BAEAEB (globaleventemail_id), INDEX IDX_31AE70B0A76ED395 (user_id), PRIMARY KEY(globaleventemail_id, user_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE global_event_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, locale_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, bannerImage_id INT DEFAULT NULL, INDEX IDX_21C760D72C2AC5D3 (translatable_id), INDEX IDX_21C760D7E559DFD1 (locale_id), INDEX IDX_21C760D7E4C68F85 (bannerImage_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE group_event_email (id INT AUTO_INCREMENT NOT NULL, subject VARCHAR(255) NOT NULL, message LONGTEXT DEFAULT NULL, sent_at DATETIME NOT NULL, groupEvent_id INT DEFAULT NULL, INDEX IDX_8331D2997AC93FAC (groupEvent_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE group_event_email_recipient (groupeventemail_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_D24E3344EF30A18B (groupeventemail_id), INDEX IDX_D24E3344A76ED395 (user_id), PRIMARY KEY(groupeventemail_id, user_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE group_event (id INT AUTO_INCREMENT NOT NULL, group_id INT DEFAULT NULL, user_id INT DEFAULT NULL, game_id INT DEFAULT NULL, attendeeCount INT DEFAULT NULL, private TINYINT(1) NOT NULL, deletedReason VARCHAR(50) DEFAULT NULL, deleted TINYINT(1) NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, content LONGTEXT DEFAULT NULL, registration_option VARCHAR(255) NOT NULL, published TINYINT(1) NOT NULL, approved TINYINT(1) NOT NULL, active TINYINT(1) NOT NULL, online TINYINT(1) NOT NULL, starts_at DATETIME DEFAULT NULL, ends_at DATETIME DEFAULT NULL, timezone VARCHAR(255) NOT NULL, display_timezone TINYINT(1) NOT NULL, external_url VARCHAR(255) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, bannerImage_id INT DEFAULT NULL, INDEX IDX_6B8221C0FE54D947 (group_id), INDEX IDX_6B8221C0A76ED395 (user_id), INDEX IDX_6B8221C0E4C68F85 (bannerImage_id), INDEX IDX_6B8221C0E48FD905 (game_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE group_events_sites (groupevent_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_E0FA287C83BF5DFA (groupevent_id), INDEX IDX_E0FA287CF6BD1646 (site_id), PRIMARY KEY(groupevent_id, site_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE group_events_attendees (groupevent_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_AE8CF7EA83BF5DFA (groupevent_id), INDEX IDX_AE8CF7EAA76ED395 (user_id), PRIMARY KEY(groupevent_id, user_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE global_event (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, game_id INT DEFAULT NULL, attendeeCount INT DEFAULT NULL, hosted_by VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, content LONGTEXT DEFAULT NULL, registration_option VARCHAR(255) NOT NULL, published TINYINT(1) NOT NULL, approved TINYINT(1) NOT NULL, active TINYINT(1) NOT NULL, online TINYINT(1) NOT NULL, starts_at DATETIME DEFAULT NULL, ends_at DATETIME DEFAULT NULL, timezone VARCHAR(255) NOT NULL, display_timezone TINYINT(1) NOT NULL, external_url VARCHAR(255) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, bannerImage_id INT DEFAULT NULL, INDEX IDX_7FAB70E4A76ED395 (user_id), INDEX IDX_7FAB70E4E4C68F85 (bannerImage_id), INDEX IDX_7FAB70E4E48FD905 (game_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE global_events_sites (globalevent_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_F70631C6E3BC917 (globalevent_id), INDEX IDX_F70631CF6BD1646 (site_id), PRIMARY KEY(globalevent_id, site_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE global_events_attendees (globalevent_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_18BCEDE06E3BC917 (globalevent_id), INDEX IDX_18BCEDE0A76ED395 (user_id), PRIMARY KEY(globalevent_id, user_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE group_event_translation ADD CONSTRAINT FK_C1A4B9D32C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES group_event(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE group_event_translation ADD CONSTRAINT FK_C1A4B9D3E559DFD1 FOREIGN KEY (locale_id) REFERENCES pd_site(id)");
        $this->addSql("ALTER TABLE group_event_translation ADD CONSTRAINT FK_C1A4B9D3E4C68F85 FOREIGN KEY (bannerImage_id) REFERENCES pd_media(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE global_event_email ADD CONSTRAINT FK_DC6A98DA71F7E88B FOREIGN KEY (event_id) REFERENCES global_event(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE global_event_email_recipient ADD CONSTRAINT FK_31AE70B0BAEAEB FOREIGN KEY (globaleventemail_id) REFERENCES global_event_email(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE global_event_email_recipient ADD CONSTRAINT FK_31AE70B0A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE global_event_translation ADD CONSTRAINT FK_21C760D72C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES global_event(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE global_event_translation ADD CONSTRAINT FK_21C760D7E559DFD1 FOREIGN KEY (locale_id) REFERENCES pd_site(id)");
        $this->addSql("ALTER TABLE global_event_translation ADD CONSTRAINT FK_21C760D7E4C68F85 FOREIGN KEY (bannerImage_id) REFERENCES pd_media(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE group_event_email ADD CONSTRAINT FK_8331D2997AC93FAC FOREIGN KEY (groupEvent_id) REFERENCES group_event(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE group_event_email_recipient ADD CONSTRAINT FK_D24E3344EF30A18B FOREIGN KEY (groupeventemail_id) REFERENCES group_event_email(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE group_event_email_recipient ADD CONSTRAINT FK_D24E3344A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE group_event ADD CONSTRAINT FK_6B8221C0FE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE group_event ADD CONSTRAINT FK_6B8221C0A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE group_event ADD CONSTRAINT FK_6B8221C0E4C68F85 FOREIGN KEY (bannerImage_id) REFERENCES pd_media(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE group_event ADD CONSTRAINT FK_6B8221C0E48FD905 FOREIGN KEY (game_id) REFERENCES pd_game(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE group_events_sites ADD CONSTRAINT FK_E0FA287C83BF5DFA FOREIGN KEY (groupevent_id) REFERENCES group_event(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE group_events_sites ADD CONSTRAINT FK_E0FA287CF6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE group_events_attendees ADD CONSTRAINT FK_AE8CF7EA83BF5DFA FOREIGN KEY (groupevent_id) REFERENCES group_event(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE group_events_attendees ADD CONSTRAINT FK_AE8CF7EAA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE global_event ADD CONSTRAINT FK_7FAB70E4A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE global_event ADD CONSTRAINT FK_7FAB70E4E4C68F85 FOREIGN KEY (bannerImage_id) REFERENCES pd_media(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE global_event ADD CONSTRAINT FK_7FAB70E4E48FD905 FOREIGN KEY (game_id) REFERENCES pd_game(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE global_events_sites ADD CONSTRAINT FK_F70631C6E3BC917 FOREIGN KEY (globalevent_id) REFERENCES global_event(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE global_events_sites ADD CONSTRAINT FK_F70631CF6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE global_events_attendees ADD CONSTRAINT FK_18BCEDE06E3BC917 FOREIGN KEY (globalevent_id) REFERENCES global_event(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE global_events_attendees ADD CONSTRAINT FK_18BCEDE0A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE pd_deal_locale");
        $this->addSql("DROP TABLE user_event");
        $this->addSql("ALTER TABLE pd_content_report ADD groupEvent_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_content_report ADD CONSTRAINT FK_E798A78E7AC93FAC FOREIGN KEY (groupEvent_id) REFERENCES group_event(id) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_E798A78E7AC93FAC ON pd_content_report (groupEvent_id)");
        $this->addSql("ALTER TABLE event DROP city, DROP country, DROP location, DROP hosted_by, DROP gameStr");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE global_event_email_recipient DROP FOREIGN KEY FK_31AE70B0BAEAEB");
        $this->addSql("ALTER TABLE group_event_email_recipient DROP FOREIGN KEY FK_D24E3344EF30A18B");
        $this->addSql("ALTER TABLE pd_content_report DROP FOREIGN KEY FK_E798A78E7AC93FAC");
        $this->addSql("ALTER TABLE group_event_translation DROP FOREIGN KEY FK_C1A4B9D32C2AC5D3");
        $this->addSql("ALTER TABLE group_event_email DROP FOREIGN KEY FK_8331D2997AC93FAC");
        $this->addSql("ALTER TABLE group_events_sites DROP FOREIGN KEY FK_E0FA287C83BF5DFA");
        $this->addSql("ALTER TABLE group_events_attendees DROP FOREIGN KEY FK_AE8CF7EA83BF5DFA");
        $this->addSql("ALTER TABLE global_event_email DROP FOREIGN KEY FK_DC6A98DA71F7E88B");
        $this->addSql("ALTER TABLE global_event_translation DROP FOREIGN KEY FK_21C760D72C2AC5D3");
        $this->addSql("ALTER TABLE global_events_sites DROP FOREIGN KEY FK_F70631C6E3BC917");
        $this->addSql("ALTER TABLE global_events_attendees DROP FOREIGN KEY FK_18BCEDE06E3BC917");
        $this->addSql("CREATE TABLE pd_deal_locale (id INT AUTO_INCREMENT NOT NULL, deal_id INT DEFAULT NULL, locale VARCHAR(255) NOT NULL, UNIQUE INDEX deal_locale (deal_id, locale), INDEX IDX_85314BCFF60E2305 (deal_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE user_event (user_id INT NOT NULL, event_id INT NOT NULL, INDEX IDX_D96CF1FFA76ED395 (user_id), INDEX IDX_D96CF1FF71F7E88B (event_id), PRIMARY KEY(user_id, event_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_deal_locale ADD CONSTRAINT FK_85314BCFF60E2305 FOREIGN KEY (deal_id) REFERENCES pd_deal(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE user_event ADD CONSTRAINT FK_D96CF1FF71F7E88B FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE user_event ADD CONSTRAINT FK_D96CF1FFA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE group_event_translation");
        $this->addSql("DROP TABLE global_event_email");
        $this->addSql("DROP TABLE global_event_email_recipient");
        $this->addSql("DROP TABLE global_event_translation");
        $this->addSql("DROP TABLE group_event_email");
        $this->addSql("DROP TABLE group_event_email_recipient");
        $this->addSql("DROP TABLE group_event");
        $this->addSql("DROP TABLE group_events_sites");
        $this->addSql("DROP TABLE group_events_attendees");
        $this->addSql("DROP TABLE global_event");
        $this->addSql("DROP TABLE global_events_sites");
        $this->addSql("DROP TABLE global_events_attendees");
        $this->addSql("ALTER TABLE event ADD city VARCHAR(255) DEFAULT NULL, ADD country VARCHAR(255) DEFAULT NULL, ADD location VARCHAR(255) DEFAULT NULL, ADD hosted_by VARCHAR(255) DEFAULT NULL, ADD gameStr VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_content_report DROP FOREIGN KEY FK_E798A78E7AC93FAC");
        $this->addSql("DROP INDEX IDX_E798A78E7AC93FAC ON pd_content_report");
        $this->addSql("ALTER TABLE pd_content_report DROP groupEvent_id");
    }
}
