<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121126230350 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE region (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE region_country (region_id INT NOT NULL, country_id INT NOT NULL, INDEX IDX_4861B8E198260155 (region_id), INDEX IDX_4861B8E1F92F3E70 (country_id), PRIMARY KEY(region_id, country_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE region_country ADD CONSTRAINT FK_4861B8E198260155 FOREIGN KEY (region_id) REFERENCES region(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE region_country ADD CONSTRAINT FK_4861B8E1F92F3E70 FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE fos_user ADD ipAddress VARCHAR(50) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE region_country DROP FOREIGN KEY FK_4861B8E198260155");
        $this->addSql("DROP TABLE region");
        $this->addSql("DROP TABLE region_country");
        $this->addSql("ALTER TABLE fos_user DROP ipAddress");
    }
}
