<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121217200649 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE commenting_thread (id VARCHAR(255) NOT NULL, is_commentable TINYINT(1) NOT NULL, last_commented_at DATETIME NOT NULL, comment_count INT NOT NULL, permalink VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_716A806DF286BC32 (permalink), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE commenting_comment (id INT AUTO_INCREMENT NOT NULL, thread_id VARCHAR(255) DEFAULT NULL, parent_id INT DEFAULT NULL, author_id INT DEFAULT NULL, body LONGTEXT NOT NULL, created_at DATETIME NOT NULL, deleted TINYINT(1) NOT NULL, deletedReason VARCHAR(50) DEFAULT NULL, INDEX IDX_D386D7DFE2904019 (thread_id), INDEX IDX_D386D7DF727ACA70 (parent_id), INDEX IDX_D386D7DFF675F31B (author_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE commenting_vote (id INT AUTO_INCREMENT NOT NULL, comment_id INT DEFAULT NULL, user_id INT DEFAULT NULL, ip_address VARCHAR(20) NOT NULL, vote_type VARCHAR(255) NOT NULL, voted_at DATETIME NOT NULL, INDEX IDX_22D2EDACF8697D13 (comment_id), INDEX IDX_22D2EDACA76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE commenting_comment ADD CONSTRAINT FK_D386D7DFE2904019 FOREIGN KEY (thread_id) REFERENCES commenting_thread(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE commenting_comment ADD CONSTRAINT FK_D386D7DF727ACA70 FOREIGN KEY (parent_id) REFERENCES commenting_comment(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE commenting_comment ADD CONSTRAINT FK_D386D7DFF675F31B FOREIGN KEY (author_id) REFERENCES fos_user(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE commenting_vote ADD CONSTRAINT FK_22D2EDACF8697D13 FOREIGN KEY (comment_id) REFERENCES commenting_comment(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE commenting_vote ADD CONSTRAINT FK_22D2EDACA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_filtered_media DROP FOREIGN KEY FK_5B5FC3CD727ACA70");
        $this->addSql("ALTER TABLE pd_filtered_media ADD CONSTRAINT FK_5B5FC3CD727ACA70 FOREIGN KEY (parent_id) REFERENCES pd_media(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE commenting_comment DROP FOREIGN KEY FK_D386D7DFE2904019");
        $this->addSql("ALTER TABLE commenting_comment DROP FOREIGN KEY FK_D386D7DF727ACA70");
        $this->addSql("ALTER TABLE commenting_vote DROP FOREIGN KEY FK_22D2EDACF8697D13");
        $this->addSql("DROP TABLE commenting_thread");
        $this->addSql("DROP TABLE commenting_comment");
        $this->addSql("DROP TABLE commenting_vote");
        $this->addSql("ALTER TABLE pd_filtered_media DROP FOREIGN KEY FK_5B5FC3CD727ACA70");
        $this->addSql("ALTER TABLE pd_filtered_media ADD CONSTRAINT FK_5B5FC3CD727ACA70 FOREIGN KEY (parent_id) REFERENCES pd_media(id) ON DELETE SET NULL");
    }
}
