<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120329211716 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE sweepstakes_entry DROP FOREIGN KEY FK_B701FFEAA76ED395");
        $this->addSql("ALTER TABLE sweepstakes_entry ADD CONSTRAINT FK_B701FFEAA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE sweepstakes_entry DROP FOREIGN KEY FK_B701FFEAA76ED395");
        $this->addSql("ALTER TABLE sweepstakes_entry ADD CONSTRAINT FK_B701FFEAA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id)");
    }
}
