<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140213172727 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE event_session (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, content LONGTEXT DEFAULT NULL, starts_at DATETIME DEFAULT NULL, ends_at DATETIME DEFAULT NULL, INDEX IDX_55137C7B71F7E88B (event_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE eventsession_user (eventsession_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_BED6B71DAA3673FF (eventsession_id), INDEX IDX_BED6B71DA76ED395 (user_id), PRIMARY KEY(eventsession_id, user_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE event_session ADD CONSTRAINT FK_55137C7B71F7E88B FOREIGN KEY (event_id) REFERENCES group_event(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE eventsession_user ADD CONSTRAINT FK_BED6B71DAA3673FF FOREIGN KEY (eventsession_id) REFERENCES event_session(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE eventsession_user ADD CONSTRAINT FK_BED6B71DA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE eventsession_user DROP FOREIGN KEY FK_BED6B71DAA3673FF");
        $this->addSql("DROP TABLE event_session");
        $this->addSql("DROP TABLE eventsession_user");
    }
}
