<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131018160135 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE group_events_attendees_gallary");
        $this->addSql("ALTER TABLE global_event CHANGE isVotingActive isVotingActive TINYINT(1) DEFAULT NULL");
        $this->addSql("ALTER TABLE group_event CHANGE isVotingActive isVotingActive TINYINT(1) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE group_events_attendees_gallary (groupevent_id INT NOT NULL, user_id INT NOT NULL, gallary_id INT NOT NULL, INDEX groupevent_id (groupevent_id), INDEX user_id (user_id), INDEX gallary_id (gallary_id), PRIMARY KEY(groupevent_id, user_id, gallary_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE global_event CHANGE isVotingActive isVotingActive TINYINT(1) NOT NULL");
        $this->addSql("ALTER TABLE group_event CHANGE isVotingActive isVotingActive TINYINT(1) NOT NULL");
    }
}
