<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120607172755 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("UPDATE `event` SET `external_url` = IF(`external_url` is null, `url_redirect`, `external_url`) WHERE `discr` = 'event' AND `id` > 0");
        $this->addSql("ALTER TABLE event DROP url_redirect");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE event ADD url_redirect VARCHAR(255) DEFAULT NULL");
        $this->addSql("UPDATE `event` SET `url_redirect` = `external_url` WHERE `discr` = 'event' AND `id` > 0");
    }
}
