<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130225182125 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE group_event_email DROP FOREIGN KEY FK_8331D2997AC93FAC");
        $this->addSql("DROP INDEX IDX_8331D2997AC93FAC ON group_event_email");
        $this->addSql("ALTER TABLE group_event_email CHANGE groupevent_id event_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE group_event_email ADD CONSTRAINT FK_8331D29971F7E88B FOREIGN KEY (event_id) REFERENCES group_event(id) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_8331D29971F7E88B ON group_event_email (event_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE group_event_email DROP FOREIGN KEY FK_8331D29971F7E88B");
        $this->addSql("DROP INDEX IDX_8331D29971F7E88B ON group_event_email");
        $this->addSql("ALTER TABLE group_event_email CHANGE event_id groupEvent_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE group_event_email ADD CONSTRAINT FK_8331D2997AC93FAC FOREIGN KEY (groupEvent_id) REFERENCES group_event(id) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_8331D2997AC93FAC ON group_event_email (groupEvent_id)");
    }
}
