<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140220182917 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE event_session DROP FOREIGN KEY FK_55137C7B12B05715");
        $this->addSql("ALTER TABLE event_session ADD CONSTRAINT FK_55137C7B12B05715 FOREIGN KEY (source_idea_id) REFERENCES idea(id) ON DELETE SET NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE event_session DROP FOREIGN KEY FK_55137C7B12B05715");
        $this->addSql("ALTER TABLE event_session ADD CONSTRAINT FK_55137C7B12B05715 FOREIGN KEY (source_idea_id) REFERENCES idea(id)");
    }
}
