<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130405123140 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE pd_queue_status (id INT AUTO_INCREMENT NOT NULL, giveaway_id INT DEFAULT NULL, user_id INT DEFAULT NULL, status VARCHAR(50) NOT NULL, type VARCHAR(50) NOT NULL, created_at DATETIME NOT NULL, reason VARCHAR(100) NOT NULL, INDEX IDX_5030B28734ABDE8C (giveaway_id), INDEX IDX_5030B287A76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_queue_status ADD CONSTRAINT FK_5030B28734ABDE8C FOREIGN KEY (giveaway_id) REFERENCES event(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE pd_queue_status ADD CONSTRAINT FK_5030B287A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE SET NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE pd_queue_status");
    }
}
