<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130920154548 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE code_assignment_code (id INT AUTO_INCREMENT NOT NULL, user INT DEFAULT NULL, assignment INT DEFAULT NULL, code VARCHAR(255) NOT NULL, INDEX IDX_7130DFC18D93D649 (user), INDEX IDX_7130DFC130C544BA (assignment), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE code_assignment (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE code_assignment_code ADD CONSTRAINT FK_7130DFC18D93D649 FOREIGN KEY (user) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE code_assignment_code ADD CONSTRAINT FK_7130DFC130C544BA FOREIGN KEY (assignment) REFERENCES code_assignment(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE code_assignment_code ADD email_sent_at DATETIME DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE code_assignment_code");
        $this->addSql("DROP TABLE code_assignment");
    }
}
