<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140702100153 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE global_event_rsvp_actions CHANGE imported_from imported_from VARCHAR(255) DEFAULT NULL, CHANGE external_event_id external_event_id INT DEFAULT NULL, CHANGE ticket_type ticket_type VARCHAR(255) DEFAULT NULL, CHANGE promo_code promo_code VARCHAR(255) DEFAULT NULL, CHANGE amount_paid amount_paid NUMERIC(10, 0) DEFAULT NULL");
        $this->addSql("ALTER TABLE group_event_rsvp_actions CHANGE imported_from imported_from VARCHAR(255) DEFAULT NULL, CHANGE external_event_id external_event_id INT DEFAULT NULL, CHANGE ticket_type ticket_type VARCHAR(255) DEFAULT NULL, CHANGE promo_code promo_code VARCHAR(255) DEFAULT NULL, CHANGE amount_paid amount_paid NUMERIC(10, 0) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE global_event_rsvp_actions CHANGE imported_from imported_from VARCHAR(255) NOT NULL, CHANGE external_event_id external_event_id INT NOT NULL, CHANGE ticket_type ticket_type VARCHAR(255) NOT NULL, CHANGE promo_code promo_code VARCHAR(255) NOT NULL, CHANGE amount_paid amount_paid NUMERIC(10, 0) NOT NULL");
        $this->addSql("ALTER TABLE group_event_rsvp_actions CHANGE imported_from imported_from VARCHAR(255) NOT NULL, CHANGE external_event_id external_event_id INT NOT NULL, CHANGE ticket_type ticket_type VARCHAR(255) NOT NULL, CHANGE promo_code promo_code VARCHAR(255) NOT NULL, CHANGE amount_paid amount_paid NUMERIC(10, 0) NOT NULL");
    }
}
