<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140221123243 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_groups ADD parentGroup_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_groups ADD CONSTRAINT FK_D63978B71222E2A FOREIGN KEY (parentGroup_id) REFERENCES pd_groups(id) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_D63978B71222E2A ON pd_groups (parentGroup_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_groups DROP FOREIGN KEY FK_D63978B71222E2A");
        $this->addSql("DROP INDEX IDX_D63978B71222E2A ON pd_groups");
        $this->addSql("ALTER TABLE pd_groups DROP parentGroup_id");
    }
}
