<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130423223521 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_videos_youtube_galleries (youtubevideo_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_C4B7B912FD53B1D7 (youtubevideo_id), INDEX IDX_C4B7B9124E7AF8F (gallery_id), PRIMARY KEY(youtubevideo_id, gallery_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_videos_youtube_galleries ADD CONSTRAINT FK_C4B7B912FD53B1D7 FOREIGN KEY (youtubevideo_id) REFERENCES pd_videos_youtube(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_videos_youtube_galleries ADD CONSTRAINT FK_C4B7B9124E7AF8F FOREIGN KEY (gallery_id) REFERENCES pd_gallery(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_videos_youtube DROP FOREIGN KEY FK_3F69BE412469DE2");
        $this->addSql("DROP INDEX IDX_3F69BE412469DE2 ON pd_videos_youtube");
        $this->addSql("ALTER TABLE pd_videos_youtube DROP category_id");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE pd_videos_youtube_galleries");
        $this->addSql("ALTER TABLE pd_videos_youtube ADD category_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_videos_youtube ADD CONSTRAINT FK_3F69BE412469DE2 FOREIGN KEY (category_id) REFERENCES pd_videos_youtube_category(id)");
        $this->addSql("CREATE INDEX IDX_3F69BE412469DE2 ON pd_videos_youtube (category_id)");
    }
}
