<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130523190012 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_videos_youtube DROP thumbnail_hq, DROP thumbnail_sq, CHANGE is_accessible is_accessible TINYINT(1) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_videos_youtube ADD thumbnail_hq VARCHAR(255) NOT NULL, ADD thumbnail_sq VARCHAR(255) NOT NULL, CHANGE is_accessible is_accessible TINYINT(1) DEFAULT '1'");
    }
}
