<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130326211836 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE pd_videos_youtube (id INT AUTO_INCREMENT NOT NULL, author_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(512) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted TINYINT(1) NOT NULL, deletedReason VARCHAR(255) DEFAULT NULL, thumbnail_hq VARCHAR(255) NOT NULL, thumbnail_sq VARCHAR(255) NOT NULL, youtube_id VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_3F69BE4989D9B62 (slug), UNIQUE INDEX UNIQ_3F69BE42B36786B (title), INDEX IDX_3F69BE4F675F31B (author_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_video_galleries (youtubevideo_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_A8F945FFD53B1D7 (youtubevideo_id), INDEX IDX_A8F945F4E7AF8F (gallery_id), PRIMARY KEY(youtubevideo_id, gallery_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_videos_youtube ADD CONSTRAINT FK_3F69BE4F675F31B FOREIGN KEY (author_id) REFERENCES fos_user(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE pd_video_galleries ADD CONSTRAINT FK_A8F945FFD53B1D7 FOREIGN KEY (youtubevideo_id) REFERENCES pd_videos_youtube(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_video_galleries ADD CONSTRAINT FK_A8F945F4E7AF8F FOREIGN KEY (gallery_id) REFERENCES pd_gallery(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_video_galleries DROP FOREIGN KEY FK_A8F945FFD53B1D7");
        $this->addSql("DROP TABLE pd_videos_youtube");
        $this->addSql("DROP TABLE pd_video_galleries");
    }
}
