<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140508175450 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE watched_events (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, global_event INT DEFAULT NULL, group_event INT DEFAULT NULL, createdAt DATETIME NOT NULL, INDEX IDX_D4BB68B2A76ED395 (user_id), INDEX IDX_D4BB68B27FAB70E4 (global_event), INDEX IDX_D4BB68B26B8221C0 (group_event), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE watched_events ADD CONSTRAINT FK_D4BB68B2A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id)");
        $this->addSql("ALTER TABLE watched_events ADD CONSTRAINT FK_D4BB68B27FAB70E4 FOREIGN KEY (global_event) REFERENCES global_event(id)");
        $this->addSql("ALTER TABLE watched_events ADD CONSTRAINT FK_D4BB68B26B8221C0 FOREIGN KEY (group_event) REFERENCES group_event(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE watched_events");
    }
}
