<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120814162143 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE groupvideo_contentreport (groupvideo_id INT NOT NULL, contentreport_id INT NOT NULL, INDEX IDX_21D99C9CDB89B53F (groupvideo_id), INDEX IDX_21D99C9C37A50B4F (contentreport_id), PRIMARY KEY(groupvideo_id, contentreport_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE groupnews_contentreport (groupnews_id INT NOT NULL, contentreport_id INT NOT NULL, INDEX IDX_E2D63A509F1166F3 (groupnews_id), INDEX IDX_E2D63A5037A50B4F (contentreport_id), PRIMARY KEY(groupnews_id, contentreport_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_content_report (id INT AUTO_INCREMENT NOT NULL, reporter_id INT DEFAULT NULL, reason VARCHAR(255) NOT NULL, reported_at DATETIME NOT NULL, deleted TINYINT(1) NOT NULL, INDEX IDX_E798A78EE1CFE6F5 (reporter_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE groupvideo_contentreport ADD CONSTRAINT FK_21D99C9CDB89B53F FOREIGN KEY (groupvideo_id) REFERENCES pd_group_video(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE groupvideo_contentreport ADD CONSTRAINT FK_21D99C9C37A50B4F FOREIGN KEY (contentreport_id) REFERENCES pd_content_report(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE groupnews_contentreport ADD CONSTRAINT FK_E2D63A509F1166F3 FOREIGN KEY (groupnews_id) REFERENCES pd_group_news(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE groupnews_contentreport ADD CONSTRAINT FK_E2D63A5037A50B4F FOREIGN KEY (contentreport_id) REFERENCES pd_content_report(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_content_report ADD CONSTRAINT FK_E798A78EE1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES fos_user(id) ON DELETE SET NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE groupvideo_contentreport DROP FOREIGN KEY FK_21D99C9C37A50B4F");
        $this->addSql("ALTER TABLE groupnews_contentreport DROP FOREIGN KEY FK_E2D63A5037A50B4F");
        $this->addSql("DROP TABLE groupvideo_contentreport");
        $this->addSql("DROP TABLE groupnews_contentreport");
        $this->addSql("DROP TABLE pd_content_report");
    }
}
