<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131211184902 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_site ADD entrySetRegistration_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_site ADD CONSTRAINT FK_1025CCFBD0E9DF32 FOREIGN KEY (entrySetRegistration_id) REFERENCES EntrySetRegistry(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_1025CCFBD0E9DF32 ON pd_site (entrySetRegistration_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_site DROP FOREIGN KEY FK_1025CCFBD0E9DF32");
        $this->addSql("DROP INDEX UNIQ_1025CCFBD0E9DF32 ON pd_site");
        $this->addSql("ALTER TABLE pd_site DROP entrySetRegistration_id");
    }
}
