<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120827142035 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE pd_group_site (group_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_40195294FE54D947 (group_id), INDEX IDX_40195294F6BD1646 (site_id), PRIMARY KEY(group_id, site_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_site (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, defaultLocale VARCHAR(255) NOT NULL, subDomain VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_group_site ADD CONSTRAINT FK_40195294FE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_group_site ADD CONSTRAINT FK_40195294F6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");

        $this->addSql("INSERT INTO `pd_site` (`name`, `defaultLocale`, `subDomain`) VALUES
            ('Demo', 'en', 'demo'),
            ('Japan', 'ja', 'japan'),
            ('China', 'zh', 'china'),
            ('North America', 'en_US', 'na'),
            ('Europe', 'en_GB', 'eu'),
            ('Latin America', 'es', 'latam'),
            ('India', 'en_IN', 'in'),
            ('Singapore', 'en_SG', 'mysg'),
            ('Australia / New Zealand', 'en_AU', 'anz')");

         $this->addSql("DROP TABLE pd_groups_locales");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_group_site DROP FOREIGN KEY FK_40195294F6BD1646");
        $this->addSql("DROP TABLE pd_group_site");
        $this->addSql("DROP TABLE pd_site");

        $this->addSql("CREATE TABLE pd_groups_locales (id INT AUTO_INCREMENT NOT NULL, group_id INT DEFAULT NULL, locale VARCHAR(255) NOT NULL, UNIQUE INDEX group_locale (group_id, locale), INDEX IDX_B7A728A8FE54D947 (group_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_groups_locales ADD CONSTRAINT FK_B7A728A8FE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id) ON DELETE CASCADE");
    }
}
