<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130516190918 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_timeline (id INT AUTO_INCREMENT NOT NULL, site_id INT DEFAULT NULL, author_id INT DEFAULT NULL, created_at DATETIME NOT NULL, google_doc_url VARCHAR(512) NOT NULL, INDEX IDX_C39ED0BDF6BD1646 (site_id), INDEX IDX_C39ED0BDF675F31B (author_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_timeline ADD CONSTRAINT FK_C39ED0BDF6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id)");
        $this->addSql("ALTER TABLE pd_timeline ADD CONSTRAINT FK_C39ED0BDF675F31B FOREIGN KEY (author_id) REFERENCES fos_user(id) ON DELETE SET NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE pd_timeline");
    }
}
