<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131014221125 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fos_user ADD organization VARCHAR(255) DEFAULT NULL, ADD title VARCHAR(255) DEFAULT NULL, ADD industry VARCHAR(255) DEFAULT NULL, ADD eventRole VARCHAR(255) DEFAULT NULL, DROP school, DROP major, DROP svicRole");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fos_user ADD school VARCHAR(255) DEFAULT NULL, ADD major VARCHAR(255) DEFAULT NULL, ADD svicRole VARCHAR(255) DEFAULT NULL, DROP organization, DROP title, DROP industry, DROP eventRole");
    }
}
