<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130411232755 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_videos_youtube ADD site_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_videos_youtube ADD CONSTRAINT FK_3F69BE4F6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id)");
        $this->addSql("CREATE INDEX IDX_3F69BE4F6BD1646 ON pd_videos_youtube (site_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_videos_youtube DROP FOREIGN KEY FK_3F69BE4F6BD1646");
        $this->addSql("DROP INDEX IDX_3F69BE4F6BD1646 ON pd_videos_youtube");
        $this->addSql("ALTER TABLE pd_videos_youtube DROP site_id");
    }
}
