<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131009112953 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE groupevent_media (groupevent_id INT NOT NULL, media_id INT NOT NULL, INDEX IDX_9FB181EA83BF5DFA (groupevent_id), INDEX IDX_9FB181EAEA9FDD75 (media_id), PRIMARY KEY(groupevent_id, media_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE groupevent_media ADD CONSTRAINT FK_9FB181EA83BF5DFA FOREIGN KEY (groupevent_id) REFERENCES group_event(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE groupevent_media ADD CONSTRAINT FK_9FB181EAEA9FDD75 FOREIGN KEY (media_id) REFERENCES pd_media(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE groupevent_media");
    }
}
