<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130411155939 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_site_config ADD supportEmailAddress VARCHAR(255) NOT NULL, ADD automatedEmailAddress VARCHAR(255) NOT NULL, ADD emailFromName VARCHAR(255) NOT NULL");
        $this->addSql('UPDATE `pd_site_config` INNER JOIN `pd_site` ON `pd_site`.`id` = `pd_site_config`.`site_id` SET `pd_site_config`.`supportEmailAddress` = `pd_site`.`supportEmailAddress`, `pd_site_config`.`automatedEmailAddress` = "noreply@alienwarearena.com", `emailFromName`="Alienware Arena"');
        $this->addSql("ALTER TABLE pd_site DROP supportEmailAddress, DROP automatedEmailAddress");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_site ADD supportEmailAddress VARCHAR(255) NOT NULL, ADD automatedEmailAddress VARCHAR(255) NOT NULL");
        $this->addSql('UPDATE `pd_site` INNER JOIN `pd_site_config` ON `pd_site`.`id` = `pd_site_config`.`site_id` SET `pd_site`.`supportEmailAddress` = `pd_site_config`.`supportEmailAddress`, `pd_site`.`automatedEmailAddress` = `pd_site_config`.`automatedEmailAddress`');
        $this->addSql("ALTER TABLE pd_site_config DROP supportEmailAddress, DROP automatedEmailAddress, DROP emailFromName");
    }
}
