<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120416173543 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE pd_machine_code_entry (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, giveaway_id INT NOT NULL, key_id INT DEFAULT NULL, machineCode VARCHAR(255) NOT NULL, ipAddress VARCHAR(100) DEFAULT NULL, status VARCHAR(20) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_C13FB636A76ED395 (user_id), INDEX IDX_C13FB63634ABDE8C (giveaway_id), INDEX IDX_C13FB636D145533 (key_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_machine_code_entry ADD CONSTRAINT FK_C13FB636A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_machine_code_entry ADD CONSTRAINT FK_C13FB63634ABDE8C FOREIGN KEY (giveaway_id) REFERENCES event(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_machine_code_entry ADD CONSTRAINT FK_C13FB636D145533 FOREIGN KEY (key_id) REFERENCES giveaway_key(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE sweepstakes_entry DROP FOREIGN KEY FK_B701FFEAA76ED395");
        $this->addSql("ALTER TABLE sweepstakes_entry ADD CONSTRAINT FK_B701FFEAA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE pd_machine_code_entry");
        $this->addSql("ALTER TABLE sweepstakes_entry DROP FOREIGN KEY FK_B701FFEAA76ED395");
        $this->addSql("ALTER TABLE sweepstakes_entry ADD CONSTRAINT FK_B701FFEAA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id)");
    }
}
