<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130226220749 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE pd_deal_locale");
        $this->addSql("ALTER TABLE pd_deal ADD group_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A980409FE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_9A980409FE54D947 ON pd_deal (group_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_deal_locale (id INT AUTO_INCREMENT NOT NULL, deal_id INT DEFAULT NULL, locale VARCHAR(255) NOT NULL, UNIQUE INDEX deal_locale (deal_id, locale), INDEX IDX_85314BCFF60E2305 (deal_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_deal_locale ADD CONSTRAINT FK_85314BCFF60E2305 FOREIGN KEY (deal_id) REFERENCES pd_deal(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_deal DROP FOREIGN KEY FK_9A980409FE54D947");
        $this->addSql("DROP INDEX UNIQ_9A980409FE54D947 ON pd_deal");
        $this->addSql("ALTER TABLE pd_deal DROP group_id");
    }
}
