<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130513112643 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_site_config ADD forward_base_url VARCHAR(255) DEFAULT NULL, ADD forwarded_paths LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)'");
        $this->addSql("ALTER TABLE pd_site_features ADD has_forward_on_404 TINYINT(1) NOT NULL");
	    $this->addSql("ALTER TABLE pd_site_features ADD has_index TINYINT(1) NOT NULL");
	    $this->addSql("ALTER TABLE pd_site_features ADD has_about TINYINT(1) NOT NULL, ADD has_contact TINYINT(1) NOT NULL");
        $this->addSql('UPDATE pd_site_features SET `has_forward_on_404` = 0, `has_index` = 1, `has_about` = 1 WHERE `site_id` IN (1,2,3)');
        $this->addSql('UPDATE pd_site_features SET `has_forward_on_404` = 1, `has_index` = 0, `has_about` = 0 WHERE `site_id` IN (4,5,6,7,8,9)');
        $this->addSql('UPDATE pd_site_config SET `forward_base_url` = "http://www.alienwarearena.com", `forwarded_paths` = \'a:4:{i:0;s:5:"^/arp";i:1;s:8:"^/forums";i:2;s:9:"^/contact";i:3;s:7:"^/about";}\' WHERE `site_id` IN (4,5,6,7,8,9)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE pd_site_config DROP forward_base_url, DROP forwarded_paths");
        $this->addSql("ALTER TABLE pd_site_features DROP has_forward_on_404");
	    $this->addSql("ALTER TABLE pd_site_features DROP has_index");
	    $this->addSql("ALTER TABLE pd_site_features DROP has_about, DROP has_contact");
    }
}
