<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120416142228 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_event_sponsor DROP FOREIGN KEY FK_81AF815EF98F144A");
        $this->addSql("ALTER TABLE pd_sponsor DROP FOREIGN KEY FK_84AACA86F98F144A");
        $this->addSql("ALTER TABLE pd_event_sponsor DROP FOREIGN KEY FK_81AF815E12F7FB51");
        $this->addSql("ALTER TABLE award_nomination DROP FOREIGN KEY FK_890B519E9033212A");
        $this->addSql("ALTER TABLE pd_site DROP FOREIGN KEY FK_1025CCFB9033212A");
        $this->addSql("ALTER TABLE pd_translation DROP FOREIGN KEY FK_649F4BB46DEC9D60");
        $this->addSql("ALTER TABLE pd_translation_token DROP FOREIGN KEY FK_D18AE792727ACA70");
        $this->addSql("DROP TABLE award_nomination");
        $this->addSql("DROP TABLE event_bak");
        $this->addSql("DROP TABLE pd_event_sponsor");
        $this->addSql("DROP TABLE pd_group");
        $this->addSql("DROP TABLE pd_group_bak");
        $this->addSql("DROP TABLE pd_media");
        $this->addSql("DROP TABLE pd_report_event_log");
        $this->addSql("DROP TABLE pd_site");
        $this->addSql("DROP TABLE pd_sponsor");
        $this->addSql("DROP TABLE pd_tenant");
        $this->addSql("DROP TABLE pd_translation");
        $this->addSql("DROP TABLE pd_translation_token");
        $this->addSql("DROP TABLE session");
        $this->addSql("DROP TABLE survey");
        $this->addSql("ALTER TABLE event ADD showKeys TINYINT(1) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE award_nomination (id INT AUTO_INCREMENT NOT NULL, tenant_id INT DEFAULT NULL, author_id INT NOT NULL, program VARCHAR(255) NOT NULL, created DATETIME NOT NULL, nom_description LONGTEXT NOT NULL, phone VARCHAR(255) NOT NULL, years INT NOT NULL, relationship VARCHAR(255) NOT NULL, nom_name_first VARCHAR(255) NOT NULL, nom_name_last VARCHAR(255) NOT NULL, nom_city VARCHAR(255) NOT NULL, nom_state VARCHAR(255) NOT NULL, nom_country VARCHAR(255) NOT NULL, nom_email VARCHAR(255) DEFAULT NULL, nom_phone VARCHAR(255) DEFAULT NULL, nom_url_primary VARCHAR(255) DEFAULT NULL, nom_url_secondary LONGTEXT DEFAULT NULL, INDEX IDX_890B519EF675F31B (author_id), INDEX IDX_890B519E9033212A (tenant_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE event_bak (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, ready TINYINT(1) NOT NULL, content LONGTEXT DEFAULT NULL, locale VARCHAR(2) NOT NULL, bannerImage VARCHAR(255) DEFAULT NULL, generalImage VARCHAR(255) DEFAULT NULL, discr VARCHAR(255) NOT NULL, published TINYINT(1) DEFAULT NULL, starts_at DATETIME DEFAULT NULL, ends_at DATETIME DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, state VARCHAR(10) DEFAULT NULL, zipcode VARCHAR(10) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, streetAddress VARCHAR(255) DEFAULT NULL, hosted_by VARCHAR(255) DEFAULT NULL, game VARCHAR(255) DEFAULT NULL, ext_reg VARCHAR(255) DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, mainGroup_id INT DEFAULT NULL, redemptionInstructions LONGTEXT DEFAULT NULL, status VARCHAR(15) DEFAULT NULL, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, INDEX IDX_3BAE0AA78721F385 (mainGroup_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_event_sponsor (id INT AUTO_INCREMENT NOT NULL, sponsor_id INT DEFAULT NULL, event_id INT DEFAULT NULL, logo_id INT DEFAULT NULL, sponsorshipLevel VARCHAR(100) NOT NULL, url VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_81AF815E71F7E88B (event_id), INDEX IDX_81AF815E12F7FB51 (sponsor_id), INDEX IDX_81AF815EF98F144A (logo_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, site VARCHAR(20) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_group_bak (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, site VARCHAR(20) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_media (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, size INT DEFAULT NULL, mimeType VARCHAR(255) DEFAULT NULL, INDEX IDX_E75DCA3C7E3C61F9 (owner_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_report_event_log (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, category VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, extraData LONGTEXT NOT NULL COMMENT '(DC2Type:array)', siteKey VARCHAR(100) DEFAULT NULL, tenantKey VARCHAR(100) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_9ECF3308A76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_site (id INT AUTO_INCREMENT NOT NULL, tenant_id INT DEFAULT NULL, site_key VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, locale VARCHAR(100) NOT NULL, subdomain VARCHAR(100) DEFAULT NULL, INDEX IDX_1025CCFB9033212A (tenant_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_sponsor (id INT AUTO_INCREMENT NOT NULL, logo_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, site VARCHAR(20) NOT NULL, isSiteSponsor TINYINT(1) NOT NULL, url VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_84AACA86F98F144A (logo_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_tenant (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, features LONGTEXT NOT NULL COMMENT '(DC2Type:array)', tenantParameters LONGTEXT NOT NULL COMMENT '(DC2Type:array)', baseHost VARCHAR(100) NOT NULL, theme VARCHAR(100) NOT NULL, functionalTheme VARCHAR(100) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_translation (id INT AUTO_INCREMENT NOT NULL, language VARCHAR(10) NOT NULL, translation LONGTEXT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, translationToken_id INT DEFAULT NULL, INDEX IDX_649F4BB46DEC9D60 (translationToken_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_translation_token (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, domain VARCHAR(200) NOT NULL, token VARCHAR(200) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, isInMessagesFile TINYINT(1) NOT NULL, UNIQUE INDEX token_domain_idx (token, domain), INDEX IDX_D18AE792727ACA70 (parent_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE session (session_id VARCHAR(255) NOT NULL, session_value LONGTEXT NOT NULL, session_time INT NOT NULL, PRIMARY KEY(session_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE survey (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, surveyid VARCHAR(25) NOT NULL, provider VARCHAR(25) NOT NULL, parameters VARCHAR(255) NOT NULL, next VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE award_nomination ADD CONSTRAINT FK_890B519E9033212A FOREIGN KEY (tenant_id) REFERENCES pd_tenant(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE award_nomination ADD CONSTRAINT FK_890B519EF675F31B FOREIGN KEY (author_id) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_event_sponsor ADD CONSTRAINT FK_81AF815E12F7FB51 FOREIGN KEY (sponsor_id) REFERENCES pd_sponsor(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_event_sponsor ADD CONSTRAINT FK_81AF815E71F7E88B FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_event_sponsor ADD CONSTRAINT FK_81AF815EF98F144A FOREIGN KEY (logo_id) REFERENCES pd_media(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_media ADD CONSTRAINT FK_E75DCA3C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_report_event_log ADD CONSTRAINT FK_9ECF3308A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE pd_site ADD CONSTRAINT FK_1025CCFB9033212A FOREIGN KEY (tenant_id) REFERENCES pd_tenant(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_sponsor ADD CONSTRAINT FK_84AACA86F98F144A FOREIGN KEY (logo_id) REFERENCES pd_media(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_translation ADD CONSTRAINT FK_649F4BB46DEC9D60 FOREIGN KEY (translationToken_id) REFERENCES pd_translation_token(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_translation_token ADD CONSTRAINT FK_D18AE792727ACA70 FOREIGN KEY (parent_id) REFERENCES pd_translation_token(id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE event DROP showKeys");
    }
}
