<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121109131618 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_contest_entry (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, contest_id INT DEFAULT NULL, ipAddress VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_A2280C7DA76ED395 (user_id), INDEX IDX_A2280C7D1CD0F0DE (contest_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_contest_entry ADD CONSTRAINT FK_A2280C7DA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_contest_entry ADD CONSTRAINT FK_A2280C7D1CD0F0DE FOREIGN KEY (contest_id) REFERENCES pd_contest(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE pd_contest_entry");
    }
}
