<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120726161600 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_locations (id INT AUTO_INCREMENT NOT NULL, address1 VARCHAR(255) NOT NULL, address2 VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, state_province VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_groups ADD location_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_groups ADD CONSTRAINT FK_D63978B764D218E FOREIGN KEY (location_id) REFERENCES pd_locations(id) ON DELETE SET NULL");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_D63978B764D218E ON pd_groups (location_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_groups DROP FOREIGN KEY FK_D63978B764D218E");
        $this->addSql("DROP TABLE pd_locations");
        $this->addSql("ALTER TABLE pd_groups DROP FOREIGN KEY FK_D63978B764D218E");
        $this->addSql("DROP INDEX UNIQ_D63978B764D218E ON pd_groups");
        $this->addSql("ALTER TABLE pd_groups DROP location_id");
    }
}
