<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130509181916 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE pd_gallery_translation (id INT AUTO_INCREMENT NOT NULL, gallery_id INT DEFAULT NULL, site_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_1C1398E15E237E06 (name), INDEX IDX_1C1398E14E7AF8F (gallery_id), INDEX IDX_1C1398E1F6BD1646 (site_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_gallery_translation ADD CONSTRAINT FK_1C1398E14E7AF8F FOREIGN KEY (gallery_id) REFERENCES pd_gallery(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_gallery_translation ADD CONSTRAINT FK_1C1398E1F6BD1646 FOREIGN KEY (site_id) REFERENCES pd_site(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_gallery DROP translations");
        $this->addSql("ALTER TABLE pd_gallery_translation CHANGE name name VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE pd_gallery_translation");
        $this->addSql("ALTER TABLE pd_gallery ADD translations LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)'");
    }
}
