<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131203172054 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE entry_set (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) DEFAULT NULL, isVotingActive TINYINT(1) NOT NULL, isSubmissionActive TINYINT(1) NOT NULL, allowedVoters VARCHAR(5000) DEFAULT NULL, UNIQUE INDEX UNIQ_15A85BBA5E237E06 (name), INDEX IDX_15A85BBA71F7E88B (event_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE entry_set ADD CONSTRAINT FK_15A85BBA71F7E88B FOREIGN KEY (event_id) REFERENCES group_event(id)");
        $this->addSql("ALTER TABLE group_event DROP isVotingActive, DROP isSubmissionActive, DROP allowedVoters, DROP type");
        $this->addSql("ALTER TABLE global_event DROP isVotingActive, DROP isSubmissionActive, DROP allowedVoters, DROP type");
        $this->addSql("ALTER TABLE idea DROP FOREIGN KEY FK_A8BCA4571F7E88B");
        $this->addSql("DROP INDEX IDX_A8BCA4571F7E88B ON idea");
        $this->addSql("ALTER TABLE idea CHANGE event_id entrySet_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE idea ADD CONSTRAINT FK_A8BCA4519758714 FOREIGN KEY (entrySet_id) REFERENCES entry_set(id)");
        $this->addSql("CREATE INDEX IDX_A8BCA4519758714 ON idea (entrySet_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE idea DROP FOREIGN KEY FK_A8BCA4519758714");
        $this->addSql("DROP TABLE entry_set");
        $this->addSql("ALTER TABLE global_event ADD isVotingActive TINYINT(1) NOT NULL, ADD isSubmissionActive TINYINT(1) NOT NULL, ADD allowedVoters VARCHAR(5000) DEFAULT NULL, ADD type VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE group_event ADD isVotingActive TINYINT(1) NOT NULL, ADD isSubmissionActive TINYINT(1) NOT NULL, ADD allowedVoters VARCHAR(5000) DEFAULT NULL, ADD type VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE idea DROP FOREIGN KEY FK_A8BCA4519758714");
        $this->addSql("DROP INDEX IDX_A8BCA4519758714 ON idea");
        $this->addSql("ALTER TABLE idea CHANGE entryset_id event_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE idea ADD CONSTRAINT FK_A8BCA4571F7E88B FOREIGN KEY (event_id) REFERENCES group_event(id)");
        $this->addSql("CREATE INDEX IDX_A8BCA4571F7E88B ON idea (event_id)");
    }
}
