<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121030170834 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_country_age_restriction_ruleset (id INT AUTO_INCREMENT NOT NULL, parent_type VARCHAR(255) NOT NULL, default_allow TINYINT(1) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pd_country_age_restriction_rule (id INT AUTO_INCREMENT NOT NULL, country_id INT DEFAULT NULL, min_age INT NOT NULL, max_age INT NOT NULL, rule_type VARCHAR(50) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_870AA50FF92F3E70 (country_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule ADD CONSTRAINT FK_870AA50FF92F3E70 FOREIGN KEY (country_id) REFERENCES country(id)");
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule ADD CONSTRAINT FK_870AA50FBF396750 FOREIGN KEY (id) REFERENCES pd_country_age_restriction_ruleset(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE event ADD ruleset_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA754F1C144 FOREIGN KEY (ruleset_id) REFERENCES pd_country_age_restriction_ruleset(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_3BAE0AA754F1C144 ON event (ruleset_id)");
        $this->addSql("ALTER TABLE pd_contest ADD ruleset_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_contest ADD CONSTRAINT FK_48F5FE754F1C144 FOREIGN KEY (ruleset_id) REFERENCES pd_country_age_restriction_ruleset(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_48F5FE754F1C144 ON pd_contest (ruleset_id)");
        $this->addSql("ALTER TABLE pd_deal ADD ruleset_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE pd_deal ADD CONSTRAINT FK_9A98040954F1C144 FOREIGN KEY (ruleset_id) REFERENCES pd_country_age_restriction_ruleset(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_9A98040954F1C144 ON pd_deal (ruleset_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE pd_country_age_restriction_rule DROP FOREIGN KEY FK_870AA50FBF396750");
        $this->addSql("ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA754F1C144");
        $this->addSql("ALTER TABLE pd_contest DROP FOREIGN KEY FK_48F5FE754F1C144");
        $this->addSql("ALTER TABLE pd_deal DROP FOREIGN KEY FK_9A98040954F1C144");
        $this->addSql("DROP TABLE pd_country_age_restriction_ruleset");
        $this->addSql("DROP TABLE pd_country_age_restriction_rule");
        $this->addSql("ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA754F1C144");
        $this->addSql("DROP INDEX UNIQ_3BAE0AA754F1C144 ON event");
        $this->addSql("ALTER TABLE event DROP ruleset_id");
        $this->addSql("ALTER TABLE pd_contest DROP FOREIGN KEY FK_48F5FE754F1C144");
        $this->addSql("DROP INDEX UNIQ_48F5FE754F1C144 ON pd_contest");
        $this->addSql("ALTER TABLE pd_contest DROP ruleset_id");
        $this->addSql("ALTER TABLE pd_deal DROP FOREIGN KEY FK_9A98040954F1C144");
        $this->addSql("DROP INDEX UNIQ_9A98040954F1C144 ON pd_deal");
        $this->addSql("ALTER TABLE pd_deal DROP ruleset_id");
    }
}
