<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130314182114 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE event ADD thumbnail_id INT DEFAULT NULL, ADD featured TINYINT(1) DEFAULT NULL, ADD featured_at DATETIME DEFAULT NULL");
        $this->addSql("ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7FDFF2E92 FOREIGN KEY (thumbnail_id) REFERENCES pd_media(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_3BAE0AA7FDFF2E92 ON event (thumbnail_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7FDFF2E92");
        $this->addSql("DROP INDEX UNIQ_3BAE0AA7FDFF2E92 ON event");
        $this->addSql("ALTER TABLE event DROP thumbnail_id, DROP featured, DROP featured_at");
    }
}
