<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130509185423 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE pd_videos_youtube_groups (youtubevideo_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_5CD1B064FD53B1D7 (youtubevideo_id), INDEX IDX_5CD1B064FE54D947 (group_id), PRIMARY KEY(youtubevideo_id, group_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE pd_videos_youtube_groups ADD CONSTRAINT FK_5CD1B064FD53B1D7 FOREIGN KEY (youtubevideo_id) REFERENCES pd_videos_youtube(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_videos_youtube_groups ADD CONSTRAINT FK_5CD1B064FE54D947 FOREIGN KEY (group_id) REFERENCES pd_groups(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE pd_videos_youtube CHANGE description description VARCHAR(512) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE pd_videos_youtube_groups");
        $this->addSql("ALTER TABLE pd_videos_youtube CHANGE description description VARCHAR(512) DEFAULT NULL");
    }
}
