<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130312143510 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE group_event CHANGE address address1 VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE group_event ADD address2 VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE global_event CHANGE address address1 VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE global_event ADD address2 VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE global_event ADD address VARCHAR(255) DEFAULT NULL, DROP address1, DROP address2");
        $this->addSql("ALTER TABLE group_event ADD address VARCHAR(255) DEFAULT NULL, DROP address1, DROP address2");
    }
}
