<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131021223734 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fos_user ADD linkedIn LONGTEXT DEFAULT NULL, ADD professionalEmail LONGTEXT DEFAULT NULL, ADD twitterUsername LONGTEXT DEFAULT NULL, ADD website LONGTEXT DEFAULT NULL, ADD mailingAddress LONGTEXT DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fos_user DROP linkedIn, DROP professionalEmail, DROP twitterUsername, DROP website, DROP mailingAddress");
    }
}
