<?php

namespace Platformd\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Platformd\SpoutletBundle\Entity\Game;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    /**
     * Used in the admin
     *
     * @return \Doctrine\ORM\Query
     */
    public function getFindNewsQuery()
    {
        return $this->createQueryBuilder('n')
            ->orderBy('n.postedAt', 'DESC')
            ->getQuery();
    }

    /**
     * @param $locale
     * @return array
     */
    public function findAllForLocale($locale)
    {
        return $this->createBaseQueryBuilder($locale)
            ->orderBy('n.postedAt', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }

    /**
     * @param $locale
     * @return \Platformd\NewsBundle\Entity\News;
     */
    public function findOneFeaturedForLocale($locale)
    {
        // todo - this will need to do something smarter - see #68
        return $this->createBaseQueryBuilder($locale)
            ->orderBy('n.postedAt', 'DESC')
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult()
        ;
    }

    /**
     * @param $locale
     * @param $num
     * @return \Platformd\NewsBundle\Entity\News[]
     */
    public function findMostRecentForLocale($locale, $num)
    {
        return $this->createBaseQueryBuilder($locale)
            ->orderBy('n.postedAt', 'DESC')
            ->getQuery()
            ->setMaxResults($num)
            ->execute()
        ;
    }

    /**
     * @param Game $game
     * @param string $site The site (i.e. locale)
     * @return \Platformd\NewsBundle\Entity\News[]
     */
    public function findActivesForGame(Game $game, $site)
    {
        return $this->createBaseQueryBuilder($site)
            ->andWhere('n.game = :game')
            ->setParameter('game', $game)
            ->orderBy('n.postedAt', 'DESC')
            ->getQuery()
            ->execute()
        ;
    }

    /**
     * Creates a base query builder that's locale-aware and only returns
     * published entries
     *
     * @param $locale
     * @param \Doctrine\ORM\QueryBuilder|null $qb
     * @return \Doctrine\ORM\QueryBuilder|null
     */
    protected function createBaseQueryBuilder($locale, QueryBuilder $qb = null)
    {
        if ($qb === null) {
            $qb = $this->createQueryBuilder('n');
        }

        $qb->andWhere('n.locale = :locale')
            ->setParameter('locale', $locale)
            ->andWhere('n.published = 1')
        ;

        return $qb;
    }
}