_group_member_check:
    pattern: /esi/USER_SPECIFIC/groupMemberCheck/{groupId}
    defaults: { _controller: GroupBundle:Group:_groupMemberCheck }

military:
    pattern: /groups/military
    defaults: { _controller: SpoutletBundle:Default:military }

GroupBundle_admin_group:
    resource: "@GroupBundle/Resources/config/routing/admin_group.yml"
    prefix:   /admin/groups

GroupBundle_group:
    resource: "@GroupBundle/Resources/config/routing/group.yml"
    prefix:   /groups

GroupBundle_group_no_prefix:
    resource: "@GroupBundle/Resources/config/routing/group_no_prefix.yml"
    prefix:   /
