imports:
    - { resource: "validation.yml" }

services:
    platformd.model.group_manager:
        class: Platformd\GroupBundle\Model\GroupManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@session"
            - "@knp_media.util.media_util"
            - "@platformd.util.site_util"
            - "@pd.cevo.api.api_manager"
            - "@security.token_storage"
            - "@event_dispatcher"
            - "@platformd_event.service.group_event"
            - "@media_exposer"

    platformd.repository.group:
        class: Platformd\GroupBundle\Entity\GroupRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - 'GroupBundle:Group'

