services:
    platformd.model.group_manager:
        class: Platformd\GroupBundle\Model\GroupManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@session"
            - "@knp_media.util.media_util"
            - "@platformd.util.site_util"
            - "@pd.cevo.api.api_manager"
            - "@security.context"
            - "@event_dispatcher"

