parameters:
#    hp_cloud.example.class: Platformd\HPCloudBundle\Example

services:
#    hp_cloud.example:
#        class: %hp_cloud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
