groups:
    pattern:  /
    defaults: { _controller: "GroupBundle:Group:index" }

group_new_getting_started:
    pattern:  /new-getting-started/
    defaults: { _controller: "GroupBundle:Group:newGettingStarted", site: ~ }

group_new:
    pattern:  /new/
    defaults: { _controller: "GroupBundle:Group:new", site: ~ }

group_create:
    pattern:  /create/
    defaults: { _controller: "GroupBundle:Group:new", site: ~ }

group_edit_discussion_post:
    pattern: /discussion-post/{id}/edit
    defaults: { _controller: "GroupBundle:Group:editDiscussionPost", site: ~ }

group_delete_discussion_post:
    pattern: /discussion-post/{id}/delete
    defaults: { _controller: "GroupBundle:Group:deleteDiscussionPost", site: ~ }

group_show_prefixed:
    pattern:  /{slug}/
    defaults: { _controller: "GroupBundle:Group:showPrefixed", site: ~ }

group_image_show:
    pattern:  /image/{id}
    defaults: { _controller: "GroupBundle:Group:showImage", site: ~ }
