group_show:
    pattern:  /{slug}/
    defaults: { _controller: "GroupBundle:Group:show", site: ~ }

group_slug_show:
    pattern:  /{slug}/
    defaults: { _controller: "GroupBundle:Group:show", site: ~ }

group_event_register_and_join:
    pattern: /{groupSlug}/event/register/{eventId}
    defaults: { _controller:"EventBundle:GroupEvent:register", site: ~ }

group_event_new:
    pattern: /{groupSlug}/event/new
    defaults: { _controller:"EventBundle:GroupEvent:new", site: ~ }

group_event_new_import:
    pattern: /{groupSlug}/event/new/import/{eventId}
    defaults: { _controller:"EventBundle:GroupEvent:newFromImport", site: ~ }

group_event_edit:
    pattern: /{groupSlug}/event/edit/{eventId}
    defaults: { _controller:"EventBundle:GroupEvent:edit", site: ~ }

group_event_pending_approval:
    pattern: /{groupSlug}/events/pending-approval
    defaults: { _controller:"EventBundle:GroupEvent:pendingApprovalList", site: ~ }

group_event_approve:
    pattern: /{groupSlug}/event/approve/{eventId}
    defaults: { _controller:"EventBundle:GroupEvent:approve", site: ~ }

group_event_delete:
    pattern: /{groupSlug}/event/delete/{eventId}
    defaults: { _controller:"EventBundle:GroupEvent:delete", site: ~ }

group_event_contact:
    pattern: /{groupSlug}/event/contact/{eventSlug}
    defaults: { _controller:"EventBundle:GroupEvent:contact", site: ~ }

group_event_attendees:
    pattern: /{groupSlug}/event/attendees/{eventSlug}
    defaults: { _controller:"EventBundle:GroupEvent:attendees", site: ~ }

group_event_email_preview:
    pattern: /{groupSlug}/event/contact-preview/{eventSlug}
    defaults: { _controller:"EventBundle:GroupEvent:emailPreview", site: ~ }
    requirements:
        _method: POST

group_event_remove_attendee:
    pattern: /{groupSlug}/event/{eventSlug}/remove/{userId}
    defaults: { _controller: EventBundle:GroupEvent:removeAttendee }

group_event_view:
    pattern: /{groupSlug}/event/{eventSlug}
    defaults: { _controller:"EventBundle:GroupEvent:view", site: ~ }
