group_show:
    pattern:  /{slug}/
    defaults: { _controller: "GroupBundle:Group:show", site: ~ }

group_slug_show:
    pattern:  /{slug}/
    defaults: { _controller: "GroupBundle:Group:show", site: ~ }

group_event_register_and_join:
    pattern: /{groupSlug}/event/register/{eventId}
    defaults: { _controller:"EventBundle:GroupEvent:register", site: ~ }

group_event_new:
    pattern: /{groupSlug}/event/new
    defaults: { _controller:"EventBundle:GroupEvent:new", site: ~ }

group_event_new_import:
    pattern: /{groupSlug}/event/new/import/{eventId}
    defaults: { _controller:"EventBundle:GroupEvent:newFromImport", site: ~ }

group_event_edit:
    pattern: /{groupSlug}/event/edit/{eventId}
    defaults: { _controller:"EventBundle:GroupEvent:edit", site: ~ }

group_event_pending_approval:
    pattern: /{groupSlug}/events/pending-approval
    defaults: { _controller:"EventBundle:GroupEvent:pendingApprovalList", site: ~ }

group_event_approve:
    pattern: /{groupSlug}/event/approve/{eventId}
    defaults: { _controller:"EventBundle:GroupEvent:approve", site: ~ }

group_event_delete:
    pattern: /{groupSlug}/event/delete/{eventId}
    defaults: { _controller:"EventBundle:GroupEvent:delete", site: ~ }

group_event_contact:
    pattern: /{groupSlug}/event/contact/{eventSlug}
    defaults: { _controller:"EventBundle:GroupEvent:contact", site: ~ }

group_event_attendees:
    pattern: /{groupSlug}/event/attendees/{eventSlug}
    defaults: { _controller:"EventBundle:GroupEvent:attendees", site: ~ }

group_event_email_preview:
    pattern: /{groupSlug}/event/contact-preview/{eventSlug}
    defaults: { _controller:"EventBundle:GroupEvent:emailPreview", site: ~ }
    requirements:
        _method: POST

group_event_remove_attendee:
    pattern: /{groupSlug}/event/{eventSlug}/remove/{userId}
    defaults: { _controller: EventBundle:GroupEvent:removeAttendee }

group_event_view:
    pattern: /{groupSlug}/event/{eventSlug}
    defaults: { _controller:"EventBundle:GroupEvent:view", site: ~ }

# New additions

group_edit:
    pattern:  /{slug}/edit/
    defaults: { _controller: "GroupBundle:Group:edit", site: ~ }

group_events:
    pattern: /{slug}/events/
    defaults: { _controller: "GroupBundle:Group:events", site: ~ }

group_news:
    pattern: /{slug}/news/
    defaults: { _controller: "GroupBundle:Group:news", site: ~ }

group_add_news:
    pattern:  /{slug}/add-news/
    defaults: { _controller: "GroupBundle:Group:addNews", site: ~ }

group_delete_news:
    pattern:  /{slug}/delete-news/{newsId}
    defaults: { _controller: "GroupBundle:Group:deleteNews", site: ~ }

group_edit_news:
    pattern:  /{slug}/edit-news/{newsId}
    defaults: { _controller: "GroupBundle:Group:editNews", site: ~ }

group_images:
    pattern: /{slug}/images/
    defaults: { _controller: "GroupBundle:Group:image", site: ~ }

group_add_image:
    pattern:  /{slug}/add-image/
    defaults: { _controller: "GroupBundle:Group:addImage", site: ~ }

group_delete_image:
    pattern:  /{slug}/delete-image/{imageId}
    defaults: { _controller: "GroupBundle:Group:deleteImage", site: ~ }

group_edit_image:
    pattern:  /{slug}/edit-image/{imageId}
    defaults: { _controller: "GroupBundle:Group:editImage", site: ~ }

group_videos:
    pattern: /{slug}/videos/
    defaults: { _controller: "GroupBundle:Group:videos", site: ~ }

group_add_video:
    pattern:  /{slug}/add-video/
    defaults: { _controller: "GroupBundle:Group:addVideo", site: ~ }

group_delete_video:
    pattern:  /{slug}/delete-video/{videoId}
    defaults: { _controller: "GroupBundle:Group:deleteVideo", site: ~ }

group_edit_video:
    pattern:  /{slug}/edit-video/{videoId}
    defaults: { _controller: "GroupBundle:Group:editVideo", site: ~ }

group_discussions:
    pattern: /{slug}/discussions/
    defaults: { _controller: "GroupBundle:Group:discussions", site: ~ }

group_enable_discussions:
    pattern: /{slug}/discussions-enable/
    defaults: { _controller: "GroupBundle:Group:enableDiscussions", site: ~ }

group_disable_discussions:
    pattern: /{slug}/discussions-disable/
    defaults: { _controller: "GroupBundle:Group:disableDiscussions", site: ~ }

group_add_discussion:
    pattern: /{slug}/add-discussion/
    defaults: { _controller: "GroupBundle:Group:addDiscussion", site: ~ }

group_delete_discussion:
    pattern: /{slug}/delete-discussion/{discussionId}
    defaults: { _controller: "GroupBundle:Group:deleteDiscussion", site: ~ }

group_edit_discussion:
    pattern: /{slug}/edit-discussion/{discussionId}
    defaults: { _controller: "GroupBundle:Group:editDiscussion", site: ~ }

group_view_discussion:
    pattern: /{slug}/discussion/{discussionId}
    defaults: { _controller: "GroupBundle:Group:viewDiscussion", site: ~ }

group_reply_discussion:
    pattern: /{slug}/discussion/{discussionId}/reply
    defaults: { _controller: "GroupBundle:Group:replyDiscussion", site: ~ }

group_about:
    pattern: /{slug}/about
    defaults: { _controller: "GroupBundle:Group:about", site: ~ }

group_leave:
    pattern:  /{slug}/leave/
    defaults: { _controller: "GroupBundle:Group:leave", site: ~ }

group_join:
    pattern:  /{slug}/join/
    defaults: { _controller: "GroupBundle:Group:join", site: ~ }

group_apply_with_event:
    pattern:  /{slug}/apply-event/{eventId}
    defaults: { _controller: "GroupBundle:Group:applyToGroupWithEvent", site: ~ }

group_apply:
    pattern:  /{slug}/apply/
    defaults: { _controller: "GroupBundle:Group:applyToGroup", site: ~ }

group_delete:
    pattern:  /{slug}/delete/
    defaults: { _controller: "GroupBundle:Group:delete", site: ~ }

group_update:
    pattern:  /{slug}/update/
    defaults: { _controller: "GroupBundle:Group:edit", site: ~ }
    requirements: { _method: post }

group_applications:
    pattern:  /{slug}/applications/
    defaults: { _controller: "GroupBundle:Group:applications", site: ~ }

group_accept_application:
    pattern:  /{slug}/applications/{applicationId}/accept
    defaults: { _controller: "GroupBundle:Group:acceptApplication", site: ~ }

group_reject_application:
    pattern:  /{slug}/applications/{applicationId}/reject
    defaults: { _controller: "GroupBundle:Group:rejectApplication", site: ~ }

group_members:
    pattern: /{slug}/members
    defaults: { _controller: "GroupBundle:Group:members", site: ~ }

group_remove_member:
    pattern: /{slug}/remove/{uid}
    defaults: { _controller: "GroupBundle:Group:remove", site: ~ }



