admin_giveaway_index:
    pattern: /
    defaults: { _controller: GiveawayBundle:GiveawayAdmin:index }

admin_giveaway_new:
    pattern: /new
    defaults: { _controller: GiveawayBundle:GiveawayAdmin:new }

admin_giveaway_edit:
    pattern: /edit/{id}
    defaults: { _controller: GiveawayBundle:GiveawayAdmin:edit }
