admin_giveaway_index:
    pattern: /
    defaults: { _controller: GiveawayBundle:GiveawayAdmin:index }

admin_giveaway_new:
    pattern: /new
    defaults: { _controller: GiveawayBundle:GiveawayAdmin:new }

admin_giveaway_export_machine_codes:
    pattern: /{id}/export
    defaults: { _controller: GiveawayBundle:GiveawayAdmin:export }

admin_giveaway_edit:
    pattern: /edit/{id}
    defaults: { _controller: GiveawayBundle:GiveawayAdmin:edit }

admin_giveaway_machine_codes:
    pattern: /codes/{id}
    defaults: { _controller: GiveawayBundle:GiveawayAdmin:codes }

admin_giveaway_pool_index:
    pattern: /{giveaway}/pools
    defaults: { _controller: GiveawayBundle:GiveawayPoolAdmin:index }

admin_giveaway_pool_new:
    pattern: /{giveaway}/pools/new
    defaults: { _controller: GiveawayBundle:GiveawayPoolAdmin:new }

admin_giveaway_pool_edit:
    pattern: /{giveaway}/pools/edit/{pool}
    defaults: { _controller: GiveawayBundle:GiveawayPoolAdmin:edit }

admin_giveaway_pool_delete:
    pattern: /{giveaway}/pools/delete/{pool}
    defaults: { _controller: GiveawayBundle:GiveawayPoolAdmin:delete }
