_deal_flash_message:
    pattern: /esi/USER_SPECIFIC/dealFlashMessage/{dealId}
    defaults: { _controller: GiveawayBundle:Deal:_dealFlashMessage }

_deal_show_actions:
    pattern: /esi/USER_SPECIFIC/dealShowMainActions/{dealId}
    defaults: { _controller: GiveawayBundle:Deal:_dealShowActions }

deal_list:
    pattern:  /
    defaults: { _controller: "GiveawayBundle:Deal:index" }

deal_show:
    pattern:  /{slug}
    defaults: { _controller: "GiveawayBundle:Deal:show" }

deal_redeem:
    pattern:  /{slug}/redeem/{joinGroup}
    defaults: { _controller: "GiveawayBundle:Deal:redeem", joinGroup: true }

deal_repies:
    pattern: /{slug}/replies
    defaults: { _controller: "GiveawayBundle:Deal:commentReplies" }
