<?php

namespace Platformd\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Platformd\GameBundle\Entity\GamePage;

/**
 * GamePageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamePageRepository extends EntityRepository
{
    /**
     * @param string $site
     * @return \Platformd\GameBundle\Entity\GamePage[]
     */
    public function findAllForSiteNewestFirst($site)
    {
        return $this->createSiteQueryBuilder($site)
            ->addOrderBy('gp.createdAt', 'DESC')
            ->getQuery()
            ->execute();
    }

    /**
     * @param integer $age
     * @param string $site
     * @return \Platformd\GameBundle\Entity\GamePage[]
     */
    public function findActiveGamesForAge($age, $site)
    {
        // we don't use the age yet

        $qb = $this->createSiteQueryBuilder($site);
        $this->addPublishedQueryBuilder($qb);

        return $qb
            ->addOrderBy('gp.createdAt', 'DESC')
            ->getQuery()
            ->execute();
    }

    /**
     * @param $age
     * @param $site
     * @return \Platformd\GameBundle\Entity\GamePage
     */
    public function findMostRecentGameForAge($age, $site)
    {
        // we don't use the age yet

        $qb = $this->createSiteQueryBuilder($site);
        $this->addPublishedQueryBuilder($qb);

        return $qb
            ->addOrderBy('gp.createdAt', 'DESC')
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

    /**
     * @param $site
     * @return \Platformd\GameBundle\Entity\GamePage[]
     */
    public function findArchivesForSite($site)
    {
        $qb = $this->createSiteQueryBuilder($site);
        $this->addArchivedQueryBuilder($qb);

        return $qb
            ->addOrderBy('gp.createdAt', 'DESC')
            ->getQuery()
            ->execute();
    }

    /**
     * @param string $slug
     * @param string $site
     * @return \Platformd\GameBundle\Entity\GamePage
     */
    public function findOneBySlugForSite($slug, $site)
    {
        return $this->createSiteQueryBuilder($site)
            ->andWhere('gp.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param \Platformd\GameBundle\Entity\Game $game
     * @param string $site
     * @return \Platformd\GameBundle\Entity\GamePage
     */
    public function findOneByGame($game, $site)
    {
        return $this->createSiteQueryBuilder($site)
            ->andWhere('gp.game = :game')
            ->setParameter('game', $game)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }

    public function findAllGamePagesWhereIdNotIn($inArray, $site) {

        $qb = $this->createSiteQueryBuilder($site)
            ->leftJoin('gp.game', 'g')
            ->andWhere('gp.status = :status');

        if (!empty($inArray)) {
            $qb->andWhere('gp.id NOT IN (:inArray)')
                ->setParameter('inArray', $inArray);
        }

        $qb->addOrderBy('gp.createdAt', 'DESC')
            ->setParameter('status', GamePage::STATUS_PUBLISHED);

        return $qb->getQuery()->execute();
    }

    public function findAllByGamePagesByCategory($category, $site, $limit = null)
    {
        $qb = $this->createSiteQueryBuilder($site)
            ->leftJoin('gp.game', 'g')
            ->andWhere('g.category = :category')
            ->andWhere('gp.status = :status')
            ->setParameter('category', $category)
            ->setParameter('status', GamePage::STATUS_PUBLISHED);

        if ($limit != null) {
            $qb->setMaxResults($limit);
        }

        return $qb->addOrderBy('gp.createdAt', 'DESC')->getQuery()->execute();
    }

    /**
     * @param $site
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function createSiteQueryBuilder($site)
    {
        $qb = $this->createQueryBuilder('gp')
            ->leftJoin('gp.sites', 's');

        if (is_string($site)) {
            $qb->andWhere('s.name = :site')
                ->setParameter('site', $site);

            return $qb;
        }

        $qb->andWhere('s = :site')
            ->setParameter('site', $site);

        return $qb;
    }

    private function addPublishedQueryBuilder(QueryBuilder $qb)
    {
        return $qb->andWhere('gp.status = :status')
            ->setParameter('status', GamePage::STATUS_PUBLISHED);
    }

    private function addArchivedQueryBuilder(QueryBuilder $qb)
    {
        return $qb->andWhere('gp.status = :status')
            ->setParameter('status', GamePage::STATUS_ARCHIVED);
    }
}
