pd_translation_admin_list_locales:
    pattern: /admin/translations
    defaults: { _controller: TranslationBundle:TranslationAdmin:listLocales }

pd_translation_admin_edit_locale:
    pattern: /admin/translations/{locale}
    defaults: { _controller: TranslationBundle:TranslationAdmin:editLocale }