services:
    pd_translation.translation.loader.entity_loader:
        class: Platformd\TranslationBundle\Translation\Loader\EntityLoader
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: translation.loader, alias: entity}

    pd_translation.translation.updater:
        class: Platformd\TranslationBundle\Translation\Updater
        arguments:
            - "@jms_translation.loader_manager"
            - "@jms_translation.extractor_manager"
            - "@doctrine.orm.entity_manager"
            - "@logger"