<?php

namespace Platformd\SpoutletBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestRepository extends EntityRepository
{
    public function findAllForSiteAlphabetically($site) {

        return $this->createSiteQueryBuilder($site)
            ->orderBy('c.name', 'ASC')
            ->getQuery()
            ->execute();
    }

    public function findAllForSiteByDate($site)
    {
        return $this->createQueryBuilder('c')
            ->leftJoin('c.sites', 's')
            ->where('c.votingEnd > :today')
            ->andWhere('s.defaultLocale = :site')
            ->setParameter('site', $site)
            ->setParameter('today', new \DateTime('now'))
            ->orderBy('c.votingEnd', 'DESC')
            ->getQuery()
            ->execute();
    }

    public function findAllAlphabetically()
    {
        return $this->createQueryBuilder('c')
            ->orderBy('c.name', 'ASC')
            ->getQuery()
            ->execute();
    }

    private function createSiteQueryBuilder($site)
    {
        $qb = $this->createQueryBuilder('c')
            ->leftJoin('c.sites', 's')
            ->where('s.defaultLocale = :site OR s = :site')
            ->setParameter('site', $site)
        ;

        return $qb;
    }

    public function canUserVoteBasedOnSite($user, $contest)
    {
        $result = $this->createQueryBuilder('c')
            ->leftJoin('c.sites', 's')
            ->andWhere('s.defaultLocale = :locale')
            ->setParameter('locale', $user->getLocale())
            ->getQuery()
            ->execute();

        return $result ? true : false;
    }

    public function findAllByCategoryAndSite($category, $site)
    {
        return $this->createSiteQueryBuilder($site)
            ->andWhere('c.category = :category')
            ->andWhere('c.votingEnd > :today')
            ->setParameter('category', $category)
            ->setParameter('today', new \DateTime('now'))
            ->getQuery()
            ->execute();
    }

    public function findAllByCategory($category)
    {
        return $this->createQueryBuilder('c')
            ->where('c.category = :category')
            ->setParameter('category', $category)
            ->getQuery()
            ->execute();
    }

    public function findAllExpiredBySite($site)
    {
        return $this->createSiteQueryBuilder($site)
            ->andWhere('c.votingEnd < :today')
            ->setParameter('today', new \DateTime('now'))
            ->getQuery()
            ->execute();
    }
}
