<?php

namespace Platformd\SpoutletBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository
{
    public function findAllAlphabetically() {
        return $this->createQueryBuilder('g')
            ->orderBy('g.name', 'ASC')
            ->getQuery()
            ->execute();
    }

    public function findAllGalleriesByCategory($category)
    {
        return $this->createQueryBuilder('ga')
            ->leftJoin('ga.categories', 'cat')
            ->where('cat.name = :category')
            ->orderBy('ga.name', 'ASC')
            ->setParameter('category', $category)
            ->getQuery()
            ->execute();
    }
}
