<?php

namespace Platformd\SpoutletBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryCategoryRepository extends EntityRepository
{
    public function findAllAlphabetically() {
        return $this->createQueryBuilder('gc')
            ->orderBy('gc.name', 'ASC')
            ->getQuery()
            ->execute();
    }
}
