<?php

namespace Platformd\SpoutletBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Platformd\SpoutletBundle\Entity\GamePage;

/**
 * GamePageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamePageRepository extends EntityRepository
{
    /**
     * @param string $site
     * @return \Platformd\SpoutletBundle\Entity\GamePage[]
     */
    public function findAllForSiteNewestFirst($site)
    {
        return $this->createSiteQueryBuilder($site)
            ->addOrderBy('gp.createdAt', 'DESC')
            ->getQuery()
            ->execute()
        ;
    }

    /**
     * @param integer $age
     * @param string $site
     * @return \Platformd\SpoutletBundle\Entity\GamePage[]
     */
    public function findActiveGamesForAge($age, $site)
    {
        // we don't use the age yet

        $qb = $this->createSiteQueryBuilder($site);
        $this->addPublishedQueryBuilder($qb);

        return $qb->getQuery()
            ->execute()
        ;
    }

    /**
     * @param $site
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function createSiteQueryBuilder($site)
    {
        return $this->createQueryBuilder('gp')
            ->leftJoin('gp.gamePageLocales', 'gpl')
            ->andWhere('gpl.locale = :site')
            ->setParameter('site', $site)
        ;
    }

    private function addPublishedQueryBuilder(QueryBuilder $qb)
    {
        return $qb->andWhere('gp.status = :status')
            ->setParameter('status', GamePage::STATUS_PUBLISHED)
        ;
    }
}