<?php

namespace Platformd\SpoutletBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use DateTime;
use DateTimeZone;

/**
 * GroupNewssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupNewsRepository extends EntityRepository
{
    public function getNewsForGroupMostRecentFirst($group)
    {
        return $this->createQueryBuilder('gn')
            ->where('gn.group = :groupId')
            ->andWhere('gn.deleted = false')
            ->setParameter('groupId', $group->getId())
            ->orderBy('gn.createdAt')
            ->getQuery()
            ->execute();
    }
}
