<?php

namespace Platformd\SpoutletBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use DateTime;
use DateTimeZone;

/**
 * GroupImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupImageRepository extends EntityRepository
{
    public function getImagesForGroupMostRecentFirst($group)
    {
        return $this->createQueryBuilder('gi')
            ->where('gi.group = :groupId')
            ->andWhere('gi.deleted = false')
            ->setParameter('groupId', $group->getId())
            ->orderBy('gi.createdAt', 'DESC')
            ->getQuery()
            ->execute();
    }

    public function getImageCountForGroup($group, $fromDate=null, $thruDate=null)
    {
        $qb = $this->createQueryBuilder('gi');

        $qb->where('gi.group = :groupId');
        $qb->setParameter('groupId', $group->getId());

        if($fromDate != null and $thruDate != null)
        {
            $qb->andWhere('gi.createdAt >= :fromDate')
               ->andWhere('gi.createdAt <= :thruDate')
               ->setParameter('fromDate', $fromDate)
               ->setParameter('thruDate', $thruDate);
        }

        $total = $qb->getQuery()
                    ->getResult();

        return count($total);
    }
}
