<?php

namespace Platformd\SpoutletBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use DateTime;
use DateTimeZone;

/**
 * GroupsLocaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupLocaleRepository extends EntityRepository
{
    public function getGroupCountForSite($site)
    {
        $qb = $this->createQueryBuilder('gl');
        $qb->select('count(gl.id)');
        $qb->where('gl.locale = :site');
        $qb->setParameter('site', $site);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
