sweepstakes_rules:
    pattern: /contest-sweeps/{slug}/contestrules
    defaults: { _controller: SweepstakesBundle:Frontend:rules, slug: null }

_sweeps_admin:
    resource: "routing/admin.yml"
    prefix:   "/admin/sweepstakes"

sweepstakes_index:
    pattern: /contest-sweeps
    defaults: { _controller: SweepstakesBundle:Frontend:index }

sweepstakes_show:
    pattern: /contest-sweeps/{slug}/{entryId}
    defaults: { _controller: SweepstakesBundle:Frontend:show, entryId: null }


