services:

    # forms
    platformd_sweeps.registration.form.type:
        class: Platformd\UserBundle\Form\Type\RegistrationFormType
        arguments:
            - %fos_user.model.user.class%
            - %platformd.news_source%
            - @session
            - @platformd.model.translator
            - @platformd.model.ip_lookup_util
            - @request
            - 1
        scope: request
        calls:
            - [ setPrefectures, [ %platformd.prefectures% ] ]
        tags:
            - { name: form.type }

    platformd_sweeps.entry.form.type:
        class: Platformd\SweepstakesBundle\Form\Type\SweepstakesEntryType
        arguments:
            - '@security.authorization_checker'
        tags:
            - { name: form.type }

    platformd_sweeps.entry.form.handler:
        class: Platformd\SweepstakesBundle\Form\Handler\SweepstakesEntryFormHandler
        arguments:
            - @request
            - @platformd_user.manager
            - @platformd_user.mailer
            - @doctrine.orm.entity_manager
            - @service_container
            - @platformd.model.ip_lookup_util
            - @platformd.user.api.manager
            - @platformd.util.site_util
            - @platformd.model.group_manager
            - @pd.cevo.api.api_manager
            - @platformd.model.translator
            - @media_exposer
        scope: request

    platformd_sweeps.model.sweepstakes_manager:
        class: Platformd\SweepstakesBundle\Model\SweepstakesManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@platformd.tags.model.tag_manager"
            - "@platformd.util.flash_util"
