services:
    platformd.repository.avatar:
        class:           Platformd\UserBundle\Entity\AvatarRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method:  getRepository
        arguments:
            - 'UserBundle:Avatar'
