services:
    # Forms
    platformd_user.registration.form.type:
        class: Platformd\UserBundle\Form\Type\RegistrationFormType
        arguments:
            - %fos_user.model.user.class%
            - %platformd.news_source%
            - @session
        calls:
            - [ setPrefectures, [ %platformd.prefectures% ] ]
        tags:
            - { name: form.type, alias: platformd_user_registration } 
    platformd_user.profile.form.type:
        class: Platformd\UserBundle\Form\Type\ProfileFormType
        arguments:
            - %fos_user.model.user.class%
        tags:
            - { name: form.type, alias: platformd_user_profile } 
    # User
    platformd_user.manager:
        class: Platformd\UserBundle\Entity\UserManager
        parent: fos_user.user_manager.default
        calls:
            - [ setContainer, ['@service_container'] ]
            - [ setFilesystem, ['@avatar_filesystem']]

    platformd.avatar_resolver:
        class:  'Platformd\UserBundle\AvatarPathResolver'
        arguments:
            - @avatar_filesystem
            - avatar
        parent: platformd.path_resolver
        tags:
            - { name: 'knp_media_exposer.resolver' }

    # our custom mailer
    platformd_user.mailer:
        class: Platformd\UserBundle\Mailer\Mailer
        parent: fos_user.mailer.default

    platformd_user.awa_video_login_redirect_listener:
        class: Platformd\UserBundle\EventListener\AwaVideoLoginRedirectListener
        arguments:
            - "@security.context"
            - %cevo_fake_api_url%
# put in place for debugging, removed for now
#        calls:
#            - [ setLogger, [ @logger ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    platformd_user.awa_video_session_id_cookie_listener:
        class: Platformd\UserBundle\EventListener\AwaVideoSessionIdCookieListener
        arguments:
            - "@security.context"
            - %base_host%
            - "%allow_faked_auth%"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    platformd_user.security_logout_handler:
        class: Platformd\UserBundle\Security\Logout\SuccessHandler
        arguments:
            - "@pd.cevo.cevo_auth_manager"
            - %base_host%
