services:
    platformd_user.registration.from.type:
        class: Platformd\UserBundle\Form\Type\RegistrationFormType
        arguments:
            - %fos_user.model.user.class%
        tags:
            - { name: form.type, alias: platformd_user_registration } 

