imports:
    - { resource: "validation.yml" }
    - { resource: "listeners.yml" }

parameters:
    platformd_user.mailer.parameters:
        confirmation.template: %fos_user.registration.confirmation.template%
        resetting.template: %fos_user.resetting.email.template%

services:

    platformd.security.user.authentication.provider.api:
        class: Platformd\UserBundle\Security\Provider\ApiAuthenticationProvider
        arguments:
            - '@platformd.user.api.manager'
            - '@platformd.security.user.provider.api'
            - '@security.user_checker'
            - ~
            - '@security.encoder_factory'
            - '%security.authentication.hide_user_not_found%'
            - '@pd.cevo.password_handler'

    platformd.user.api.manager:
        class: Platformd\UserBundle\Model\ApiManager
        arguments:
            - '%api_base_url%'
            - '%api_access_key%'
            - '%api_secret_key%'
            - "@logger"

    platformd.security.user.provider.api:
        class: Platformd\UserBundle\Security\Provider\ApiUserProvider
        arguments:
            - '@platformd.user.api.manager'
            - '@doctrine.orm.entity_manager'

    # Forms
    platformd_user.registration.form.type:
        class: Platformd\UserBundle\Form\Type\RegistrationFormType
        arguments:
            - %fos_user.model.user.class%
            - %platformd.news_source%
            - @session
            - @platformd.model.translator
            - @platformd.model.ip_lookup_util
            - @request
        scope: request
        calls:
            - [ setPrefectures, [ %platformd.prefectures% ] ]
        tags:
            - { name: form.type, alias: platformd_user_registration }

    platformd_user.profile.form.type:
        class: Platformd\UserBundle\Form\Type\ProfileFormType
        arguments:
            - %fos_user.model.user.class%
        tags:
            - { name: form.type, alias: platformd_user_profile }

    platformd_user.account_settings.form.type:
        class: Platformd\UserBundle\Form\Type\AccountSettingsType
        arguments:
            - '@security.encoder_factory'
            - '@security.context'
            - '@platformd.user.api.manager'
            - '%api_authentication%'
        tags:
            - { name: form.type, alias: platformd_user_profile }

    platformd_user.subscription_settings.form.type:
        class: Platformd\UserBundle\Form\Type\SubscriptionSettingsType
        arguments:
            - '@security.encoder_factory'
            - '@security.context'
            - '@platformd.user.api.manager'
            - '%api_authentication%'
        tags:
            - { name: form.type, alias: platformd_user_profile }


    platformd_user.registration.form.handler:
        class: Platformd\UserBundle\Form\Handler\RegistrationFormHandler
        arguments:
            - @fos_user.registration.form
            - @request
            - @platformd_user.manager
            - @platformd_user.mailer
            - @doctrine.orm.entity_manager
            - @service_container
            - @platformd.model.ip_lookup_util
        scope: request

    platformd_user.resetting.form.handler:
        class: Platformd\UserBundle\Form\Handler\ResettingFormHandler
        parent: fos_user.resetting.form.handler.default
        scope: request

    # User
    platformd_user.manager:
        class: Platformd\UserBundle\Entity\UserManager
        arguments:
            - "@platformd.model.translator"
        parent: fos_user.user_manager.default
        calls:
            - [ setContainer, ['@service_container'] ]
            - [ setFilesystem, ['@avatar_filesystem']]

    platformd.avatar_resolver:
        class:  'Platformd\UserBundle\AvatarPathResolver'
        arguments:
            - @avatar_filesystem
            - avatars
        parent: platformd.path_resolver
        tags:
            - { name: 'knp_media_exposer.resolver' }

    # our custom mailer
    platformd_user.mailer:
        class: Platformd\UserBundle\Mailer\Mailer
        arguments:
            - '@platformd.model.email_manager'
            - '@router'
            - '@templating'
            - '%platformd_user.mailer.parameters%'
            - '@platformd.util.site_util'

    platformd.model.avatar_manager:
        class: Platformd\UserBundle\Model\AvatarManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@avatar_filesystem'
            - '%s3_bucket_name%'
            - '%s3_private_bucket_name%'
            - '@platformd.s3'
            - '@platformd.util.queue_util'
            - '@fos_user.user_manager'

    platformd.avatar.s3.adapter:
        class: Gaufrette\Adapter\AmazonS3
        arguments:
            - @platformd.s3
            - "%s3_private_bucket_name%"
        calls:
            - [ "setDirectory", [ "images/avatars"]]

    # platformd.facebook.provider:
    #     class: Platformd\UserBundle\Security\User\Provider\FacebookProvider
    #     arguments:
    #         facebook: "@fos_facebook.api"
    #         userManager: "@fos_user.user_manager"
    #         validator: "@validator"
    #         container: "@service_container"

    # platformd.twitter.provider:
    #     class: Platformd\UserBundle\Security\User\Provider\TwitterProvider
    #     arguments:
    #         twitter_oauth: "@fos_twitter.api"
    #         userManager: "@fos_user.user_manager"
    #         validator: "@validator"
    #         session: "@session"
    #         api: "@fos_twitter.service"
    #         container: "@service_container"

    platformd_user.authentication_handler:
        class: Platformd\UserBundle\Handler\AuthenticationHandler
        arguments:
            - "@router"
            - "@fos_user.user_manager"
            - "@platformd.util.site_util"
            - "%api_authentication%"
            - "@platformd.model.translator"
            - '%base_host%'
