group_event_rsvp:
    pattern: /group-events/ajax/rsvp
    defaults: { _controller:"EventBundle:GroupEvent:rsvpAjax", site: ~ }
    requirements:
        _format: json
        _method: POST

group_event_disable:
    pattern: /group-events/ajax/disable
    defaults: { _controller:"EventBundle:GroupEvent:disableAjax", site: ~ }
    requirements:
        _format: json
        _method: POST

group_event_new:
    pattern: /groups/{slug}/event/new
    defaults: { _controller:"EventBundle:GroupEvent:new", site: ~ }

group_event_edit:
    pattern: /groups/{groupSlug}/event/edit/{eventSlug}
    defaults: { _controller:"EventBundle:GroupEvent:edit", site: ~ }

group_event_delete:
    pattern: /groups/{groupSlug}/event/delete/{eventSlug}
    defaults: { _controller:"EventBundle:GroupEvent:delete", site: ~ }

group_event_view:
    pattern: /groups/{groupSlug}/event/{eventSlug}
    defaults: { _controller:"EventBundle:GroupEvent:view", site: ~ }
