global_events_index:
    path: /events
    defaults: { _controller: EventBundle:GlobalEvent:index }

_user_event_list:
    path: /esi/USER_SPECIFIC/userEventList
    defaults: { _controller: EventBundle:GlobalEvent:_userEventList }

_global_event_user_info:
    path: /esi/USER_SPECIFIC/_globalEventUserInfo/{id}
    defaults: { _controller: EventBundle:GlobalEvent:_globalEventUserInfo }

global_event_contact:
    path: /events/contact/{id}
    defaults: { _controller:"EventBundle:GlobalEvent:contact", site: ~ }

global_event_attendees:
    path: /events/attendees/{id}
    defaults: { _controller:"EventBundle:GlobalEvent:attendees", site: ~ }

global_event_email_preview:
    path: /events/contact-preview/{slug}
    defaults: { _controller:"EventBundle:GlobalEvent:emailPreview", site: ~ }
    requirements:
        _method: POST

global_event_rsvp:
    path: /events/ajax/rsvp
    defaults: { _controller:"EventBundle:GlobalEvent:rsvpAjax", site: ~ }
    requirements:
        _format: json
        _method: POST

global_event_disable:
    path: /events/ajax/disable
    defaults: { _controller:"EventBundle:GlobalEvent:disableAjax", site: ~ }
    requirements:
        _format: json
        _method: POST

global_event_remove_attendee:
    path: /events/{id}/remove/{userId}
    defaults: { _controller: EventBundle:GlobalEvent:removeAttendee }

global_event_view:
    path: /public/{id}
    defaults: { _controller: EventBundle:GlobalEvent:view }

admin_events_index:
    path: /admin/events
    defaults: { _controller: EventBundle:GlobalEventAdmin:index }

admin_events_new:
    path: /admin/events/new
    defaults: { _controller: EventBundle:GlobalEventAdmin:newEvent }

admin_events_list:
    path: /admin/events/list/{site}
    defaults: { _controller: EventBundle:GlobalEventAdmin:list }

admin_events_new_import:
    path: /admin/events/new/import/{id}
    defaults: { _controller: EventBundle:GlobalEventAdmin:newFromImport }

admin_events_edit:
    path: /admin/events/edit/{id}
    defaults: { _controller: EventBundle:GlobalEventAdmin:editEvent }

admin_event_publish:
    path: /admin/events/publish/{id}
    defaults: { _controller: EventBundle:GlobalEventAdmin:publishEvent }

admin_event_unpublish:
    path: /admin/events/unpublish/{id}
    defaults: { _controller: EventBundle:GlobalEventAdmin:unpublishEvent }

admin_event_metrics:
    path: /admin/events/metrics
    defaults: { _controller: EventBundle:GlobalEventAdmin:metrics }

admin_event_summary_csv:
    path: /admin/event/summary-csv
    defaults: { _controller: EventBundle:GlobalEventAdmin:eventSummaryCsv }

admin_event_attendee_csv:
    path: /admin/event/attendee-csv/{eventType}/{id}
    defaults: { _controller: EventBundle:GlobalEventAdmin:eventAttendeeCsv, eventType: "group" }

global_event_register:
    path: /events/register/{id}
    defaults: { _controller:"EventBundle:GlobalEvent:register", site: ~ }
