admin_sweepstakes_index:
    pattern: /
    defaults: { _controller: SweepstakesBundle:Admin:index }

admin_sweepstakes_new:
    pattern: /new
    defaults: { _controller: SweepstakesBundle:Admin:new }

admin_sweepstakes_edit:
    pattern: /edit/{id}
    defaults: { _controller: SweepstakesBundle:Admin:edit }

admin_sweepstakes_approve:
    pattern: /admin/events/approve/{id}
    defaults: { _controller: SweepstakesBundle:Admin:approve }

admin_sweepstakes_unpublish:
    pattern: /admin/events/unpublish/{id}
    defaults: { _controller: SweepstakesBundle:Admin:unpublish }

admin_sweepstakes_metrics:
    pattern: /metrics
    defaults: { _controller: SweepstakesBundle:Admin:metrics }

admin_sweepstakes_metrics_show:
    pattern: /metrics/{id}
    defaults: { _controller: SweepstakesBundle:Admin:showMetrics }