api_group:
    path:    /groups/{groupId}
    defaults:   { _controller: ApiBundle:Api:group }

api_all_groups:
    path:    /allGroups/
    defaults:   { _controller: ApiBundle:Api:allGroups }

api_all_events:
    path:    /allEvents/
    defaults:   { _controller: ApiBundle:Api:allEvents }

api_event:
    path:    /events/{eventId}
    defaults:   { _controller: ApiBundle:Api:event }

api_entrySet:
    path:    /lists/{entrySetId}
    defaults:   { _controller: ApiBundle:Api:entrySet }

api_entry:
    path:    /entries/{entryId}
    defaults:   { _controller: ApiBundle:Api:entry }

api_user:
    path:    /users/{userId}
    defaults:   { _controller: ApiBundle:Api:user }

api_mobile:
    path:    /mobile
    defaults:   { _controller: ApiBundle:Api:mobile }



