
api_group:
    pattern:    /groups/{groupId}
    defaults:   { _controller: ApiBundle:Api:group }

api_event:
    pattern:    /events/{eventId}
    defaults:   { _controller: ApiBundle:Api:event }

api_entrySet:
    pattern:    /lists/{entrySetId}
    defaults:   { _controller: ApiBundle:Api:entrySet }

api_entry:
    pattern:    /entries/{entryId}
    defaults:   { _controller: ApiBundle:Api:entry }

api_user:
    pattern:    /users/{userId}
    defaults:   { _controller: ApiBundle:Api:user }



