
api_entrySet:
    pattern:    /list/{entrySetId}
    defaults:   { _controller: ApiBundle:Api:entrySet }

api_entry:
    pattern:    /entry/{entryId}
    defaults:   { _controller: ApiBundle:Api:entry }
