parameters:
    platformd_event.form.type.group_event.class: Platformd\EventBundle\Form\Type\GroupEventType
    platformd_event.form.type.group_event_wrapper.class: Platformd\EventBundle\Form\Type\GroupEventWrapperType

services:
    platformd_event.form.type.group_event:
        class: %platformd_event.form.type.group_event.class%
        arguments:
            - @security.context
        tags:
            - { name: form.type, alias: groupEvent }

    platformd_event.form.type.group_event_wrapper:
        class: %platformd_event.form.type.group_event_wrapper.class%
        arguments:
            - @security.context
        tags:
            - { name: form.type, alias: groupEventWrapper }
