services:
    platformd.event.listener.group_event_listener:
            class: Platformd\EventBundle\EventListener\GroupEventListener
            arguments:
                - "@translator"
                - "@platformd.model.site_util"
                - "@platformd.model.email_manager"
                - %sender_email_address%
                - %sender_email_name%
            tags:
                - { name: kernel.event_listener, event: platformd.event.approve, method: onApprove }
                - { name: kernel.event_listener, event: platformd.event.cancel, method: onCancel }
                - { name: kernel.event_listener, event: platformd.event.activate, method: onActivate }
            scope: request
