services:
    platformd.event.listener.group_event_listener:
            class: Platformd\EventBundle\EventListener\GroupEventListener
            arguments:
                - "@translator"
                - "@platformd.util.site_util"
                - "@platformd.model.email_manager"
                - "@router"
            tags:
                - { name: kernel.event_listener, event: platformd.event.approve, method: onApprove }
                - { name: kernel.event_listener, event: platformd.event.create, method: onCreate }
            #scope: request
