Platformd\MediaBundle\Entity\Media:
    properties:
        fileObject:
            - Image:
                mimeTypesMessage: 'The image must be in the JPG, PNG, or GIF format.'
                mimeTypes: ['image/jpeg', 'image/png', 'image/gif']
                groups: ['Avatar']
